import type { Question } from '../types';
import { questionBuilders } from './build';

/**
 * A+ Core 1 (220-1201) practice questions. Written from the objectives as an
 * outline; every word is original. Verify coverage against CompTIA's objectives.
 */

const m = questionBuilders('a1-d1');
const MOBILE: Question[] = [
  m.mcq('tap-to-pay', 'A customer pays by holding a phone a few centimetres from a terminal. Which wireless technology makes that work?',
    'NFC', ['Bluetooth Classic', 'Infrared', 'GPS'],
    'Near-field communication only works over a few centimetres, which is why it suits payments and tap-to-pair. Bluetooth reaches metres, and GPS only receives.', 'a1-d1-mobile-connections'),
  m.mcq('swollen-battery', 'A laptop’s case is bulging and the touchpad is lifting. What should you do?',
    'Power it off, unplug it, stop using it, and have the battery replaced and disposed of safely',
    ['Press the lid down and keep charging so it deflates', 'Puncture the battery to let the gas out', 'Charge it to 100% to recalibrate it'],
    'A swollen lithium-ion cell is a fire risk. Never puncture, crush or keep charging it; get it out of the device and to proper recycling.', 'a1-d1-battery-swelling'),
  m.multi('lid-parts', 'Which TWO parts are normally found in a laptop’s lid, behind the display?',
    ['Wi-Fi antennas', 'Webcam and microphone'], ['CPU cooler', 'RAM slots', 'Battery'],
    'The antennas run up the lid for a better signal, and the webcam and mic sit in the bezel. The CPU, RAM and battery live in the base.', 'a1-d1-display-components'),
  m.mcq('dead-touch-strip', 'A tablet shows a perfect picture but ignores touches along one edge. Which part has most likely failed?',
    'The digitizer', ['The backlight', 'The GPU', 'The battery'],
    'The digitizer is the touch-sensing layer. A backlight failure would dim the picture, and a GPU fault would corrupt it.', 'a1-d1-digitizer'),
  m.order('bt-pair', 'Put the steps for pairing a Bluetooth headset with a phone in order.',
    ['Turn Bluetooth on in the phone’s settings', 'Put the headset into pairing mode', 'Choose the headset from the phone’s list of devices', 'Accept the pairing prompt or enter the PIN', 'Play some audio to test it'],
    'The headset has to be discoverable before the phone can find it, and you confirm the pairing before you test.', 'a1-d1-bluetooth-pairing'),
  m.match('mobile-terms', 'Match each term with what it does.',
    [['MDM', 'Enrolls company phones and enforces passcodes and apps'], ['Tethering', 'Shares a phone’s cellular data with one device, often by USB cable'],
     ['Mobile hotspot', 'Shares a phone’s cellular data as a Wi-Fi network'], ['NFC', 'Tap-to-pay range of a few centimetres']],
    'Tethering and a hotspot both share cellular data. Tethering is usually a direct cable or Bluetooth link to one device; a hotspot broadcasts Wi-Fi for several.', 'a1-d1-hotspot-tethering'),
  m.mcq('screen-rotate', 'Which sensors let a phone rotate its screen when you turn it sideways?',
    'Accelerometer and gyroscope', ['Barometer and light sensor', 'NFC chip', 'Digitizer'],
    'They sense orientation and movement. The barometer measures air pressure and the light sensor sets brightness.', 'a1-d1-accelerometer-gyro'),
  m.mcq('oled', 'Which display type has no backlight because each pixel produces its own light?',
    'OLED', ['IPS LCD', 'TN LCD', 'VA LCD'],
    'IPS, TN and VA are all LCD types, which need a backlight (usually LED). OLED pixels glow on their own, so black pixels are truly off.', 'a1-d1-display-types'),
  m.mcq('new-phone-mfa', 'A user gets a new phone and can no longer approve sign-ins with the company authenticator app. Why?',
    'The authenticator’s secret was tied to the old phone, so it must be set up again on the new one',
    ['Authenticator apps only work on phones older than a year', 'The new phone’s cellular plan blocks it', 'NFC must be enabled first'],
    'The app’s secret lives on the device that enrolled it. IT has to re-enroll the new phone, ideally after verifying the user.', 'a1-d1-mfa-authenticator'),
  m.mcq('fn-toggle', 'A laptop’s Wi-Fi stops working and nothing is broken in Device Manager. What quick check applies?',
    'Look for a Fn-key toggle or airplane-mode switch that turned the radio off',
    ['Replace the motherboard', 'Reinstall the operating system', 'Swap the battery'],
    'Fn combinations and airplane mode toggle radios, brightness and the touchpad. They are the cheapest thing to rule out first.', 'a1-d1-laptop-keyboard-fn'),
];

const n = questionBuilders('a1-d2');
const NETWORK: Question[] = [
  n.mcq('ssh-port', 'Which port does SSH use by default?', 'TCP 22', ['TCP 21', 'TCP 23', 'TCP 25'],
    'SSH is 22. Port 21 is FTP control, 23 is Telnet (which is unencrypted) and 25 is SMTP.', 'a1-d2-port-ssh-telnet'),
  n.multi('encrypted-ports', 'Which TWO ports carry traffic that is encrypted by default?',
    ['TCP 22', 'TCP 443'], ['TCP 23', 'TCP 80', 'TCP 110'],
    'SSH (22) and HTTPS (443) encrypt. Telnet (23), HTTP (80) and POP3 (110) send in clear text unless wrapped in something else.', 'a1-d2-port-http-https'),
  n.match('port-match', 'Match each service with its well-known port.',
    [['DNS', '53'], ['DHCP server', '67'], ['SMB file sharing', '445'], ['Remote Desktop', '3389']],
    'DNS is 53, the DHCP server listens on UDP 67 (clients use 68), SMB is 445, and RDP is 3389.', 'a1-d2-port-smb-rdp'),
  n.order('dora', 'Put the DHCP exchange in order.',
    ['The client broadcasts a Discover', 'A server answers with an Offer', 'The client sends a Request for that offer', 'The server sends an Acknowledgement'],
    'Discover, Offer, Request, Acknowledge: DORA. The lease only begins after the final acknowledgement.', 'a1-d2-dhcp-dora'),
  n.mcq('apipa', 'A PC has the address 169.254.33.8 and cannot reach the internet. What does that address tell you?',
    'It could not get an address from DHCP and gave itself a link-local one',
    ['It is a public address assigned by the ISP', 'The router has a static route to it', 'The PC has an IPv6 address'],
    'Windows falls back to APIPA (169.254.0.0/16) when no DHCP server answers. Check the cable, the switch and the DHCP service.', 'a1-d2-apipa'),
  n.mcq('public-address', 'Which of these addresses is NOT in a private IPv4 range?', '172.32.4.9',
    ['10.20.30.40', '192.168.1.50', '172.20.0.5'],
    'The private 172 range is only 172.16.0.0 to 172.31.255.255, so 172.32.x.x is public.', 'a1-d2-private-ranges'),
  n.mcq('cat6a', 'You need 10 Gbps over the full 100 m of copper. What is the usual minimum cable category?',
    'Cat 6a', ['Cat 5', 'Cat 5e', 'Cat 3'],
    'Cat 6a supports 10 Gbps for 100 m. Cat 6 manages it only for short runs, and Cat 5e is a gigabit cable.', 'a1-d2-cable-categories'),
  n.mcq('single-mode', 'Two buildings are 8 km apart and need a fiber link. Which cable type fits?',
    'Single-mode fiber', ['Multimode fiber', 'Cat 6a', 'Coaxial cable'],
    'Single-mode carries light much further with less loss. Multimode is cheaper and suits inside a building or campus.', 'a1-d2-fiber-types'),
  n.mcq('nonoverlap', 'Which set of 2.4 GHz Wi-Fi channels does not overlap in North America?',
    '1, 6 and 11', ['1, 2 and 3', '3, 6 and 9', '5, 10 and 15'],
    'Each channel is about 22 MHz wide and spaced 5 MHz apart, so only 1, 6 and 11 stay clear of one another.', 'a1-d2-wifi-channels'),
  n.mcq('udp-call', 'A video call would rather drop a packet than wait for it to be resent. Which transport protocol suits it?',
    'UDP', ['TCP', 'ICMP', 'ARP'],
    'UDP has no retransmission, so late data is simply skipped. TCP’s guaranteed delivery would add delay and stutter.', 'a1-d2-tcp-vs-udp'),
  n.mcq('dns-by-name', 'Websites fail when you type the name but load when you type the IP address. What is broken?',
    'DNS name resolution', ['The default gateway', 'The network cable', 'The subnet mask'],
    'If IP traffic works, the link and routing are fine. Names are failing, so look at the DNS server setting or the DNS service.', 'a1-d5-dns-failure'),
  n.match('dns-records', 'Match each DNS record type with what it holds.',
    [['A', 'An IPv4 address'], ['AAAA', 'An IPv6 address'], ['MX', 'The mail server for a domain'], ['CNAME', 'An alias pointing to another name']],
    'A and AAAA map names to addresses, MX names the mail server, and a CNAME points one name at another.', 'a1-d2-dns-records'),
  n.mcq('poe-ap', 'A wireless access point must go on a ceiling with no power outlet nearby. What lets one cable do the job?',
    'A PoE switch or injector', ['A crossover cable', 'A loopback plug', 'A KVM switch'],
    'Power over Ethernet sends power and data over the same twisted pair, so the access point needs only one cable.', 'a1-d2-poe'),
  n.mcq('slash24', 'How many usable host addresses does a /24 IPv4 network give?', '254', ['256', '255', '24'],
    'A /24 has 256 addresses, minus the network address and the broadcast address.', 'a1-d2-subnet-mask'),
  n.mcq('switch-mac', 'Which device forwards frames between devices on one network by looking at MAC addresses?',
    'A switch', ['A router', 'A modem', 'A repeater'],
    'A switch learns which MAC address sits on which port. A router works with IP addresses to move traffic between networks.', 'a1-d2-switch-vs-router'),
  n.mcq('tone-trace', 'You need to find which wall jack a cable in the closet leads to. Which tool set do you use?',
    'A toner and probe', ['A loopback plug', 'A multimeter on the outlet', 'A cable stripper'],
    'The toner puts a signal on the wire and the probe picks it up, so you can trace it through walls and bundles.', 'a1-d2-tools-network'),
  n.mcq('ipv6-length', 'How many bits long is an IPv6 address?', '128', ['32', '64', '48'],
    'IPv6 is 128 bits, written as eight groups of four hex digits. IPv4 is 32 bits and a MAC address is 48.', 'a1-d2-ipv6-basics'),
];

const h = questionBuilders('a1-d3');
const HARDWARE: Question[] = [
  h.mcq('eps8', 'A builder has an 8-pin (4+4) cable left over near the top of the board. What does it power?',
    'The CPU', ['The graphics card', 'The SATA drives', 'The front USB ports'],
    'The EPS 8-pin feeds the CPU’s voltage regulators. Skipping it usually means the board will not power up.', 'a1-d3-mb-eps8'),
  h.mcq('ddr-notch', 'Can a DDR4 module be installed in a DDR5 slot?', 'No, the notch sits in a different place so it will not fit',
    ['Yes, it just runs slower', 'Yes, if you enable XMP', 'Yes, but only in a laptop'],
    'Each DDR generation moves the key notch so you cannot fit the wrong one. Forcing it damages the slot.', 'a1-d3-ram-ddr'),
  h.mcq('dual-channel', 'Why should two RAM sticks go in the slots the motherboard manual names?',
    'So they run in dual-channel mode for more memory bandwidth', ['So the PC will boot at all', 'To double the total capacity', 'To lower the voltage'],
    'Slots are colour-coded or paired by channel. Using the wrong pair still works, but at single-channel speed.', 'a1-d3-ram-channels'),
  h.mcq('thermal-paste', 'Why is thermal paste applied between a CPU and its cooler?',
    'It fills microscopic gaps so heat moves into the heatsink', ['It glues the cooler on', 'It insulates the CPU from static', 'It lowers the fan noise'],
    'Metal surfaces look flat but are rough. Air in the gaps insulates, so a thin layer of paste conducts heat far better.', 'a1-d3-cpu-cooling'),
  h.mcq('nvme-fast', 'Both are M.2. Why is an NVMe SSD faster than an M.2 SATA SSD?',
    'NVMe uses PCIe lanes instead of the slower SATA interface', ['NVMe drives use spinning platters', 'NVMe uses a bigger connector', 'M.2 SATA drives have no cache'],
    'M.2 is only the shape. SATA-mode M.2 drives are capped by the SATA interface; NVMe talks to the CPU over PCIe.', 'a1-d3-storage-nvme-sata'),
  h.multi('raid-redundant', 'Which THREE RAID levels can survive the loss of one drive?',
    ['RAID 1', 'RAID 5', 'RAID 10'], ['RAID 0'],
    'Mirroring (1, 10) and parity (5) keep the data if a drive fails. RAID 0 stripes for speed and loses everything if one drive dies.', 'a1-d3-raid-levels'),
  h.order('laser-steps', 'Put the laser printing process in order.',
    ['Processing', 'Charging', 'Exposing', 'Developing', 'Transferring', 'Fusing', 'Cleaning'],
    'The page is rendered, the drum charged and written with the laser, toner is attracted to it, moved to paper, melted on by the fuser, and the drum is cleaned.', 'a1-d3-laser-printer-steps'),
  h.mcq('usb3', 'What is the speed of USB 3.2 Gen 1 (formerly called USB 3.0)?', '5 Gbps', ['480 Mbps', '10 Gbps', '40 Gbps'],
    'USB 2.0 is 480 Mbps, USB 3.2 Gen 1 is 5 Gbps, Gen 2 is 10 Gbps and USB4 reaches 40 Gbps.', 'a1-d3-usb-versions'),
  h.match('video-ports', 'Match each video connection with its description.',
    [['HDMI', 'Digital video and audio, common on TVs'], ['DisplayPort', 'Digital video and audio, common on PC monitors'],
     ['VGA', 'Analog video only'], ['USB-C with DP Alt Mode', 'Video over a USB-C port']],
    'HDMI and DisplayPort are digital and carry sound. VGA is the analog holdover, and USB-C can carry DisplayPort video if the port supports it.', 'a1-d3-video-connectors'),
  h.mcq('tpm', 'Which component is a chip on the board that stores keys and helps measure a trusted boot?',
    'The TPM', ['The CMOS battery', 'The chipset', 'The PSU'],
    'The Trusted Platform Module holds encryption keys (BitLocker uses it). Secure Boot is a firmware feature that only loads signed bootloaders.', 'a1-d3-secure-boot-tpm'),
  h.mcq('lga-pins', 'On an LGA socket, where are the pins?', 'In the socket, with flat pads on the CPU', ['On the CPU', 'On the cooler', 'Soldered to the board'],
    'LGA stands for land grid array. Bent socket pins are the classic hazard, so check them before seating a CPU.', 'a1-d3-mb-cpu-socket'),
  h.mcq('psu-12v', 'Which power supply rail feeds most of a modern PC’s CPU and graphics card?', '+12 V', ['+3.3 V', '+5 V', '-12 V'],
    'The heavy loads run from +12 V, while +5 V and +3.3 V feed logic and some drives.', 'a1-d3-psu-rails'),
  h.mcq('ecc', 'Where is ECC memory mostly used, and why?', 'In servers, where it detects and corrects single-bit errors',
    ['In gaming PCs, where it raises clock speed', 'In phones, where it saves power', 'In printers, where it stores fonts'],
    'Error-correcting memory guards against silent corruption, which matters more on machines that run for months.', 'a1-d3-ram-ecc'),
  h.mcq('modular-psu', 'What is a modular power supply?', 'One whose cables unplug from the unit so you only attach what you need',
    ['One that accepts any voltage worldwide', 'One built into the motherboard', 'One that has two fans'],
    'Fewer cables means less clutter and better airflow in the case.', 'a1-d3-psu-modular'),
  h.mcq('pcie-x16', 'What normally goes in the long PCIe x16 slot closest to the CPU?', 'The graphics card', ['A Wi-Fi card', 'RAM', 'A sound card only'],
    'The x16 slot has the most lanes and the shortest path to the CPU, which is what a GPU wants.', 'a1-d3-mb-pcie-x16'),
  h.mcq('maintenance-kit', 'What does a laser printer maintenance kit usually replace?', 'The fuser and rollers', ['The laser and drum motor', 'The toner cartridge only', 'The network card'],
    'They are the parts that wear out by page count, so the kit is swapped on a schedule.', 'a1-d3-printer-maintenance'),
];

const v = questionBuilders('a1-d4');
const VIRT: Question[] = [
  v.mcq('type1', 'Which hypervisor type runs directly on the hardware with no host operating system?', 'Type 1 (bare metal)', ['Type 2 (hosted)', 'A container engine', 'A remote desktop client'],
    'Type 1 hypervisors like Hyper-V Server or ESXi are installed as the OS. A Type 2, such as VirtualBox, runs as an app on top of one.', 'a1-d4-hypervisor-types'),
  v.mcq('iaas', 'In IaaS, which of these does the customer manage?', 'The guest operating system, apps and data', ['The physical servers', 'The data center’s power', 'The hypervisor'],
    'The provider runs the hardware and virtualization layer; the customer runs everything from the operating system up.', 'a1-d4-cloud-iaas'),
  v.mcq('saas', 'Which of these is an example of SaaS?', 'A hosted email and office suite you sign in to', ['Renting a virtual server to install your own OS', 'A platform for deploying your own code without managing servers', 'Renting rack space in a data center'],
    'With SaaS you only use the application. Renting servers is IaaS and a code-hosting platform is PaaS.', 'a1-d4-cloud-paas-saas'),
  v.mcq('snapshot', 'A tech takes a VM snapshot before installing updates. What is it for?', 'To roll the VM back if the update goes wrong, though it is not a backup',
    ['To replace nightly backups', 'To copy the VM to another host', 'To free up disk space'],
    'A snapshot records a point in time on the same storage. If that storage fails the snapshot goes with it, so it is not a backup.', 'a1-d4-vm-snapshot'),
  v.mcq('container', 'How is a container different from a virtual machine?', 'It shares the host’s kernel instead of running a full guest OS',
    ['It needs its own hypervisor', 'It emulates separate hardware', 'It can only run Windows'],
    'Containers package an app and its dependencies on a shared kernel, which makes them small and quick to start.', 'a1-d4-containers'),
  v.match('cloud-models', 'Match each cloud model with its description.',
    [['Public', 'Shared provider infrastructure open to many customers'], ['Private', 'Infrastructure used by a single organization'],
     ['Hybrid', 'A mix of private and public cloud'], ['Community', 'Shared by organizations with common needs']],
    'The model describes who shares the infrastructure, not where it physically sits.', 'a1-d4-cloud-deployment'),
  v.mcq('elasticity', 'A shop’s website slows down during a sale, and the provider automatically adds capacity, then removes it afterward. What is this called?',
    'Rapid elasticity', ['Multitenancy', 'Snapshotting', 'Tethering'],
    'Elasticity is resources scaling up and down with demand, so you only pay for what you use.', 'a1-d4-cloud-elasticity'),
  v.mcq('vt-x', 'A hypervisor refuses to start 64-bit VMs on a fairly new PC. What setting is likely off?', 'Hardware virtualization (Intel VT-x or AMD-V) in UEFI',
    ['Secure Boot', 'ECC memory', 'The CMOS battery'],
    'Modern hypervisors need the CPU’s virtualization extensions, and they are often disabled by default in firmware.', 'a1-d3-virtualization-bios'),
  v.mcq('vdi', 'What is VDI?', 'Users’ desktops run as VMs in a data center and are reached from any device', ['A type of video cable', 'A tool for cloning hard drives', 'A network protocol for printers'],
    'Virtual desktop infrastructure keeps the desktop and its data centrally, so a thin device or laptop just displays it.', 'a1-d4-vdi'),
];

const t = questionBuilders('a1-d5');
const TROUBLE: Question[] = [
  t.order('method', 'Put CompTIA’s troubleshooting methodology in order.',
    ['Identify the problem', 'Establish a theory of probable cause', 'Test the theory to determine the cause', 'Establish a plan of action and implement the solution',
     'Verify full system functionality and implement preventive measures', 'Document findings, actions and outcomes'],
    'You find out what is wrong before guessing why, prove the guess before fixing, fix it, confirm it worked, and write it down.', 'a1-d5-method-steps'),
  t.mcq('theory-fails', 'Your theory of probable cause turned out to be wrong. What is the next step?', 'Establish a new theory, or escalate to someone with more experience',
    ['Implement the fix anyway', 'Document the problem as resolved', 'Replace the whole computer'],
    'A failed test sends you back to theorizing. If you run out of ideas, escalating is part of the process, not a failure.', 'a1-d5-method-escalate'),
  t.mcq('fuser', 'Laser printer output looks fine but the toner smears when you rub it. Which part has failed?', 'The fuser', ['The pickup roller', 'The drum', 'The spooler'],
    'The fuser’s heat and pressure melt toner into the paper. If it is not working, the toner just sits on top.', 'a1-d5-printer-smudge'),
  t.mcq('burning', 'A PC gives off a burning smell. What is the right first move?', 'Power it off and unplug it immediately',
    ['Open the case with it running to look', 'Run a diagnostic to find the fault', 'Spray it with contact cleaner'],
    'Fire and shock risk come first. Then look for a failed PSU, a swollen capacitor or a shorted component.', 'a1-d5-burning-smell'),
  t.mcq('no-power', 'A desktop shows no lights and no fans when you press the power button. What do you check first?', 'The outlet, power cable and PSU switch',
    ['The RAM modules', 'The graphics driver', 'The BIOS boot order'],
    'Start with the simplest and cheapest: is it plugged in and switched on? Then the PSU and front-panel connector.', 'a1-d5-no-power'),
  t.mcq('post-beeps', 'A PC powers on, shows nothing, and gives a pattern of beeps. What are the beeps?', 'POST codes reporting a hardware fault',
    ['A sign the OS is updating', 'A network error', 'A printer alert'],
    'The firmware can’t always show text before video is ready, so it beeps a code. Look the pattern up in the board’s manual.', 'a1-d5-no-post-beeps'),
  t.mcq('overheat', 'A PC shuts off by itself only when gaming. What is the most likely cause?', 'Overheating', ['A bad keyboard', 'A DNS problem', 'A weak Wi-Fi signal'],
    'Load raises temperature. Dust, a failed fan, or dry thermal paste can trip the CPU’s thermal shutdown.', 'a1-d5-overheating-shutdown'),
  t.mcq('degraded', 'A RAID 5 array reports “degraded”. What does that mean?', 'A drive has failed; the data is available but redundancy is gone until you replace it',
    ['The array is full', 'The controller battery is low', 'All the data is lost'],
    'RAID 5 survives one failure, but a second failure before the rebuild finishes would lose the data, so replace the drive promptly.', 'a1-d5-raid-degraded'),
  t.mcq('ip-conflict', 'Windows warns that another system is using the same IP address. What likely happened?', 'Two devices have the same address, often one set statically inside the DHCP range',
    ['The DNS server is down', 'The cable is too long', 'The subnet mask is 255.255.255.0'],
    'Duplicate addresses cause dropouts on both devices. Fix by moving the static address outside the DHCP scope or reserving it.', 'a1-d5-ip-conflict'),
  t.mcq('clock-resets', 'A PC loses its date, time and firmware settings each time it is unplugged. What should you replace?', 'The CMOS battery', ['The power supply', 'The hard drive', 'The RAM'],
    'The coin cell keeps the clock and settings alive without mains power. A dead one loses them.', 'a1-d5-clock-resets'),
  t.mcq('spooler', 'Print jobs pile up in the queue and nothing prints. What is a common Windows fix?', 'Clear the queue and restart the Print Spooler service',
    ['Reinstall Windows', 'Replace the toner', 'Change the Wi-Fi channel'],
    'The spooler service holds jobs. A stuck job can jam it, and restarting it after clearing the queue usually frees things up.', 'a1-d5-printer-queue'),
  t.mcq('dim-screen', 'A laptop screen looks black, but you can faintly see the desktop with a flashlight. What failed?', 'The backlight', ['The GPU', 'The RAM', 'The hard drive'],
    'The image is still being drawn, only the light behind the panel is out. An external monitor working would confirm the GPU is fine.', 'a1-d5-display-dim'),
  t.multi('hdd-failing', 'Which TWO signs point to a failing hard drive?',
    ['Clicking or grinding noises from the drive', 'Read or write errors and very slow file access'], ['Loud fan noise at boot', 'A blue power LED', 'Static shocks from the case'],
    'Mechanical drives warn with noise, slow access and errors. Back up immediately, then replace the drive.', 'a1-d5-drive-failing'),
  t.mcq('phone-no-charge', 'A phone will not charge. What do you try before replacing the battery?', 'A different cable and charger, and clear lint from the port',
    ['Factory reset', 'Replace the screen', 'Update the carrier settings'],
    'Cables wear out and pocket lint packs the port. Both are cheap to check.', 'a1-d5-mobile-no-charge'),
  t.mcq('bsod-driver', 'A blue screen starts appearing right after new hardware is installed. What is the most common cause?', 'A bad or incompatible driver',
    ['A dead CMOS battery', 'A DNS misconfiguration', 'Too many browser tabs'],
    'Drivers run with kernel privileges, so a faulty one can crash the whole system. Roll back or update it.', 'a1-d5-bsod'),
  t.mcq('no-boot-device', 'A PC says “no boot device found”, but the drive tests fine. What should you check?', 'The boot order in UEFI and whether a USB stick or disc is left in',
    ['The DNS server', 'The printer queue', 'The Wi-Fi password'],
    'The firmware may be trying the wrong device first. Loose data cables and a changed boot mode are the next suspects.', 'a1-d5-boot-device'),
  t.mcq('monitor-flicker', 'An external monitor flickers. What is a common cause?', 'A loose cable or an unsupported refresh rate',
    ['A full hard drive', 'A weak Wi-Fi signal', 'An expired license'],
    'Reseat or replace the cable first, then check that the refresh rate matches what the monitor supports.', 'a1-d5-display-flicker'),
  t.order('no-network', 'A wired PC has no network at all. Put a sensible order of checks first to last.',
    ['Check the link light and the cable', 'Check the switch port', 'Check the IP configuration with ipconfig', 'Ping the default gateway', 'Ping a public name to test DNS'],
    'Work from the physical layer outwards: cable, port, address, gateway, then name resolution.', 'a1-d5-network-no-connectivity'),
  t.mcq('slow-floor', 'Users on one floor report slow wired network speeds. Which is a likely cause?', 'A bad cable or port negotiating at a lower speed',
    ['A CMOS battery', 'A dead pixel', 'A printer driver'],
    'A damaged cable can force a link down to 100 Mbps or cause errors. Check the switch port’s negotiated speed.', 'a1-d5-network-slow'),
];

export const A1_QUESTIONS: Question[] = [...MOBILE, ...NETWORK, ...HARDWARE, ...VIRT, ...TROUBLE];
export default A1_QUESTIONS;
