import type { Question } from '../types';
import { questionBuilders } from './build';

/**
 * A+ Core 2 (220-1202) practice questions. Written from the objectives as an
 * outline; every word is original. Verify coverage against CompTIA's objectives.
 */

const o = questionBuilders('a2-d1');
const OS: Question[] = [
  o.mcq('home-domain', 'A small business bought PCs with Windows 11 Home and now wants to join them to its Active Directory domain. What is the fix?',
    'Upgrade the PCs to Windows Pro or higher', ['Enable domain join in Settings > Accounts', 'Install the Remote Desktop role', 'Change the file system to NTFS'],
    'Domain join is a business feature that Home does not include. Pro, Enterprise and Education can join a domain.', 'a2-d1-editions-domain'),
  o.mcq('win11-tpm', 'An older PC runs Windows 10 well but fails the Windows 11 compatibility check. Which missing feature is the most likely cause?',
    'TPM 2.0 (or UEFI with Secure Boot)', ['A discrete graphics card', 'A touch screen', 'A DVD drive'],
    'Windows 11 requires a TPM 2.0 chip and UEFI Secure Boot for its security features. Graphics cards, touch and optical drives are not required.', 'a2-d1-win11-requirements'),
  o.mcq('clean-install', 'A technician is reassigning a slow, cluttered PC to a new employee and wants to remove years of leftover software. Which installation type fits best?',
    'A clean install', ['An in-place upgrade', 'A repair install that keeps files', 'System Restore to last week'],
    'A clean install wipes the drive and starts fresh. An in-place upgrade or repair keeps the old clutter.', 'a2-d1-inplace-vs-clean'),
  o.mcq('pxe', 'A technician must deploy Windows to 40 identical PCs without carrying a USB drive to each. Which boot method fits?',
    'PXE network boot', ['Safe Mode', 'An optical disc in each PC', 'Boot from a floppy image'],
    'PXE boots each PC from an image server over the network, so one setup serves many machines.', 'a2-d1-install-sources'),
  o.mcq('gpt-4tb', 'A new 4 TB drive shows only 2 TB usable. What is the most likely cause?',
    'It was initialized as MBR and needs converting to GPT', ['It needs a new drive letter', 'NTFS cannot handle 4 TB', 'It needs a firmware update'],
    'MBR addresses at most 2 TB. GPT handles far larger disks, and NTFS itself is not the limit.', 'a2-d1-gpt-vs-mbr'),
  o.mcq('exfat-portable', 'You need one file system for a portable drive used on Windows and macOS with 8 GB video files. Which fits?',
    'exFAT', ['FAT32', 'NTFS', 'ext4'],
    'FAT32 cannot store a file above 4 GB. NTFS is Windows-native and Macs read it but do not write by default, and ext4 is a Linux file system.', 'a2-d1-exfat-usb'),
  o.mcq('dhcp-refresh', 'A PC holds a bad DHCP lease. Which pair of commands gets it a fresh one?',
    'ipconfig /release, then ipconfig /renew', ['ipconfig /flushdns, then nslookup', 'netstat -an, then tracert', 'gpupdate /force, then sfc /scannow'],
    'Release gives up the current lease and renew asks the DHCP server for a new one. flushdns only clears the DNS cache.', 'a2-d1-cmd-ipconfig'),
  o.mcq('slow-route', 'Web pages load slowly. Which command shows where along the route to the site the delay begins?',
    'tracert (or pathping)', ['ipconfig /all', 'nslookup', 'netstat'],
    'tracert lists each router hop with its response time. ipconfig shows local settings, nslookup tests DNS and netstat lists connections.', 'a2-d1-cmd-tracert'),
  o.mcq('sfc', 'Windows behaves oddly and you suspect damaged system files. Which elevated command scans and repairs them?',
    'sfc /scannow', ['chkdsk /r', 'gpupdate /force', 'diskpart'],
    'System File Checker replaces damaged protected files. chkdsk looks at the file system and bad sectors, not protected system files.', 'a2-d1-cmd-sfc'),
  o.mcq('gpupdate', 'You changed a Group Policy setting and want a PC to apply it immediately. Which command?',
    'gpupdate /force', ['gpresult /r', 'ipconfig /renew', 'net use'],
    'gpupdate /force refreshes policy at once. gpresult only reports what already applied.', 'a2-d1-cmd-gpupdate'),
  o.mcq('chmod', 'A Linux script must be executable by its owner but only readable by everyone else. Which command fits?',
    'chmod 744 script.sh', ['chmod 777 script.sh', 'chmod 644 script.sh', 'chmod 477 script.sh'],
    'Owner 7 (read, write, execute); group and others 4 (read). 644 would leave the owner unable to execute it.', 'a2-d1-linux-chmod'),
  o.mcq('grep', 'Which Linux command searches for a text string inside the files of a folder?',
    'grep -r', ['find', 'chown', 'df'],
    'grep searches inside files. find locates files by name or attribute, chown changes ownership and df reports free space.', 'a2-d1-linux-grep-find'),
  o.mcq('time-machine', 'A Mac user wants automatic, versioned backups to an external drive. Which built-in feature?',
    'Time Machine', ['Spotlight', 'Keychain', 'Mission Control'],
    'Time Machine backs up on a schedule and keeps versions. Spotlight searches, Keychain stores passwords and Mission Control manages desktops.', 'a2-d1-mac-features'),
  o.multi('cpu-tools', 'Which TWO Windows tools show which program is using the CPU right now?',
    ['Task Manager', 'Resource Monitor'], ['Disk Management', 'Event Viewer', 'Registry Editor'],
    'Both show live per-process usage. Disk Management handles partitions, Event Viewer shows logs and the Registry Editor edits configuration.', 'a2-d1-tool-perfmon-resmon'),
  o.mcq('event-viewer', 'A service crashed overnight. Where do you find the error messages with timestamps?',
    'Event Viewer', ['Device Manager', 'Disk Cleanup', 'Windows Firewall'],
    'Event Viewer keeps application, system and security logs, so the failure is recorded with the time and source.', 'a2-d1-tool-eventviewer'),
  o.match('win-tools', 'Match each Windows tool with what it does.',
    [['Device Manager', 'Installs and troubleshoots hardware drivers'], ['Disk Management', 'Initializes, formats and assigns letters to drives'],
     ['services.msc', 'Starts, stops and configures background services'], ['regedit', 'Edits the Windows configuration database']],
    'Each snap-in has one job. Back up registry keys before you change them.', 'a2-d1-tool-devmgr-diskmgmt'),
  o.match('linux-cmds', 'Match each Linux command with what it does.',
    [['ls', 'Lists the files in a folder'], ['pwd', 'Prints the current directory'], ['chmod', 'Changes file permissions'], ['grep', 'Searches for text inside files']],
    'These are the everyday commands for moving around, checking permissions and searching.', 'a2-d1-linux-navigation'),
  o.mcq('private-profile', 'A laptop cannot see shared printers on the office network although internet works. The office connection is set to Public. What should change?',
    'Set the network profile to Private', ['Replace the network card', 'Reinstall the driver on the print server', 'Disable the firewall permanently'],
    'The Public profile turns network discovery and sharing off. Private allows them on a network you trust.', 'a2-d1-net-profiles'),
  o.mcq('rdp-home', 'A user wants to Remote Desktop into their Windows 11 Home PC from work. What is the problem?',
    'Home can connect out but cannot host Remote Desktop connections', ['TCP 443 must be open', 'Home PCs must be on a domain', 'RDP only works on Linux'],
    'Hosting Remote Desktop needs Pro or higher. The service uses TCP 3389 and should sit behind a VPN.', 'a2-d1-net-rdp'),
  o.mcq('domain-choice', 'A company of 200 PCs wants one set of accounts and central policy. Which model fits?',
    'A domain using Active Directory', ['A workgroup', 'The Public network profile', 'Peer-to-peer file sharing'],
    'A workgroup keeps accounts on each PC. A domain centralises accounts and policy.', 'a2-d1-net-workgroup-domain'),
  o.mcq('net-use', 'Which command maps a network share to drive Z: from a command prompt?',
    'net use Z: \\\\server\\share', ['map Z: \\\\server\\share', 'mount Z: \\\\server\\share', 'netstat Z: \\\\server\\share'],
    'net use maps and lists network resources. Add /persistent:yes to keep the drive after a restart.', 'a2-d1-cmd-net-use'),
];

const s = questionBuilders('a2-d2');
const SECURITY: Question[] = [
  s.mcq('mantrap', 'A data center wants to be sure only one verified person enters at a time. Which control fits?',
    'An access control vestibule (mantrap)', ['Bollards', 'A cable lock', 'Motion-activated lighting'],
    'Two interlocking doors let a guard or reader verify a person before the second door opens, which also stops tailgating.', 'a2-d2-phys-vestibule'),
  s.mcq('tailgating', 'An employee holds the door for a stranger carrying boxes. What has just succeeded?',
    'Tailgating', ['Shoulder surfing', 'Vishing', 'Whaling'],
    'Tailgating is following an authorised person through a controlled door. Politely challenging strangers is the defence.', 'a2-d2-tailgate-shoulder'),
  s.mcq('vishing', 'A caller claiming to be from the bank asks for the one-time code just sent to your phone. What is this?',
    'Vishing', ['Smishing', 'Whaling', 'Dumpster diving'],
    'Vishing is phishing by voice call. Smishing is by text message. Never share one-time codes with a caller.', 'a2-d2-social-phishing'),
  s.mcq('whaling', 'A convincing phishing email is written specifically for the company’s CFO. What is this called?',
    'Whaling', ['Smishing', 'Tailgating', 'An evil twin'],
    'Whaling is spear phishing aimed at senior executives, who have the most access and authority.', 'a2-d2-social-phishing'),
  s.mcq('evil-twin', 'At an airport, several travellers join “Airport_Free_WiFi” and then see certificate warnings. Which attack is most likely?',
    'An evil twin access point', ['Brute force', 'A zero-day exploit', 'SQL injection'],
    'A rogue access point copying a legitimate network name lets an attacker sit in the middle. The certificate warnings are the tell.', 'a2-d2-attack-evil-twin'),
  s.mcq('ddos', 'A website is flooded with traffic from thousands of infected devices. What is this?',
    'A DDoS attack', ['An on-path attack', 'Cross-site scripting', 'A zero-day exploit'],
    'A distributed denial of service uses many machines (often a botnet), so blocking one source does not help.', 'a2-d2-attack-dos'),
  s.mcq('sqli', 'An attacker types \' OR 1=1 -- into a login form and gets in. Which attack is this?',
    'SQL injection', ['Cross-site scripting', 'Brute force', 'A rootkit'],
    'The input changes the database query itself. Input validation and parameterised queries prevent it.', 'a2-d2-attack-sqli-xss'),
  s.mcq('spraying', 'An attacker tries the password “Summer2026!” against every account in the company. What is this?',
    'Password spraying', ['Brute force', 'An on-path attack', 'An evil twin'],
    'Spraying tries a few common passwords across many accounts to stay under lockout limits. Brute force tries many passwords on one account.', 'a2-d2-attack-passwords'),
  s.mcq('ransomware', 'Files on a shared drive are renamed and unreadable, and a note demands payment. What is the best recovery plan?',
    'Isolate the infected systems and restore from clean, offline backups', ['Pay the ransom', 'Reboot the file server and carry on', 'Delete the note and keep working'],
    'Isolating stops the spread, and tested offline backups mean you do not need the attacker’s key.', 'a2-d2-malware-ransomware'),
  s.mcq('trojan', 'A user installs a free “PDF converter” that also opens a backdoor. What kind of malware is it?',
    'A Trojan', ['A worm', 'Ransomware', 'A rootkit'],
    'A Trojan pretends to be useful software and relies on the user to run it. A worm spreads on its own.', 'a2-d2-malware-worm-trojan'),
  s.mcq('wpa3', 'Which Wi-Fi security setting should a small office choose if every device supports it?',
    'WPA3', ['WEP', 'WPA with TKIP', 'An open network with MAC filtering'],
    'WPA3 is the strongest current option. WEP and TKIP are outdated, and MAC filtering is not encryption.', 'a2-d2-wifi-security'),
  s.mcq('radius', 'A company wants central authentication for its Wi-Fi, so disabling one account blocks access everywhere. Which service fits?',
    'RADIUS', ['DHCP', 'SMTP', 'TFTP'],
    'RADIUS provides central authentication, authorisation and accounting for network access. DHCP hands out addresses and SMTP moves mail.', 'a2-d2-aaa-protocols'),
  s.multi('mfa-pairs', 'Which TWO combinations count as multifactor authentication?',
    ['A password and a code from an authenticator app', 'A smart card and a PIN'], ['A password and a security question', 'Two different passwords', 'A PIN and a passphrase'],
    'MFA needs two different factor types: know, have or are. A password plus a security question is two things you know.', 'a2-d2-mfa-factors'),
  s.mcq('least-privilege', 'A new accountant needs only the finance share. What is the best access?',
    'Access to only the finance share', ['Membership of Domain Admins', 'The same access as their manager', 'Access to the whole file server'],
    'Least privilege gives only what the job needs, which limits the damage from mistakes or a stolen account.', 'a2-d2-least-privilege'),
  s.mcq('ntfs-share', 'A user has Full Control at the share level but Read at the NTFS level. What access do they have over the network?',
    'Read', ['Full control', 'Modify', 'No access'],
    'The most restrictive of the share and NTFS permissions applies.', 'a2-d2-ntfs-share-perms'),
  s.mcq('bitlocker', 'A company laptop is stolen. Which control stops the thief reading its drive?',
    'BitLocker full-disk encryption', ['Windows Defender Firewall', 'A screen saver password', 'UAC'],
    'Encrypting the whole volume keeps the data unreadable even if the drive is moved to another PC.', 'a2-d2-bitlocker'),
  s.mcq('ssd-degauss', 'A company retires SSDs that held customer data. Which method is NOT effective on them?',
    'Degaussing', ['Crypto erase', 'Shredding', 'Incineration'],
    'Degaussing scrambles magnetic fields, and flash memory has none. Crypto erase and physical destruction work.', 'a2-d2-data-destruction'),
  s.mcq('quick-format', 'An old hard drive will be donated. Which action best prevents its data from being recovered?',
    'Overwriting the whole drive with a secure-wipe tool', ['A quick format', 'Deleting the folders and emptying the Recycle Bin', 'Reinstalling the operating system'],
    'A quick format only clears the file table. Deleting files just removes the pointers.', 'a2-d2-quick-format'),
  s.order('malware-steps', 'Put the malware removal steps in order.',
    ['Investigate and verify the symptoms', 'Quarantine the infected system', 'Disable System Restore', 'Remediate: update anti-malware and scan', 'Schedule scans and run updates',
     'Enable System Restore and create a restore point', 'Educate the end user'],
    'Isolate before you clean, and switch System Restore off so malware is not preserved in old restore points.', 'a2-d2-malware-removal-steps'),
  s.match('malware-types', 'Match each type of malware with its behaviour.',
    [['Worm', 'Spreads across a network by itself'], ['Trojan', 'Disguised as legitimate software'], ['Ransomware', 'Encrypts files and demands payment'],
     ['Keylogger', 'Records keystrokes to steal credentials'], ['Rootkit', 'Hides deep in the operating system']],
    'Knowing how each one behaves tells you how to contain it.', 'a2-d2-malware-worm-trojan'),
  s.mcq('router-first', 'What is the FIRST thing to change on a newly installed home router?',
    'The default administrator password', ['The DHCP lease time', 'The channel width', 'The MTU'],
    'Default credentials are public. Changing them (and updating the firmware) closes the easiest way in.', 'a2-d2-soho-hardening'),
  s.mcq('lost-phone', 'An executive reports a lost phone that holds company email. What should IT do first?',
    'Remotely lock or wipe it through MDM', ['Wait a week in case it is found', 'Ask the executive to be more careful', 'Reset only the executive’s email password'],
    'Remote lock or wipe protects the data immediately, and the account credentials can be reset alongside.', 'a2-d2-mobile-security'),
  s.mcq('pci', 'Which standard governs how payment card data must be handled?',
    'PCI DSS', ['HIPAA', 'GDPR', 'SOX'],
    'PCI DSS covers cardholder data. HIPAA covers US health data and GDPR covers personal data of people in the EU.', 'a2-d2-compliance-data'),
];

const w = questionBuilders('a2-d3');
const SOFTWARE: Question[] = [
  w.mcq('bsod-driver', 'A PC blue-screens on every boot after a new graphics driver was installed. What is the best first fix?',
    'Boot to Safe Mode and roll back the driver', ['Reformat the drive', 'Replace the RAM', 'Reset the BIOS clock'],
    'The change that preceded the failure is the prime suspect, and Safe Mode loads basic drivers so you can undo it.', 'a2-d3-bsod-driver'),
  w.mcq('boot-device', 'After a drive swap, a PC shows “Boot device not found” but firmware detects the drive. What should you check?',
    'The boot order and boot mode, then repair the boot records', ['The power supply', 'The keyboard driver', 'The DNS cache'],
    'A detected drive with no boot device suggests the wrong boot order or mode, or damaged boot records.', 'a2-d3-no-os'),
  w.mcq('bootrec', 'In WinRE’s command prompt, which command rebuilds the boot configuration data?',
    'bootrec /rebuildbcd', ['sfc /rebuildbcd', 'chkdsk /bcd', 'diskpart /rebuild'],
    'bootrec has /fixmbr, /fixboot and /rebuildbcd. sfc and chkdsk work on system files and file systems.', 'a2-d3-bootrec'),
  w.mcq('safe-mode', 'A problem disappears when the PC runs in Safe Mode. What does that suggest?',
    'A driver, service or startup program is the cause', ['The motherboard is failing', 'The disk is full of bad sectors', 'The BIOS is corrupt'],
    'Safe Mode loads only basic drivers and services, so a problem that vanishes points at something normally loaded.', 'a2-d3-safe-mode'),
  w.mcq('startup-tab', 'A PC is slow only for the first five minutes after sign-in. Which tool shows what launches at sign-in?',
    'The Startup tab in Task Manager', ['Device Manager', 'Disk Management', 'Windows Firewall'],
    'Startup apps compete for the CPU and disk right after logon. Disabling ones you do not need shortens the wait.', 'a2-d3-slow-taskmgr'),
  w.mcq('clock-certs', 'Every HTTPS site shows a certificate warning on one PC, and its clock is two years behind. What is the likely cause?',
    'A dead CMOS battery or a failed time sync', ['A failing hard drive', 'A virus in the browser only', 'A DNS outage'],
    'A wrong date makes valid certificates look expired. Fix the clock source, not the sites.', 'a2-d3-time-drift'),
  w.mcq('slow-profile', 'One user’s sign-in takes ten minutes while others are fine on the same PC. What should you try?',
    'Create a new user profile and compare', ['Replace the router', 'Reinstall Windows', 'Update the BIOS'],
    'If a new profile is fast, the old profile is corrupt or bloated. Nothing about the hardware is at fault.', 'a2-d3-slow-profile'),
  w.mcq('update-space', 'Windows Update fails repeatedly with a “not enough space” message on a 64 GB drive. What is the first step?',
    'Free disk space with Disk Cleanup and by removing old files', ['Disable the firewall', 'Change the DNS server', 'Reset the router'],
    'The error names the cause. Updates need working space to unpack.', 'a2-d3-update-fails'),
  w.mcq('dism', 'sfc /scannow says it could not repair some files. What is next?',
    'Run DISM to repair the component store, then run sfc again', ['Run defrag', 'Format the drive', 'Disable UAC'],
    'sfc takes its good copies from the component store. DISM repairs that store first.', 'a2-d3-dism'),
  w.mcq('malware-signs', 'A PC shows constant pop-ups, a changed homepage and a disabled antivirus. What is the best conclusion?',
    'It is probably infected with malware, so start the removal process', ['The monitor is failing', 'The DHCP lease expired', 'The RAM is bad'],
    'These symptoms together are typical of malware. Investigate and quarantine before you clean.', 'a2-d3-malware-symptoms'),
  w.mcq('rogue-av', 'A pop-up claims “Your PC is infected: call now and buy this cleaner.” What is it?',
    'Rogue antivirus (scareware)', ['A Windows Update prompt', 'A UAC prompt', 'A BIOS alert'],
    'Real security tools do not demand payment from a browser pop-up. Close it from Task Manager and run a genuine scan.', 'a2-d3-rogue-av'),
  w.mcq('phone-app-drain', 'A phone’s battery drops 30% an hour and it runs hot. Battery usage shows an unfamiliar app at the top. What next?',
    'Force stop and uninstall the app, then scan the device', ['Raise the screen brightness', 'Factory reset without a backup', 'Ignore it'],
    'The usage list names the culprit. Remove it and check for anything else unwanted before considering a reset.', 'a2-d3-mobile-battery'),
  w.mcq('app-crash-launch', 'An app crashes on launch. What is the least disruptive first fix?',
    'Force stop it and clear its cache', ['Factory reset the phone', 'Replace the battery', 'Root the device'],
    'Start with the gentlest fix that keeps the user’s data.', 'a2-d3-mobile-app-crash'),
  w.mcq('data-spike', 'A phone’s cellular data use tripled with no change in habits. What is the most likely cause?',
    'A background app or automatic cloud upload using cellular data', ['A dead battery', 'A cracked screen', 'An old wallpaper'],
    'Check per-app data usage and restrict background data or remove the app.', 'a2-d3-mobile-data-spike'),
  w.mcq('forget-network', 'A phone will not join a known Wi-Fi network that works for everyone else. What is a quick first step?',
    'Forget the network and join it again', ['Factory reset', 'Replace the SIM', 'Change the router'],
    'A saved profile can be stale or corrupt. Rejoining re-enters the settings and is harmless.', 'a2-d3-mobile-connectivity'),
  w.mcq('sideload', 'A user installs a game APK from a random website. What is the main risk?',
    'It skipped store vetting and may contain malware', ['It voids the SIM contract', 'It uses more storage', 'It disables Wi-Fi'],
    'Official stores review and scan apps. A file from the web has had none of that.', 'a2-d3-sideloading'),
  w.order('wont-boot', 'A PC will not start after an update. Put these steps in order, least to most disruptive.',
    ['Confirm firmware detects the drive and the boot order is right', 'Boot into the Windows Recovery Environment', 'Run Startup Repair',
     'Use the recovery command prompt (bootrec, sfc, chkdsk)', 'Reset or reimage the PC if repairs fail'],
    'Cheap checks come first and a reset last, because it costs the user their setup.', 'a2-d3-winre'),
  w.match('fix-tools', 'Match each command with what it repairs or checks.',
    [['sfc', 'Repairs protected system files'], ['chkdsk', 'Checks the file system and bad sectors'], ['DISM', 'Repairs the Windows component store'], ['bootrec', 'Repairs boot records from WinRE']],
    'Each tool works at a different level, so the symptom decides which to start with.', 'a2-d1-cmd-chkdsk'),
  w.multi('browser-hijack', 'Which TWO are common signs of a hijacked browser?',
    ['Search results redirect to unfamiliar sites', 'New toolbars or extensions you did not install'], ['Low screen brightness', 'A flickering keyboard backlight', 'The fan spins at boot'],
    'Redirects and unknown extensions point at a browser hijack. Reset the browser and scan for malware.', 'a2-d3-browser-redirect'),
];

const p = questionBuilders('a2-d4');
const OPERATIONS: Question[] = [
  p.mcq('backup-321', 'Which arrangement follows the 3-2-1 backup rule?',
    'Three copies, on two media types, with one stored off-site', ['Three copies on the same disk', 'Two copies on one medium with none off-site', 'One cloud copy and nothing else'],
    'Different media and a different location protect you from one failure or disaster taking everything.', 'a2-d4-backup-321'),
  p.mcq('incremental-restore', 'A full backup runs Sunday and incrementals run Monday to Wednesday. The disk dies Thursday morning. What do you restore?',
    'Sunday’s full backup plus the Monday, Tuesday and Wednesday incrementals', ['Only Wednesday’s incremental', 'Only Sunday’s full backup', 'Wednesday’s and Monday’s incrementals'],
    'Each incremental holds only that day’s changes, so the whole chain is needed.', 'a2-d4-backup-restore'),
  p.mcq('differential-restore', 'A full backup runs Sunday and differentials run Monday to Wednesday. The disk dies Thursday. What do you restore?',
    'Sunday’s full backup plus Wednesday’s differential', ['Sunday’s full backup plus all three differentials', 'Only Wednesday’s differential', 'Monday’s and Wednesday’s differentials'],
    'A differential holds everything changed since the last full, so only the latest one is needed with the full backup.', 'a2-d4-backup-types'),
  p.mcq('rollback', 'Which part of a change request lets you undo a change that fails?',
    'The rollback (backout) plan', ['The risk analysis', 'The scope statement', 'The approval signature'],
    'A rollback plan says how to return to the previous working state, and it is tested before the change.', 'a2-d4-change-testing'),
  p.mcq('esd-strap', 'While installing RAM, how do you best protect it from electrostatic discharge?',
    'Wear a wrist strap clipped to bare metal on the case', ['Work barefoot on carpet', 'Hold the module by its gold contacts', 'Blow on the module to remove dust'],
    'The strap keeps you and the part at the same potential. Touching contacts and working on carpet make static worse.', 'a2-d4-esd'),
  p.mcq('fire-class', 'A server rack catches fire. Which extinguisher is appropriate?',
    'Class C (CO2 or a clean agent)', ['A water extinguisher', 'A Class A water-based extinguisher', 'A bucket of sand'],
    'Class C is for electrical fires. Water can conduct electricity and spread the fire.', 'a2-d4-fire-class-c'),
  p.mcq('sds', 'You must clean up a spilled toner cartridge. Which document explains its hazards and handling?',
    'The Safety Data Sheet (SDS)', ['The SLA', 'The AUP', 'The network diagram'],
    'An SDS lists a product’s hazards, first aid and disposal.', 'a2-d4-sds'),
  p.mcq('ups', 'A server must keep running for ten minutes through a power cut so it can shut down cleanly. Which device?',
    'A UPS', ['A surge protector', 'A power strip', 'A voltage regulator alone'],
    'A UPS has a battery. A surge protector only absorbs spikes and does nothing in a blackout.', 'a2-d4-ups-vs-surge'),
  p.mcq('angry-user', 'A user is shouting that the network is down. What should you do first?',
    'Stay calm, listen, and let them finish before asking questions', ['Tell them to calm down', 'Explain the technical cause in detail', 'Transfer the call immediately'],
    'Being heard lowers the temperature. Then restate the problem and explain the next steps.', 'a2-d4-angry-customer'),
  p.mcq('hr-data', 'While fixing a laptop you see an open HR spreadsheet with salaries. What is appropriate?',
    'Avoid reading it, do only what the task needs and keep it confidential', ['Copy it in case it is needed', 'Mention the numbers to colleagues', 'Email it to yourself for reference'],
    'Access to the machine is not permission to use what is on it.', 'a2-d4-confidentiality'),
  p.mcq('escalate-notes', 'Which detail helps the next technician most when you escalate a ticket?',
    'The steps already tried and their results', ['Only the ticket number', 'A guess at who is to blame', 'A shorter description than the original'],
    'Escalation notes stop the next tier repeating your work.', 'a2-d4-escalation'),
  p.mcq('ps1', 'Which file extension is a PowerShell script?',
    '.ps1', ['.bat', '.sh', '.py'],
    '.bat is batch, .sh is shell (Linux or macOS) and .py is Python.', 'a2-d4-script-types'),
  p.mcq('ai-data', 'A colleague pastes a customer’s account details into a public AI chatbot to draft a reply. What is the main concern?',
    'Private data may be disclosed or retained by the tool', ['The chatbot will overheat', 'The reply will be too short', 'It voids the software licence'],
    'Follow company policy on what may be shared, and verify AI output before using it.', 'a2-d4-ai-limits'),
  p.mcq('custody', 'After a security incident you hand a laptop to investigators. Which documentation shows it was not tampered with?',
    'Chain of custody', ['The asset tag', 'The SLA', 'The AUP'],
    'Chain of custody records who handled the evidence and when.', 'a2-d4-chain-of-custody'),
  p.multi('safe-pc', 'Which TWO are safe practices before opening a desktop PC?',
    ['Power it off and unplug it', 'Use an ESD strap or mat'], ['Open the power supply to check its capacitors', 'Keep a drink close by', 'Wear a metal bracelet'],
    'Remove power and control static. A power supply can hold a dangerous charge and is not a field-serviceable part.', 'a2-d4-electrical-safety'),
  p.match('ops-terms', 'Match each term with its meaning.',
    [['SLA', 'Promised response and resolution times'], ['SOP', 'Written steps for a routine task'], ['AUP', 'Rules for using company systems'], ['SDS', 'Hazard and handling information for a product']],
    'Each document does a different job: expectations, consistency, behaviour and safety.', 'a2-d4-sla'),
  p.mcq('battery-disposal', 'Where should a swollen lithium battery go?',
    'An approved recycler or hazardous-waste program', ['The office trash', 'The shredder', 'A drawer until it deflates'],
    'Damaged lithium batteries can ignite. Follow local disposal rules.', 'a2-d4-disposal'),
  p.mcq('remote-secure', 'A technician needs secure remote access to a user’s PC from home. What is the best practice?',
    'Connect through a VPN with MFA and a least-privilege account', ['Open port 3389 to the internet', 'Share the admin password over chat', 'Turn the firewall off for the session'],
    'Exposed remote access is a top attack path, so protect it with a VPN, MFA and limited rights.', 'a2-d4-remote-access'),
];

export const A2_QUESTIONS: Question[] = [...OS, ...SECURITY, ...SOFTWARE, ...OPERATIONS];
export default A2_QUESTIONS;
