import type { Card } from './types';

/**
 * A+ Core 2 (220-1202). Topics follow the official objectives as an outline;
 * every word here is original. Verify against CompTIA's objectives PDF before
 * relying on coverage.
 */
const card = (domain: string, slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'objective-outline',
});

const os = 'a2-d1';
export const OS_CARDS: Card[] = [
  card(os, 'editions-domain', 'Which Windows editions can join an Active Directory domain, and which cannot?',
    'Pro, Enterprise and Education can join a domain. Home cannot.',
    'Domain join, Group Policy management, BitLocker and hosting Remote Desktop are business features, so Microsoft leaves them out of Home.',
    'Think about which edition a small business buys instead of the consumer one.'),
  card(os, 'win11-requirements', 'Beyond a 64-bit CPU, what are the key hardware requirements for Windows 11?',
    'TPM 2.0, UEFI with Secure Boot, at least 4 GB of RAM and 64 GB of storage.',
    'Windows 11’s security features lean on the TPM and Secure Boot, which is why some older PCs that run Windows 10 fail the compatibility check.',
    'Two of the requirements are security features built into the motherboard.'),
  card(os, 'inplace-vs-clean', 'What is the difference between an in-place upgrade and a clean install?',
    'An in-place upgrade keeps files, apps and settings. A clean install wipes the drive and starts fresh.',
    'Upgrade for convenience; clean install to shed accumulated problems or repurpose a machine. Back up first either way.',
    'One keeps your things, the other erases them.'),
  card(os, 'install-sources', 'Name common ways to start a Windows installation.',
    'A USB drive, an optical disc, PXE network boot, or an image on a recovery partition.',
    'PXE lets a technician deploy many machines from a server without media, USB is the everyday choice, and a recovery partition restores the maker’s image.',
    'One of them needs no media at all, only the network.'),
  card(os, 'gpt-vs-mbr', 'What are the main limits of MBR compared with GPT?',
    'MBR handles disks up to 2 TB and four primary partitions. GPT handles far larger disks and up to 128 partitions, and it is the normal style for UEFI boot.',
    'Modern PCs use UEFI with GPT. MBR lives on older BIOS machines and small removable drives.',
    'One of them stops at a size measured in terabytes.'),
  card(os, 'exfat-usb', 'Which file system suits a USB stick shared between Windows and Mac that holds files over 4 GB?',
    'exFAT. FAT32 cannot store a file larger than 4 GB.',
    'exFAT is the flash-drive file system with no practical file size limit and read/write support on both systems. NTFS is Windows-native and Macs read it but do not write to it by default.',
    'It is FAT’s newer cousin, built for flash drives.'),
  card(os, 'ntfs-features', 'What does NTFS offer that FAT32 does not?',
    'File and folder permissions, encryption (EFS), compression, journaling, and very large files and volumes.',
    'Permissions and journaling are why Windows itself lives on NTFS: it can secure files and recover from a crash mid-write.',
    'Think security and reliability features.'),
  card(os, 'cmd-ipconfig', 'Which command shows a Windows PC’s full network configuration, including MAC address and DNS servers?',
    'ipconfig /all',
    'Plain ipconfig shows the basics. /all adds the MAC, DHCP server, lease times and DNS servers. /release and /renew refresh a DHCP lease, and /flushdns clears the DNS cache.',
    'Add a switch that means everything.'),
  card(os, 'cmd-tracert', 'Which command shows each router hop between your PC and a destination?',
    'tracert on Windows (traceroute on Linux and macOS).',
    'It shows where delay or loss begins along the path. pathping adds statistics over time.',
    'Its name says it traces a route.'),
  card(os, 'cmd-nslookup', 'Which command queries a DNS server directly to test name resolution?',
    'nslookup (dig on Linux and macOS).',
    'It shows which server answered and which records came back, which separates a DNS problem from a connectivity problem.',
    'Its name blends name server and look up.'),
  card(os, 'cmd-netstat', 'How do you list active connections and listening ports on a Windows PC?',
    'netstat, for example netstat -an, or -b to show the program (from an elevated prompt).',
    'It is a quick way to spot unexpected outbound connections that might point to malware.',
    'Network plus statistics.'),
  card(os, 'cmd-sfc', 'Which command scans and repairs protected Windows system files?',
    'sfc /scannow, from an elevated prompt. If it cannot repair them, run DISM first.',
    'System File Checker compares protected files against known-good copies and replaces damaged ones.',
    'The first two letters stand for system file.'),
  card(os, 'cmd-chkdsk', 'What does chkdsk /f /r do?',
    'It checks a drive’s file system, fixes errors (/f), and finds bad sectors and recovers readable data (/r).',
    'On the system drive it usually schedules the check for the next restart, and /r can take hours on a large disk.',
    'Two switches: one repairs, one recovers.'),
  card(os, 'cmd-gpupdate', 'How do you apply Group Policy changes to a PC right now, and confirm what applied?',
    'gpupdate /force to refresh, and gpresult /r to see which policies applied.',
    'Policy normally refreshes on a timer. Forcing it makes a fix visible immediately, and gpresult shows whether the policy really reached the machine.',
    'One command updates policy, the other reports the result.'),
  card(os, 'cmd-diskpart', 'Which command-line tool creates, deletes and formats partitions and can convert MBR to GPT?',
    'diskpart',
    'It works in WinRE where no graphical tools exist. Its clean command erases the partition table, so make sure the right disk is selected first.',
    'Its name is disk plus part.'),
  card(os, 'cmd-robocopy', 'Which command copies large folder trees robustly, retrying on failure and able to mirror?',
    'robocopy, for example robocopy source dest /mir.',
    'Unlike copy, it retries on errors and can preserve permissions. /mir mirrors the source, deletions included, so double-check the direction.',
    'It is robust copy.'),
  card(os, 'cmd-net-use', 'How do you map a network share to a drive letter from the command line?',
    'net use Z: \\\\server\\share',
    'The drive letter then appears in File Explorer. Add /persistent:yes to keep it after a restart.',
    'It starts with net, and the verb is to use.'),
  card(os, 'linux-navigation', 'Which Linux commands list files, print the current directory and change directory?',
    'ls, pwd and cd.',
    'ls -l adds permissions and sizes, and ls -a shows hidden files. Paths starting with / are absolute.',
    'Each is two or three letters.'),
  card(os, 'linux-chmod', 'What does chmod 755 script.sh do?',
    'It gives the owner read, write and execute, and everyone else read and execute.',
    'Each digit adds read 4, write 2 and execute 1, so 7 is 4+2+1 and 5 is 4+1. chown changes who owns the file rather than what they can do.',
    'Add up 4, 2 and 1 for each digit.'),
  card(os, 'linux-grep-find', 'Which Linux command searches inside files for text, and which searches for files by name?',
    'grep searches file contents. find searches the file tree by name and other attributes.',
    'They are often combined: find locates the files and grep looks inside them.',
    'One reads the contents, the other walks the folders.'),
  card(os, 'linux-ps-kill', 'How do you see running processes on Linux and stop a stuck one?',
    'ps or top to list them, then kill followed by the process ID (kill -9 to force it).',
    'kill sends a signal asking the process to end. -9 (SIGKILL) cannot be ignored but gives the program no chance to clean up.',
    'Find the process’s number first.'),
  card(os, 'linux-sudo-apt', 'What are sudo and apt (or dnf) for on Linux?',
    'sudo runs one command with administrator (root) rights. apt or dnf install and update software from repositories.',
    'Working as a normal user and using sudo only when needed is safer than staying logged in as root.',
    'One raises your rights, the other installs software.'),
  card(os, 'linux-df-du', 'Which Linux commands show free disk space and how much space a folder uses?',
    'df shows free space per file system. du shows the space used by files and folders.',
    'df -h and du -sh print sizes in human-readable units.',
    'Disk free, and disk usage.'),
  card(os, 'mac-features', 'Name the macOS features for backups, system-wide search, multiple desktops and password storage.',
    'Time Machine, Spotlight, Mission Control and Keychain.',
    'Time Machine backs up to an external or network drive, Spotlight also launches apps, and Keychain stores passwords and certificates.',
    'Four features, four different names.'),
  card(os, 'mac-security', 'What do FileVault and Gatekeeper do on macOS?',
    'FileVault encrypts the startup disk. Gatekeeper limits which apps can run, based on signing and where they came from.',
    'One protects data if the Mac is lost, the other helps stop unvetted software being run.',
    'One protects data at rest, the other vets apps.'),
  card(os, 'tool-taskmgr', 'Which Windows tool shows processes, performance graphs, startup apps and services in one place?',
    'Task Manager (Ctrl+Shift+Esc).',
    'The Startup tab controls which programs launch at sign-in, and the Details tab shows process IDs.',
    'The shortcut is Ctrl, Shift, then Esc.'),
  card(os, 'tool-eventviewer', 'Where do you read Windows application, security and system logs?',
    'Event Viewer (eventvwr.msc).',
    'Errors and warnings there often name the failing service, driver or app, which turns a vague symptom into something you can search for.',
    'It views what happens on the system.'),
  card(os, 'tool-devmgr-diskmgmt', 'Which tools manage hardware and drivers, and drives and partitions?',
    'Device Manager for hardware and drivers. Disk Management for drives and partitions.',
    'A yellow warning icon in Device Manager means a driver problem. Disk Management is where you initialize, format and assign letters to new drives.',
    'One is about devices, the other about disks.'),
  card(os, 'tool-services-msconfig', 'Which tools control background services, and startup and boot options?',
    'services.msc for services. msconfig (System Configuration) for startup and boot options such as Safe Boot.',
    'Use msconfig to boot to Safe Mode next time, and services.msc to restart or disable a service.',
    'One ends in msc and lists services.'),
  card(os, 'tool-perfmon-resmon', 'Which tools show live per-process CPU, memory, disk and network use, and log counters over time?',
    'Resource Monitor for live per-process detail. Performance Monitor (perfmon) to graph and log counters over time.',
    'Resource Monitor finds what is busy right now. Performance Monitor answers what happened overnight.',
    'One is live, the other is a recorder.'),
  card(os, 'tool-regedit', 'What is the Registry Editor for, and what should you do before changing it?',
    'regedit edits the Windows configuration database. Back up (export) the keys first.',
    'A wrong edit can stop Windows booting. An exported .reg file lets you undo it.',
    'One careful step before you edit.'),
  card(os, 'tool-gpedit-lusrmgr', 'Which consoles manage local policy and local user accounts?',
    'gpedit.msc for Local Group Policy (Pro and above) and lusrmgr.msc for local users and groups (not on Home).',
    'On Home you use Settings and the registry instead.',
    'Both end in .msc.'),
  card(os, 'tool-system-restore', 'What are a restore point and System Restore?',
    'A restore point is a snapshot of system files and settings. System Restore rolls them back without touching personal files.',
    'It undoes a bad driver or update without a reinstall, but it does not replace a backup.',
    'It restores the system to an earlier moment.'),
  card(os, 'net-profiles', 'What is the difference between Public and Private network profiles in Windows?',
    'Private trusts the network, so discovery and sharing can be allowed. Public locks them down for places like cafés.',
    'Choosing Public on a home network is why file sharing sometimes seems broken; choosing Private on hotel Wi-Fi exposes the PC.',
    'One assumes you know the people on the network.'),
  card(os, 'net-workgroup-domain', 'How do a workgroup and a domain differ?',
    'A workgroup is peer to peer with accounts kept on each PC. A domain uses central accounts and policy from Active Directory.',
    'Domains scale: one sign-in and one set of policies for hundreds of PCs.',
    'One has a central authority, the other does not.'),
  card(os, 'net-rdp', 'Which port does Remote Desktop use, and which Windows editions can host it?',
    'TCP 3389. Pro, Enterprise and Education can host it; Home can only connect out.',
    'Never expose 3389 straight to the internet. Use a VPN or a gateway with MFA.',
    'Four digits, starting with 33.'),
  card(os, 'app-install', 'Before installing a business application, what should you check?',
    'System requirements (OS version, 32- or 64-bit, RAM, disk), compatibility, licensing, and the impact on other devices, the network and the business.',
    'A quick check prevents installs that fail, slow the PC or break another business tool.',
    'Will it fit the machine, and what else will it disturb?'),
  card(os, 'win-updates', 'What is the difference between Windows quality updates and feature updates?',
    'Quality updates fix bugs and security holes and arrive monthly. Feature updates add new functionality and arrive less often.',
    'Test feature updates on a few machines first, since they change more.',
    'One repairs, the other adds.'),
];

const sec = 'a2-d2';
export const SECURITY_CARDS: Card[] = [
  card(sec, 'phys-vestibule', 'What is an access control vestibule (mantrap)?',
    'A small space with two interlocking doors, so only one person passes at a time and can be verified before the second door opens.',
    'It defeats tailgating: nobody can slip in behind an authorised person.',
    'Two doors that never open together.'),
  card(sec, 'phys-controls', 'Name four physical security controls.',
    'Badge readers, biometrics, security guards and cameras. Also locks, fences, bollards, lighting and cable locks.',
    'Layered controls mean defeating one does not open the door: prevent, detect and deter.',
    'Some check who you are, others record you.'),
  card(sec, 'tailgate-shoulder', 'What is the difference between tailgating and shoulder surfing?',
    'Tailgating is following an authorised person through a door. Shoulder surfing is watching someone type a password or read a screen.',
    'Badges alone do not stop tailgating; a vestibule or a policy of challenging strangers does. Privacy screens stop shoulder surfing.',
    'One is about doors, the other about screens.'),
  card(sec, 'social-phishing', 'What are phishing, vishing and smishing, and who do spear phishing and whaling target?',
    'Phishing is by email, vishing by voice call, smishing by text message. Spear phishing targets a person or group, and whaling targets executives.',
    'Each pretends to be someone trusted to get a click, a password or a payment. Slow down and verify through another channel.',
    'The names hint at the channel: mail, voice, SMS.'),
  card(sec, 'social-dumpster', 'What is dumpster diving, and how do you defend against it?',
    'Searching trash for sensitive information. Defend by shredding paper and destroying media before disposal.',
    'Discarded printouts, sticky notes and old drives are often easier to steal than data on a network.',
    'The attacker goes through what you throw away.'),
  card(sec, 'attack-evil-twin', 'What is an evil twin?',
    'A rogue access point that copies a real network’s name to trick users into connecting, so their traffic can be captured.',
    'Check the network name with staff, avoid open Wi-Fi for sensitive work, and use a VPN.',
    'A fake copy of a real Wi-Fi network.'),
  card(sec, 'attack-dos', 'How does a DoS attack differ from a DDoS?',
    'A DoS floods a target from one source. A DDoS uses many machines, often a botnet, so it is far harder to block.',
    'Blocking one address stops a DoS but not thousands of infected devices sending at once.',
    'The extra D means distributed.'),
  card(sec, 'attack-on-path', 'What is an on-path (man-in-the-middle) attack?',
    'The attacker secretly sits between two parties, reading or altering the traffic.',
    'Encryption with certificate validation (HTTPS, VPN) defends against it, and a certificate warning is a red flag.',
    'A third party quietly inserts itself between two others.'),
  card(sec, 'attack-passwords', 'How do brute force, dictionary and password spraying attacks differ?',
    'Brute force tries every combination. A dictionary attack tries likely words. Spraying tries a few common passwords across many accounts to avoid lockouts.',
    'Long unique passwords, MFA and lockout policies each defeat a different one.',
    'One is exhaustive, one uses a word list, one spreads its guesses.'),
  card(sec, 'attack-sqli-xss', 'What are SQL injection and cross-site scripting (XSS)?',
    'SQL injection slips database commands in through a web form. XSS injects a script that runs in other visitors’ browsers.',
    'Both come from trusting user input. Input validation and parameterised queries prevent them.',
    'Both smuggle code in through input fields.'),
  card(sec, 'attack-zero-day', 'What is a zero-day attack?',
    'An attack on a vulnerability the vendor does not yet know about, so no patch exists.',
    'Defence relies on layers: least privilege, network segmentation, monitoring and fast patching once a fix arrives.',
    'The vendor has had zero days to fix it.'),
  card(sec, 'malware-ransomware', 'Which malware encrypts your files and demands payment, and what is the best defence?',
    'Ransomware. Offline or immutable backups that you have tested, plus patching and user training.',
    'If you can restore from a backup that the attacker could not reach, there is nothing to pay for.',
    'It holds your data hostage.'),
  card(sec, 'malware-worm-trojan', 'How does a worm differ from a Trojan?',
    'A worm spreads by itself across networks. A Trojan pretends to be useful software and needs the user to run it.',
    'Worms are a patching problem; Trojans are a user-behaviour problem.',
    'One needs your help to get in, the other does not.'),
  card(sec, 'malware-rootkit-keylogger', 'What are a rootkit and a keylogger?',
    'A rootkit hides malware deep in the operating system, even from the OS. A keylogger records what you type to steal credentials.',
    'Rootkits often need a rebuild or an offline scan to remove. Keyloggers are why MFA matters.',
    'One conceals, the other records.'),
  card(sec, 'malware-cryptojack', 'What does cryptojacking look like on a PC?',
    'High CPU or GPU use, heat, fan noise and slowness with no visible cause, because malware is mining cryptocurrency.',
    'The attacker gets the coins and you pay for the power and wear.',
    'A busy machine with nothing running that you started.'),
  card(sec, 'malware-removal-steps', 'What are the steps for removing malware, in order?',
    '1 Investigate and verify symptoms. 2 Quarantine the system. 3 Disable System Restore. 4 Remediate: update anti-malware, scan and remove, use Safe Mode or a pre-install environment. 5 Schedule scans and run updates. 6 Enable System Restore and create a restore point. 7 Educate the end user.',
    'Isolate first so it cannot spread, and turn System Restore off so the malware is not saved into old restore points.',
    'Cut it off from the network before you clean it.'),
  card(sec, 'wifi-security', 'Which Wi-Fi security is strongest today, and which are outdated?',
    'WPA3 is strongest. WPA2 with AES is still acceptable. WEP and WPA with TKIP are outdated.',
    'WEP can be broken in minutes. WPA3 replaces the pre-shared key handshake with SAE, which resists offline guessing.',
    'Higher number, newer protocol.'),
  card(sec, 'aaa-protocols', 'What do RADIUS, TACACS+ and Kerberos each do?',
    'RADIUS and TACACS+ provide central authentication, authorisation and accounting: RADIUS commonly for Wi-Fi and VPN, TACACS+ for device administration. Kerberos is the ticket-based authentication Active Directory uses.',
    'Central AAA means one place to grant and revoke access instead of accounts on every device.',
    'Two are about central access control, one about tickets.'),
  card(sec, 'mfa-factors', 'What are the authentication factors, and what makes MFA?',
    'Something you know, something you have and something you are. MFA combines at least two different kinds.',
    'A password plus a security question is two things you know, so it is not MFA. A password plus a code from an app is.',
    'Knowledge, possession and inherence.'),
  card(sec, 'least-privilege', 'What is the principle of least privilege?',
    'Give users and services only the access they need to do their job, and no more.',
    'It limits the damage from a mistake, a stolen account or malware running as that user.',
    'Only what the job needs.'),
  card(sec, 'ntfs-share-perms', 'When NTFS and share permissions both apply, which access wins?',
    'The most restrictive of the two.',
    'A user reaching a folder over the network passes both checks, so a permissive share does not override a tight NTFS setting.',
    'Both must allow it.'),
  card(sec, 'uac', 'What does User Account Control (UAC) do?',
    'It prompts before actions that need administrator rights, so malware cannot silently change the system.',
    'Standard users are asked for admin credentials, and admins must approve elevation.',
    'The dialog that dims the screen and asks permission.'),
  card(sec, 'bitlocker', 'What is BitLocker, and what usually holds its key?',
    'Full-disk encryption on Pro and above. It seals the key in the TPM and asks for a recovery key if the hardware changes.',
    'A stolen laptop’s data is unreadable without the key. Store the recovery key somewhere safe, such as your directory or a secure vault.',
    'It encrypts the whole drive and leans on a chip on the board.'),
  card(sec, 'efs-vs-bitlocker', 'How does EFS differ from BitLocker?',
    'EFS encrypts individual files and folders for a user. BitLocker encrypts the whole volume.',
    'They can be combined: BitLocker guards the stolen drive, EFS guards files from other users on the same PC.',
    'One works per file, the other per drive.'),
  card(sec, 'defender-firewall', 'What do Windows Defender Antivirus and Windows Defender Firewall each do?',
    'The antivirus scans for and blocks malicious files and behaviour. The firewall filters network traffic by rule.',
    'Different jobs: one looks at what runs, the other at what connects.',
    'One inspects files, the other inspects connections.'),
  card(sec, 'account-hardening', 'Name three ways to harden Windows user accounts.',
    'Disable or rename the built-in Administrator, disable the Guest account, enforce strong passwords with lockout after failed attempts, and set screen-lock timeouts.',
    'Default accounts are the first ones attackers try.',
    'Remove the defaults and limit the guesses.'),
  card(sec, 'data-destruction', 'Which methods destroy data on an old SSD and on an old magnetic hard drive?',
    'SSD: crypto erase or physical shredding (degaussing does nothing). HDD: degauss, shred or overwrite.',
    'Degaussing scrambles magnetic fields, and flash has none. Overwriting an SSD is unreliable because of wear levelling.',
    'One of the methods only works on magnets.'),
  card(sec, 'quick-format', 'Why is a quick format not secure erasure?',
    'It only clears the file table. The data stays on the disk until overwritten, and recovery tools can read it.',
    'For a drive leaving your control, use a wipe or destruction method and keep a certificate of destruction.',
    'It clears the index, not the pages.'),
  card(sec, 'browser-security', 'Name three browser security practices.',
    'Keep the browser updated, use a password manager, limit pop-ups and untrusted extensions, and heed certificate warnings.',
    'Extensions can read everything you browse, so install as few as you can.',
    'Updates, managers and caution with add-ons.'),
  card(sec, 'soho-hardening', 'Name four steps to secure a small office or home router.',
    'Change the default admin password, update the firmware, use WPA3 or WPA2 with a strong passphrase, disable WPS and unneeded services, and use a guest network.',
    'Default credentials and unpatched firmware are how routers are taken over.',
    'Defaults, updates, encryption and separation.'),
  card(sec, 'mobile-security', 'How do you protect data on a lost company phone?',
    'A screen lock with biometrics, device encryption, and remote wipe and locate through MDM or the platform’s find-my service.',
    'Encryption keeps the data unreadable, and remote wipe removes it if the phone is not recovered.',
    'Lock it, encrypt it, and be able to erase it remotely.'),
  card(sec, 'jailbreak-root', 'What are jailbreaking and rooting, and why are they a risk?',
    'Removing the vendor’s restrictions to gain full control. It disables built-in protections, so malware and unvetted apps can run.',
    'MDM tools flag rooted or jailbroken devices as non-compliant.',
    'It breaks out of the vendor’s limits.'),
  card(sec, 'compliance-data', 'What are PII, PHI and PCI DSS?',
    'PII is personally identifiable information. PHI is protected health information (HIPAA in the US). PCI DSS is the standard for handling payment card data.',
    'Handling regulated data brings legal duties: encryption, access limits, retention rules and breach reporting.',
    'Two are kinds of data, one is a standard.'),
  card(sec, 'router-port-forward', 'What does port forwarding do on a router, and what is the risk?',
    'It sends inbound traffic on a chosen port to a specific internal host. It exposes that service to the internet, so forward only what you must.',
    'Every forwarded port is an open door that needs patching and monitoring.',
    'A door from outside to one inside machine.'),
  card(sec, 'mac-filtering', 'Why is MAC filtering weak security?',
    'MAC addresses are sent in the clear and are easy to spoof, so it only slows casual users.',
    'It is not a substitute for strong Wi-Fi encryption.',
    'An address you can copy is not a secret.'),
];

const sw = 'a2-d3';
export const SOFTWARE_CARDS: Card[] = [
  card(sw, 'bsod-driver', 'A Windows PC shows a blue screen after a driver update. What are sensible first steps?',
    'Note the stop code, boot to Safe Mode or WinRE, then roll back the driver or use System Restore.',
    'The stop code and the driver named on the screen narrow the search. Safe Mode loads only basic drivers, so the bad one stays out of the way.',
    'Undo the most recent change, from a mode that works.'),
  card(sw, 'slow-taskmgr', 'A PC is slow. What do you look at first in Task Manager?',
    'Which process is using the most CPU, memory or disk, and what starts at boot.',
    'Sorting by the busy column finds the culprit quickly, and the Startup tab shows programs launching at sign-in.',
    'Find the thing that is busiest.'),
  card(sw, 'slow-causes', 'Name common causes of slow performance.',
    'Too little RAM, too many startup programs, a nearly full or failing drive, malware, overheating and outdated drivers.',
    'Work from cheapest to check to most expensive: startup items and disk space first, RAM or a drive swap later.',
    'Think resources, clutter, faults and infections.'),
  card(sw, 'no-os', 'A PC says “Operating system not found” or “Boot device not found”. What are likely causes?',
    'A wrong boot order, a disconnected or failed drive, or damaged boot records (BCD or MBR).',
    'Check firmware first: is the drive detected, and is it first in the boot order? Then repair the boot records.',
    'The firmware cannot find something to start.'),
  card(sw, 'bootrec', 'Which recovery commands repair Windows boot records?',
    'bootrec /fixmbr, bootrec /fixboot and bootrec /rebuildbcd, from the recovery command prompt.',
    'They rewrite the master boot record, the boot sector and the boot configuration data respectively.',
    'The command starts with boot and ends with rec.'),
  card(sw, 'winre', 'What is the Windows Recovery Environment used for?',
    'Startup Repair, System Restore, uninstalling updates, a command prompt, and resetting or reimaging the PC when Windows will not start.',
    'Windows starts it automatically after repeated failed boots, or you can boot from install media.',
    'A repair mode that runs outside your normal Windows.'),
  card(sw, 'safe-mode', 'When would you boot into Safe Mode?',
    'To troubleshoot with only basic drivers and services: remove a bad driver, run malware scans, or undo a change that stops normal boot.',
    'If a problem disappears in Safe Mode, the cause is a driver, service or startup program.',
    'It loads the bare minimum.'),
  card(sw, 'app-crash', 'An application keeps crashing. What steps help?',
    'Check Event Viewer, update or repair or reinstall the app, check compatibility and free resources, and scan for malware.',
    'The error in Event Viewer usually points to a module or a dependency that failed.',
    'Read the log, then try repair before reinstalling.'),
  card(sw, 'service-wont-start', 'A Windows service will not start. What do you check?',
    'In services.msc, its dependencies and logon account, and Event Viewer for the error.',
    'A service fails when something it depends on is stopped or its account’s password changed.',
    'It may need something else, or the right account.'),
  card(sw, 'slow-profile', 'A user’s sign-in takes minutes and the desktop is slow to load. What might be wrong?',
    'A corrupt or very large user profile, or slow network access to a roaming profile or domain controller.',
    'Test with a new profile: if it is fast, the old profile is the problem.',
    'Something about the user’s settings or where they load from.'),
  card(sw, 'time-drift', 'A PC’s clock is wrong and certificate errors appear. What might cause it?',
    'A dead CMOS battery or a failed time sync (NTP or domain).',
    'A wrong date makes valid certificates look expired or not yet valid, so HTTPS sites throw errors.',
    'The hardware clock or the sync that corrects it.'),
  card(sw, 'low-memory', 'Windows warns that memory is low. What helps?',
    'Close apps and startup items, add RAM, and check the paging file size.',
    'The paging file is disk space Windows uses as overflow memory. It is slower than RAM.',
    'Use less of it or add more of it.'),
  card(sw, 'usb-not-recognised', 'A USB device is not recognised. What do you try?',
    'A different port and cable, reinstalling or updating the driver in Device Manager, checking power settings, and testing on another PC.',
    'Isolate the fault: if it works elsewhere, the problem is the PC; if not, the device or cable.',
    'Swap one thing at a time.'),
  card(sw, 'update-fails', 'Windows Update keeps failing. What do you try?',
    'Run the Windows Update troubleshooter, free disk space, restart the update services, run sfc and DISM, then retry.',
    'Corrupt update components and full disks are the usual causes.',
    'Clear space and repair the tools before retrying.'),
  card(sw, 'dism', 'When sfc /scannow cannot repair files, what do you run next?',
    'DISM, for example dism /online /cleanup-image /restorehealth, then rerun sfc.',
    'DISM repairs the component store that sfc draws its good copies from.',
    'It repairs the source that sfc copies from.'),
  card(sw, 'malware-symptoms', 'List common symptoms of malware on a PC.',
    'Pop-ups, browser redirects and changed homepages, disabled antivirus, unknown programs, high CPU use, and files renamed or missing.',
    'Any one symptom is only a clue. Verify before you start removing.',
    'The PC does things you did not ask.'),
  card(sw, 'cert-warnings', 'Why might a browser show certificate warnings on many sites at once?',
    'The PC’s clock may be wrong, or traffic is being intercepted by an on-path attack, a proxy or malware.',
    'Check the date and time first. If that is right, treat repeated warnings as a possible interception.',
    'Something is wrong with trust, not with one site.'),
  card(sw, 'rogue-av', 'What is rogue antivirus?',
    'A fake security alert or scanner that scares users into paying or installing malware. Close it from Task Manager and scan with real tools.',
    'Real antivirus does not appear as a browser pop-up demanding a card number.',
    'It pretends to be a defender.'),
  card(sw, 'browser-redirect', 'A browser redirects searches and shows pop-ups. How do you fix it?',
    'Remove unknown extensions, clear the cache, reset the browser, and run an anti-malware scan.',
    'Hijacked browsers usually carry a malicious extension or changed settings.',
    'Clean the browser, then check the machine.'),
  card(sw, 'mobile-battery', 'A phone’s battery drains quickly and it runs hot. What do you check?',
    'Battery usage by app, brightness, background activity, location and radios, and OS updates. Look for rogue or malicious apps.',
    'One app draining power often shows at the top of the battery usage list.',
    'Find what is using the power.'),
  card(sw, 'mobile-app-crash', 'A phone app will not open or keeps crashing. What steps help?',
    'Force stop and restart it, clear its cache, update or reinstall it, restart the phone and update the OS.',
    'Go from least to most disruptive so you keep the user’s data.',
    'Start with the gentlest fix.'),
  card(sw, 'mobile-data-spike', 'A phone’s data use suddenly spikes. What are possible causes?',
    'A malicious or misbehaving app in the background, or automatic cloud uploads or updates over cellular.',
    'Check per-app data usage, then restrict background data or remove the app.',
    'Something is talking a lot over cellular.'),
  card(sw, 'mobile-reset', 'When is a factory reset the right answer on a mobile device?',
    'As a last resort after simpler fixes fail, or before handing the device on. Back up first.',
    'It removes the user’s apps and settings, so it comes after every gentler option.',
    'The final step, after a backup.'),
  card(sw, 'mobile-connectivity', 'A phone shows no service or will not join Wi-Fi. What can you try?',
    'Toggle airplane mode, restart, reseat the SIM, forget and rejoin the network, or reset network settings.',
    'Toggling the radios often clears a stuck connection without touching data.',
    'Cycle the radios first.'),
  card(sw, 'sideloading', 'Why is sideloading apps risky?',
    'Apps installed from outside the official store skip vetting and can carry malware.',
    'Stores scan and review apps; a random file from the web has had none of that.',
    'It bypasses the store’s checks.'),
];

const ops = 'a2-d4';
export const OPERATIONS_CARDS: Card[] = [
  card(ops, 'docs-types', 'Name kinds of documentation a help desk relies on.',
    'Ticket records, knowledge base articles, network diagrams and standard operating procedures (SOPs).',
    'Good documentation means the next technician, or you in six months, does not start from scratch.',
    'Records of work, answers, maps and procedures.'),
  card(ops, 'sop', 'What is an SOP and why does it matter?',
    'A standard operating procedure: written steps so a task is done the same, correct way every time.',
    'Consistency reduces mistakes and makes training and audits easier.',
    'Written steps for a routine job.'),
  card(ops, 'ticket-fields', 'What should a good support ticket capture?',
    'Who reported it, contact details, a clear description, category, priority or severity, steps taken, the resolution and any escalation.',
    'The next person should understand the case without asking the user again.',
    'Enough detail to hand it over cleanly.'),
  card(ops, 'escalation', 'What is escalation in a ticket system?',
    'Passing a ticket to a higher tier or specialist when you lack the skill, access or authority to resolve it.',
    'Escalating with notes of what you tried saves the next tier from repeating your work.',
    'Sending it up to someone with more reach.'),
  card(ops, 'sla', 'What is an SLA?',
    'A service level agreement: the promised response and resolution times for a class of ticket.',
    'It sets expectations for the customer and a measure for the support team.',
    'A promise about how quickly you will respond.'),
  card(ops, 'aup', 'What is an acceptable use policy?',
    'A document setting out how employees may use company systems and data, signed so expectations and consequences are clear.',
    'It gives IT something to point to when usage crosses the line.',
    'The rules of use that everyone signs.'),
  card(ops, 'asset-tags', 'Why tag and inventory assets?',
    'To track ownership, location, warranty and lifecycle. Asset tags and barcodes tie a device to its record.',
    'You cannot patch, replace or recover what you do not know you have.',
    'A label that links a device to its record.'),
  card(ops, 'change-request', 'What should a change request include?',
    'The purpose, scope, date and time, affected systems, risk analysis, a plan and a rollback (backout) plan, and approval.',
    'Documented changes are easier to approve, schedule and undo.',
    'Why, what, when, how risky, and how to undo it.'),
  card(ops, 'change-testing', 'Why test a change in a sandbox and keep a backout plan?',
    'A sandbox proves it works without risking production. A backout plan lets you undo it fast if it fails.',
    'Most outages after a change come from an untested change with no way back.',
    'Try it safely first, and know how to reverse it.'),
  card(ops, 'backup-321', 'What is the 3-2-1 backup rule?',
    'Keep three copies of data, on two different media, with one copy off-site.',
    'Different media and locations protect against a single disk failure, a fire and ransomware together.',
    'Three, two and one.'),
  card(ops, 'backup-types', 'How do full, incremental and differential backups differ?',
    'Full copies everything. Incremental copies changes since the last backup of any type. Differential copies changes since the last full.',
    'Incrementals are small and quick to make but slow to restore; differentials grow over the week but restore faster.',
    'They differ in what they compare against.'),
  card(ops, 'backup-restore', 'You use a weekly full backup plus daily incrementals. To restore on Thursday, what do you need?',
    'The last full backup and every incremental since, in order.',
    'Each incremental holds only that day’s changes, so a missing one breaks the chain. A differential would need only the full plus the latest.',
    'Every link in the chain.'),
  card(ops, 'backup-test', 'Why test restores?',
    'A backup you have never restored is unproven. Media, permissions or the process may fail when you need it.',
    'Schedule regular test restores so you find problems before an emergency.',
    'A backup only counts if it comes back.'),
  card(ops, 'esd', 'How do you protect components from electrostatic discharge?',
    'Wear an ESD wrist strap clipped to bare metal on the case, use an anti-static mat, and keep parts in anti-static bags.',
    'You cannot feel most ESD that kills a chip, so the precaution is habit, not a reaction.',
    'Keep yourself and the part at the same potential.'),
  card(ops, 'electrical-safety', 'What are safe practices when working inside a PC?',
    'Power off and unplug, never open a power supply, remove jewellery, and keep liquids away.',
    'A PSU’s capacitors can hold a dangerous charge even when unplugged, so it is not a field-serviceable part.',
    'Remove the power before your hands go in.'),
  card(ops, 'fire-class-c', 'Which fire extinguisher class is for electrical fires?',
    'Class C, using CO2 or a clean agent. Never water.',
    'Water conducts electricity and can spread the fire or electrocute you. Cut the power if it is safe to do so.',
    'It is the third letter.'),
  card(ops, 'sds', 'What is a Safety Data Sheet (SDS)?',
    'A document describing a product’s hazards, handling, first aid and disposal, for things like toner and batteries.',
    'It is the first place to check before cleaning up a spill or disposing of a chemical.',
    'The hazard paperwork that comes with a product.'),
  card(ops, 'lifting', 'How do you lift a heavy device safely?',
    'Bend your knees, keep your back straight, hold the load close, and use a cart or ask for help for heavy items.',
    'Your legs are stronger than your back, and a dropped server is a hazard too.',
    'Let your legs do the work.'),
  card(ops, 'ups-vs-surge', 'What is the difference between a surge protector and a UPS?',
    'A surge protector absorbs voltage spikes. A UPS also provides battery power so equipment can ride out an outage or shut down cleanly.',
    'A surge protector does nothing during a blackout, so critical equipment usually needs a UPS.',
    'One has a battery, one does not.'),
  card(ops, 'angry-customer', 'How should you handle an angry customer?',
    'Stay calm, listen without interrupting, do not argue or get defensive, restate the problem, and explain the next steps.',
    'Being heard lowers the temperature, and clear next steps give them something to hold.',
    'Listen before you fix.'),
  card(ops, 'clear-communication', 'What is good practice when explaining a fix?',
    'Avoid jargon, be honest about time and outcome, confirm understanding and follow up.',
    'A user who understands what happened is less likely to call again about the same thing.',
    'Say it plainly and check they followed.'),
  card(ops, 'confidentiality', 'You see private data on a customer’s screen while fixing their PC. What do you do?',
    'Do not read, copy or discuss it beyond what the task needs. Respect confidentiality.',
    'Trust is the job. Access to a machine is not permission to look at everything on it.',
    'It is not yours to read.'),
  card(ops, 'remote-access', 'Name common remote access tools, and a security concern with them.',
    'RDP, SSH, VNC, VPN and screen-sharing or RMM tools. Exposed remote access is a top attack path, so use MFA, updates and least privilege.',
    'Attackers scan the internet for open remote access, so treat it like a front door.',
    'Ways to reach a machine from far away.'),
  card(ops, 'script-types', 'Which file extensions are used for batch, PowerShell, Bash, Python and JavaScript scripts?',
    '.bat, .ps1, .sh, .py and .js.',
    'Match the language to the platform: .bat and .ps1 on Windows, .sh on Linux and macOS.',
    'Short extensions, one per language.'),
  card(ops, 'script-uses', 'Give two uses of scripts in IT support, and a risk.',
    'Automating backups, installing updates or software, gathering inventory, and mapping drives. Risks include unintentionally deleting data or running untrusted code.',
    'Test a script on one machine before running it on a hundred.',
    'Repetitive jobs are candidates; one bad line runs everywhere.'),
  card(ops, 'ai-limits', 'What are two limits of generative AI tools to keep in mind at work?',
    'They can produce confident but wrong answers (hallucinations) and reflect bias, and pasting private or company data into a public tool can leak it.',
    'Treat output as a draft to verify and follow the company’s policy on what data may be shared.',
    'Confident is not the same as correct.'),
  card(ops, 'chain-of-custody', 'What is chain of custody?',
    'Documentation of who handled evidence and when, proving it was not altered.',
    'Without it, evidence from a security incident may not be usable. Preserve data, document, and report through the proper channel.',
    'A record of every hand the evidence passed through.'),
  card(ops, 'disposal', 'How should batteries and toner be disposed of?',
    'At an approved recycler or hazardous-waste program, following local rules, never in ordinary trash.',
    'Lithium batteries can ignite in a bin or compactor, and toner is fine powder that should not be released.',
    'Special handling, not the bin.'),
  card(ops, 'environment', 'What environmental factors matter for a computer room?',
    'Temperature, humidity, ventilation and dust. Very low humidity raises ESD risk and very high humidity causes condensation.',
    'Heat and dust shorten equipment life, and airflow keeps hot spots from forming.',
    'The air around the equipment.'),
  card(ops, 'eula-drm', 'What are an EULA and DRM?',
    'A EULA is the end-user license agreement, the terms for using software. DRM limits copying or use of protected content.',
    'Installing business software without the right licence is a legal and audit risk.',
    'One is the agreement, one is the enforcement.'),
];

export const A2_CARDS: Card[] = [...OS_CARDS, ...SECURITY_CARDS, ...SOFTWARE_CARDS, ...OPERATIONS_CARDS];
