import type { Card } from './types';

/**
 * A+ Core 1 (220-1201). Topics follow the official objectives as an outline;
 * every word here is original. Verify against CompTIA's objectives PDF before
 * relying on coverage.
 */
const card = (domain: string, slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'objective-outline',
  tags: slug.startsWith('mb-') ? ['motherboard'] : undefined,
});

const hw = 'a1-d3';

/** One card per part of the motherboard diagram. */
export const MOTHERBOARD_CARDS: Card[] = [
  card(hw, 'mb-rear-io',
    'On a desktop, where do the monitor, network cable and USB keyboard plug in?',
    'The rear I/O panel: the ports built onto the back edge of the motherboard.',
    'They are part of the board, so the board decides which ports you get (USB, RJ45 Ethernet, audio, and video out for integrated graphics). The metal I/O shield just fills the gap in the case.',
    'The cluster of ports you see on the back of the case.'),
  card(hw, 'mb-eps8',
    'What does the 8-pin (4+4) connector near the top-left of the board power?',
    'The CPU, through the voltage regulators around the socket. It is the EPS12V connector.',
    'The 24-pin cable cannot feed a modern CPU on its own. Forgetting this plug is a classic "fans spin, nothing on screen" build mistake.',
    'It sits near the socket and feeds just one component.'),
  card(hw, 'mb-cpu-socket',
    'LGA or PGA: where are the pins?',
    'LGA: the pins are in the socket and the CPU has flat pads. PGA: the pins are on the CPU and the socket has holes.',
    'A socket only takes CPUs made for it, so the socket name (for example LGA1700 or AM5) is the first thing to match when choosing a CPU.',
    'LGA: the L is for Land, as in flat landing pads. So which part has the pins?'),
  card(hw, 'mb-fan-header',
    'Which header should the CPU cooler’s fan use, and why does it matter?',
    'CPU_FAN, a 4-pin PWM header next to the socket.',
    'Firmware watches CPU_FAN. With nothing on it, many boards warn or stop at boot, and PWM is how the fan speeds up as the CPU warms.',
    'A small 4-pin header named after the processor it keeps cool.'),
  card(hw, 'mb-dimm',
    'The tall slots beside the CPU take what, and how do two sticks run in dual channel?',
    'DIMMs (desktop RAM). Put the pair in the slots the manual names, usually A2 and B2.',
    'A notch in each stick stops the wrong DDR generation fitting. Dual channel gives the CPU two paths to memory, so which slots you use changes the speed.',
    'Memory sticks. The manual says which two slots pair up.'),
  card(hw, 'mb-atx24',
    'What is the widest power connector on the board?',
    'The 24-pin ATX main power connector (20-pin on old boards).',
    'It carries 3.3 V, 5 V and 12 V to the whole board. A 20+4 pin plug from the power supply fits both kinds.',
    'The biggest plug coming from the power supply.'),
  card(hw, 'mb-pcie-x16',
    'What usually goes in the long PCIe x16 slot nearest the CPU?',
    'The graphics card.',
    '"x16" is sixteen lanes, the most bandwidth a slot offers. The one nearest the CPU is normally wired straight to it.',
    'The longest expansion slot, with the most lanes. Think gaming.'),
  card(hw, 'mb-pcie-x1',
    'What fits a short PCIe x1 slot?',
    'Small expansion cards: Wi-Fi, sound, an extra network or USB card.',
    'One lane is plenty for them. A short card fits a longer PCIe slot, never the other way round.',
    'The shortest PCIe slot, for small add-in cards.'),
  card(hw, 'mb-m2',
    'What is the M.2 slot for, and which two ways can an M.2 SSD talk to the system?',
    'A small SSD that screws flat to the board. It runs as NVMe over PCIe (fast) or as SATA (slower).',
    'Same shape, different bus, so check what the slot supports. The notches on the edge connector (B key, M key) are the hint.',
    'A stick-of-gum-sized SSD that screws flat to the board. It can use one of two buses.'),
  card(hw, 'mb-chipset',
    'What does the chipset do?',
    'It links the CPU to the slower parts: SATA, USB, extra PCIe lanes, audio and networking.',
    'Modern CPUs talk to RAM and the main x16 slot directly; the chipset handles the rest. Older boards split this job into a northbridge and a southbridge.',
    'The traffic controller between the CPU and the slower devices.'),
  card(hw, 'mb-sata',
    'What plugs into the SATA ports?',
    '2.5" and 3.5" drives and optical drives, one per port. The drive’s power comes separately from the power supply.',
    'SATA III tops out at 6 Gb/s, which is why an NVMe SSD is faster. The L-shaped plug only fits one way round.',
    'Small L-shaped data ports for drives.'),
  card(hw, 'mb-cmos',
    'What does the coin cell on the board do, and what does a dead one look like?',
    'It keeps the clock and firmware settings alive while the PC is unplugged. When it dies, the time resets and settings are lost at every boot.',
    'Swapping the CR2032 (or clearing CMOS on purpose) puts firmware settings back to their defaults, which is also a known fix for a board that will not POST after a bad setting.',
    'A CR2032 coin cell. What would be forgotten every time the PC is unplugged?'),
  card(hw, 'mb-uefi',
    'What lives on the UEFI firmware chip?',
    'The firmware that runs POST, finds a boot device and starts the operating system, plus its setup screens.',
    'UEFI replaced legacy BIOS and adds Secure Boot and booting from GPT disks larger than 2 TB. Updating it is called flashing the firmware.',
    'The firmware that runs POST before the operating system loads.'),
  card(hw, 'mb-usb-header',
    'What connects to the internal USB header?',
    'The case’s front USB ports.',
    'Front ports are only a cable back to the board. If they are dead, check this header before blaming the ports.',
    'It connects the ports on the front of the case.'),
  card(hw, 'mb-front-panel',
    'What connects to the front-panel header?',
    'The case’s power button, reset button, power LED and drive-activity LED.',
    'The pins are tiny and labelled (PWR_SW, RESET, PLED, HDD_LED). A PC that never turns on may just have the power switch on the wrong pins.',
    'Where the case’s power button and LEDs plug in.'),
];

const mob = 'a1-d1';

/** 1.0 Mobile devices. */
export const MOBILE_CARDS: Card[] = [
  card(mob, 'laptop-ram-sodimm',
    'What form of memory module does most laptop RAM use?',
    'SO-DIMM: a shorter module than a desktop DIMM, installed at an angle and pressed down until the clips lock.',
    'A desktop DIMM will not fit a laptop slot. Many thin laptops also solder RAM to the board, so check before promising an upgrade.',
    'The little cousin of the desktop memory stick.'),
  card(mob, 'laptop-storage-swap',
    'A customer wants a faster laptop and it still has a 2.5-inch hard drive. What is the usual upgrade?',
    'Swap it for a 2.5-inch SATA SSD, or an M.2 SSD if the board has a slot, and clone or reinstall the OS.',
    'Moving from spinning disk to flash is the biggest speed gain per dollar in an old laptop. Check the slot type (SATA vs NVMe, key, length) before buying.',
    'The slowest part in an old laptop is usually the one that spins.'),
  card(mob, 'battery-swelling',
    'A laptop’s touchpad is lifting and the case bulges. What is the likely cause and the right response?',
    'A swollen lithium-ion battery. Power it off, do not puncture or charge it, remove it if safe, and recycle it as hazardous waste.',
    'Swelling is gas from a failing cell and can end in fire. It is a safety issue first and a repair second.',
    'Something inside is expanding under the touchpad. Which part stores energy chemically?'),
  card(mob, 'display-types',
    'Which laptop display type has no backlight because each pixel makes its own light?',
    'OLED. LCD panels (IPS, TN, VA) need a backlight, usually LED.',
    'No backlight means true blacks and a thinner panel, but OLED can suffer burn-in from static images.',
    'The panel type phones brag about for true blacks.'),
  card(mob, 'display-components',
    'Besides the panel, what sits in a laptop’s lid?',
    'The Wi-Fi antennas, the webcam and microphone, and often the digitizer for touch; on older LCDs, an inverter for the backlight.',
    'Antennas in the lid explain why a badly reassembled screen can cause weak Wi-Fi, and why a dim screen on an old laptop points to the inverter or backlight.',
    'The lid is the highest point, which suits anything that sends or receives signals.'),
  card(mob, 'digitizer',
    'A tablet displays fine but ignores touches in one area. Which part is failing?',
    'The digitizer, the touch-sensing layer over (or bonded to) the display.',
    'Display and touch are separate jobs. A good picture with dead touch points at the digitizer, not the LCD or OLED.',
    'Showing the picture works; sensing the finger does not.'),
  card(mob, 'mobile-connections',
    'Name the common short-range wireless links a phone uses besides Wi-Fi and cellular.',
    'Bluetooth (headsets, keyboards), NFC (tap-to-pay, a few centimetres) and, on some devices, infrared for remotes.',
    'NFC’s tiny range is deliberate: you have to mean it to pay. Bluetooth needs pairing first, which is the first thing to check when an accessory "does not work".',
    'One of them only works when two things almost touch.'),
  card(mob, 'bluetooth-pairing',
    'What are the basic steps to pair a Bluetooth headset with a phone?',
    'Turn on Bluetooth, put the headset in pairing (discoverable) mode, pick it on the phone, confirm the PIN or passkey if asked, then test.',
    'Most "it will not connect" calls are a device that is not in pairing mode, or one already paired to something else nearby.',
    'The accessory has to announce itself first.'),
  card(mob, 'hotspot-tethering',
    'What is the difference between tethering and a mobile hotspot?',
    'Both share the phone’s cellular data. Tethering usually means over USB or Bluetooth to one device; a hotspot shares it over Wi-Fi to several.',
    'Both use the data plan, and some carriers limit or charge for it, which is a common reason it "stops working".',
    'One uses a cable or a single pairing; the other turns the phone into a small access point.'),
  card(mob, 'mobile-sync',
    'A user’s contacts and calendar should appear on both their phone and laptop. What makes that happen?',
    'Synchronization with an account (for example Microsoft 365, Google or iCloud) that stores the data in the cloud and copies changes to every device.',
    'When items are missing on one device, check that it is signed into the same account and that sync for that data type is switched on.',
    'The data lives in one place, and each device keeps a copy up to date.'),
  card(mob, 'mdm',
    'What does mobile device management (MDM) let a company do?',
    'Enroll phones and tablets, push settings and apps, enforce passcodes and encryption, and lock or wipe a lost device remotely.',
    'It is how help desk manages hundreds of devices without touching each one, and how company data is protected when a phone is lost.',
    'Managing a fleet of phones from one console.'),
  card(mob, 'mfa-authenticator',
    'Why might a new phone need the company’s authenticator app set up again?',
    'The authenticator’s secrets are tied to the old device, so multifactor sign-in must be re-registered on the new one.',
    'A user who wipes or trades in a phone without moving their authenticator gets locked out. Plan the move before the old phone is gone.',
    'The second factor lives on a specific device.'),
  card(mob, 'docking-station',
    'What does a laptop docking station or port replicator add?',
    'Extra ports (displays, USB, Ethernet, audio) and often charging, through one connection so the laptop becomes a desk setup.',
    'Modern docks mostly connect over USB-C or Thunderbolt. A dock that charges but shows no display often needs a firmware or driver update or a port that supports video.',
    'One plug turns a laptop into a full desk.'),
  card(mob, 'laptop-keyboard-fn',
    'A laptop’s Wi-Fi, screen brightness or touchpad suddenly stops working, and nothing is broken. What should you check first?',
    'The Fn key toggles and function-key settings: one of them may have switched the feature off.',
    'Hardware toggles and airplane mode cause a surprising share of "it just stopped" tickets. It takes seconds to rule out.',
    'The shortcut keys along the top row can switch things off.'),
  card(mob, 'accelerometer-gyro',
    'Which sensors let a phone rotate its screen when you turn it sideways?',
    'The accelerometer (and gyroscope) sense orientation and movement.',
    'If rotation stops, check rotation lock before calling it a sensor failure.',
    'A sensor that feels gravity and tilt.'),
];

const net = 'a1-d2';

/** 2.0 Networking. */
export const NETWORKING_CARDS: Card[] = [
  card(net, 'port-ftp', 'Which ports does FTP use?',
    'TCP 20 for data and TCP 21 for control.',
    'FTP sends credentials in plain text, which is why SFTP or FTPS replaces it where security matters.',
    'Two neighbouring numbers, both just under the port for SSH.'),
  card(net, 'port-ssh-telnet', 'Which ports do SSH and Telnet use?',
    'SSH is TCP 22; Telnet is TCP 23.',
    'Both give a remote command line, but only SSH encrypts it. Telnet should not cross a network you do not trust.',
    'Next-door numbers: the secure one comes first.'),
  card(net, 'port-smtp', 'Which port does SMTP use to send mail between servers?',
    'TCP 25.',
    'SMTP only sends. Mail clients read with POP3 or IMAP, and often submit outgoing mail on 587 with encryption.',
    'Sending mail: a quarter of a hundred.'),
  card(net, 'port-dns', 'Which port does DNS use?',
    'Port 53, mostly UDP for lookups and TCP for large replies and zone transfers.',
    'If names fail to resolve but IP addresses work, something is blocking or breaking port 53.',
    'Name lookups: fifty-something.'),
  card(net, 'port-dhcp', 'Which ports does DHCP use?',
    'UDP 67 (server) and UDP 68 (client).',
    'The client has no address yet, so it broadcasts. That is why DHCP needs a relay to cross routers.',
    'A pair in the high sixties, one for each side.'),
  card(net, 'port-http-https', 'Which ports do HTTP and HTTPS use?',
    'HTTP is TCP 80; HTTPS is TCP 443.',
    'HTTPS wraps the same web traffic in TLS. A site that loads on 80 but not 443 often points to a certificate or firewall problem.',
    'The secure one is a three-digit number with a repeated four.'),
  card(net, 'port-pop-imap', 'Which ports do POP3 and IMAP use?',
    'POP3 is TCP 110; IMAP is TCP 143.',
    'POP3 usually downloads mail to one device; IMAP keeps it on the server so every device sees the same folders.',
    'One is a round one-hundred-and-something, the other ends in 43.'),
  card(net, 'port-smb-rdp', 'Which ports do SMB file sharing and Remote Desktop use?',
    'SMB is TCP 445 (older NetBIOS over 137–139); RDP is TCP 3389.',
    'Exposing either straight to the internet is a common way in for attackers, so they belong behind a VPN.',
    'Windows file shares sit in the 400s; the remote desktop port has four digits.'),
  card(net, 'port-ldap-snmp', 'Which ports do LDAP and SNMP use?',
    'LDAP is TCP 389; SNMP is UDP 161 (traps on 162).',
    'LDAP queries directories such as Active Directory; SNMP lets monitoring tools read device counters.',
    'A directory lookup in the 300s; device monitoring in the 160s.'),
  card(net, 'tcp-vs-udp', 'What is the practical difference between TCP and UDP?',
    'TCP sets up a connection and guarantees ordered, acknowledged delivery; UDP just sends, with no handshake or retries.',
    'Downloads and web pages need every byte, so they use TCP. Voice, video and DNS lookups prefer speed, so they use UDP.',
    'One checks every delivery arrived; the other throws and hopes.'),
  card(net, 'wifi-standards', 'Which Wi-Fi generation is 802.11ax, and which bands does it use?',
    'Wi-Fi 6 on 2.4 and 5 GHz; Wi-Fi 6E adds 6 GHz.',
    'The band decides range and speed: 2.4 GHz reaches further but is crowded; 5 and 6 GHz are faster but weaker through walls.',
    'The letters that come after ac.'),
  card(net, 'wifi-bands', 'Why might a laptop get a stronger Wi-Fi signal on 2.4 GHz but faster speeds on 5 GHz?',
    'Lower frequencies travel further and pass through walls better; higher frequencies carry more data over shorter range.',
    'It explains most "fast in the living room, slow in the bedroom" complaints.',
    'Longer waves, longer reach.'),
  card(net, 'wifi-channels', 'Which 2.4 GHz channels do not overlap in North America?',
    'Channels 1, 6 and 11.',
    'Neighbouring access points on overlapping channels interfere, so a site survey places them on 1, 6 and 11.',
    'Three numbers, five apart.'),
  card(net, 'dhcp-dora', 'What four steps does a client take to get an address from DHCP?',
    'Discover, Offer, Request, Acknowledge (DORA).',
    'If a client ends up with a 169.254.x.x address, the Discover got no Offer back.',
    'A four-letter name that sounds like an explorer.'),
  card(net, 'apipa', 'A PC shows an address of 169.254.12.7. What does that tell you?',
    'It is an APIPA (link-local) address: the PC asked for a DHCP address and got no answer.',
    'Look at the cable, the switch port, the VLAN or the DHCP server, not the PC’s IP settings.',
    'The PC gave itself an address because nobody handed it one.'),
  card(net, 'private-ranges', 'What are the IPv4 private address ranges?',
    '10.0.0.0/8, 172.16.0.0/12 (172.16–172.31) and 192.168.0.0/16.',
    'Private addresses are not routed on the internet, so NAT translates them at the edge.',
    'One starts with 10, one with 172, one with 192.'),
  card(net, 'subnet-mask', 'What does a subnet mask of 255.255.255.0 (/24) mean for a network?',
    'The first three octets are the network; the last is for hosts, giving 254 usable addresses.',
    'Two devices with different masks or networks cannot talk directly and must go through the default gateway.',
    'Count how many octets are all ones.'),
  card(net, 'ipv6-basics', 'How long is an IPv6 address, and how is it written?',
    '128 bits, written as eight groups of four hex digits separated by colons; one run of zero groups can be shortened to ::.',
    'IPv6 removes the need for NAT and has link-local addresses starting fe80:: on every interface.',
    'Four times as many bits as IPv4.'),
  card(net, 'dns-records', 'What do DNS A, AAAA, MX and CNAME records hold?',
    'A: an IPv4 address. AAAA: an IPv6 address. MX: the mail server for a domain. CNAME: an alias pointing to another name.',
    'Mail that bounces for a whole domain often traces back to a wrong or missing MX record.',
    'The quadruple letter is for the longer kind of address.'),
  card(net, 'dns-txt-spf', 'Which DNS record type holds SPF, DKIM and DMARC settings for email?',
    'TXT records.',
    'They tell receiving servers which senders are allowed for the domain, which cuts spoofing and keeps real mail out of spam.',
    'The record type that is just text.'),
  card(net, 'switch-vs-router', 'What is the difference between a switch and a router?',
    'A switch forwards frames between devices on the same network by MAC address; a router forwards packets between networks by IP address.',
    'Your home "router" is really several devices in one box: router, switch, access point and often a firewall.',
    'One works inside a network, the other between networks.'),
  card(net, 'poe', 'What does Power over Ethernet let you do?',
    'Send power and data over the same Ethernet cable, from a PoE switch or injector, to devices like access points, phones and cameras.',
    'No outlet is needed where the device is mounted. If a PoE device will not power up, check that the switch port supplies enough power.',
    'One cable does two jobs.'),
  card(net, 'cable-categories', 'Which twisted-pair category is the usual minimum for 10 Gbps over the full 100 m?',
    'Cat 6a. Cat 6 manages 10 Gbps only over shorter runs (about 55 m); Cat 5e is rated for 1 Gbps.',
    'Cable category limits speed, so a new 10 Gb link on old cable can fall back to 1 Gb.',
    'The one with an "augmented" letter on the end.'),
  card(net, 'fiber-types', 'When would you choose single-mode fiber over multimode?',
    'For long runs (kilometres). Multimode is cheaper and suits shorter runs inside a building or campus.',
    'Single-mode’s narrow core carries one path of light, so the signal spreads less over distance.',
    'One path of light goes further than many.'),
  card(net, 'tools-network', 'What are a cable tester, a toner probe and a loopback plug each used for?',
    'A cable tester checks each wire’s continuity and pinout; a toner and probe traces which wall jack goes to which patch-panel port; a loopback plug tests a port by sending its signal straight back.',
    'Picking the right tool turns an hour of guessing into a minute of proof.',
    'One tests, one finds, one talks to itself.'),
];

const hwMore: Card[] = [
  card(hw, 'ram-ddr', 'Can a DDR4 module go in a DDR5 slot?',
    'No. Each DDR generation has its notch in a different place, so the module will not seat.',
    'The notch is keyed deliberately, so the wrong memory cannot be forced in and damaged.',
    'Look at where the gap in the gold edge sits.'),
  card(hw, 'ram-channels', 'Why install RAM in matched pairs in the slots the manual names?',
    'To run in dual-channel mode, which doubles the memory bandwidth.',
    'Two sticks in the wrong slots can run single-channel and noticeably slower, with nothing reporting an error.',
    'Two lanes are faster than one.'),
  card(hw, 'ram-ecc', 'What does ECC memory do, and where is it used?',
    'It detects and corrects single-bit memory errors. It is used in servers and workstations, and needs a board and CPU that support it.',
    'A flipped bit in a server can corrupt data silently. ECC catches it.',
    'A server cares a lot about silent mistakes.'),
  card(hw, 'storage-nvme-sata', 'Both are M.2. Why is an NVMe SSD faster than an M.2 SATA SSD?',
    'NVMe talks to the CPU over PCIe lanes; M.2 SATA is still limited by the SATA interface (about 600 MB/s).',
    'The slot looks the same, so check whether the board’s M.2 slot supports NVMe, SATA or both before buying.',
    'Same shape, different road to the CPU.'),
  card(hw, 'raid-levels', 'What do RAID 0, 1, 5 and 10 trade off?',
    'RAID 0 stripes for speed with no redundancy. RAID 1 mirrors two drives. RAID 5 stripes with parity and survives one failed drive (3+ drives). RAID 10 mirrors and stripes (4+ drives).',
    'RAID is not a backup: it survives a dead drive, not deletion or ransomware.',
    'Zero means zero protection.'),
  card(hw, 'psu-rails', 'Which voltages does a desktop power supply provide?',
    '+12 V (CPU, GPU, drives’ motors), +5 V and +3.3 V (logic and some drives).',
    'The 12 V rail carries most of the load, so a PSU’s 12 V rating matters more than its headline wattage.',
    'The biggest one powers the hungriest parts.'),
  card(hw, 'psu-modular', 'What is a modular power supply?',
    'One whose cables unplug from the unit, so you only attach the ones you need.',
    'Fewer loose cables means better airflow and an easier build.',
    'Its cables are not all permanently attached.'),
  card(hw, 'cpu-cooling', 'Why is thermal paste applied between a CPU and its cooler?',
    'It fills microscopic gaps so heat flows into the heatsink instead of being trapped by air.',
    'Too little, too old or none at all shows up as overheating and throttling under load.',
    'Air is a poor conductor of heat.'),
  card(hw, 'virtualization-bios', 'A hypervisor refuses to start 64-bit VMs. Which firmware setting is likely off?',
    'Hardware virtualization support (Intel VT-x or AMD-V) in UEFI/BIOS.',
    'Many boards ship with it disabled. Turning it on is a firmware change, not a Windows setting.',
    'The CPU has a feature for running guests, and firmware can hide it.'),
  card(hw, 'secure-boot-tpm', 'What do Secure Boot and a TPM each provide?',
    'Secure Boot only loads signed bootloaders; the TPM is a chip that stores keys, used for BitLocker and to check the boot has not been tampered with.',
    'Windows 11 requires both. They are why a failed firmware update or swapped board can trigger a BitLocker recovery prompt.',
    'One checks what starts; the other keeps secrets.'),
  card(hw, 'laser-printer-steps', 'What are the steps of the laser printing process, in order?',
    'Processing, charging, exposing, developing, transferring, fusing, cleaning.',
    'Each defect maps to a step: smudging toner that rubs off is fusing; a repeating mark is often the drum or a roller.',
    'The paper is heated near the end so the toner sticks.'),
  card(hw, 'inkjet-thermal', 'How do inkjet and thermal printers put an image on paper?',
    'Inkjets spray tiny drops of ink from nozzles; thermal printers heat special paper (or a ribbon) to make the mark.',
    'Receipt printers are usually thermal, which is why the receipts fade in heat and sunlight.',
    'One sprays, one heats.'),
  card(hw, 'printer-maintenance', 'What does a laser printer maintenance kit usually replace?',
    'The fuser and rollers (pickup, separation and transfer rollers).',
    'Printers count pages and prompt for the kit. Paper jams and misfeeds after a long service life point at worn rollers.',
    'Parts that grip the paper or heat it wear out over time.'),
  card(hw, 'usb-versions', 'How fast are USB 2.0, USB 3.2 Gen 1 and USB4?',
    'USB 2.0: 480 Mbps. USB 3.2 Gen 1 (formerly USB 3.0): 5 Gbps. USB4: up to 40 Gbps (80 Gbps in version 2).',
    'The USB-C connector says nothing about speed. The same plug can carry any of these.',
    'Each major version jumps by roughly ten times or more.'),
  card(hw, 'video-connectors', 'Which video connectors carry digital video and audio, and which is analog only?',
    'HDMI and DisplayPort (and USB-C with DP Alt Mode) carry digital video and audio. VGA is analog video only; DVI is video without audio.',
    'A projector showing a picture but no sound over VGA is working as designed.',
    'The oldest blue one carries neither digital signals nor sound.'),
];

export const HARDWARE_CARDS: Card[] = [...MOTHERBOARD_CARDS, ...hwMore];

const virt = 'a1-d4';

/** 4.0 Virtualization and cloud computing. */
export const VIRTUALIZATION_CARDS: Card[] = [
  card(virt, 'hypervisor-types', 'What is the difference between a Type 1 and a Type 2 hypervisor?',
    'Type 1 runs directly on the hardware (bare metal, e.g. Hyper-V Server, ESXi). Type 2 runs as an app on a host OS (e.g. VirtualBox, VMware Workstation).',
    'Servers use Type 1 for performance and isolation; a technician’s laptop uses Type 2 to test things safely.',
    'One has an operating system underneath it; the other is the thing underneath.'),
  card(virt, 'vm-requirements', 'What does a host need to run several VMs well?',
    'A CPU with virtualization extensions, plenty of RAM (each guest gets its own), fast storage, and enough network capacity.',
    'RAM is usually the first limit: every running guest reserves its share.',
    'Every guest wants its own slice of the same resource.'),
  card(virt, 'vm-uses', 'Name three reasons a help desk might use a virtual machine.',
    'Testing updates or software safely, running an old app that needs an older OS, and sandboxing a suspicious file.',
    'A snapshot lets you roll the VM back in seconds if the test goes wrong.',
    'Somewhere you can break things without consequences.'),
  card(virt, 'vm-snapshot', 'What is a VM snapshot, and why is it not a backup?',
    'A saved point-in-time state of a VM you can roll back to. It usually depends on the original disk, so losing that disk loses the snapshot too.',
    'Snapshots are for short-term safety before a change. Left running for weeks they grow and slow the VM.',
    'It saves the moment, but it lives on the same disk.'),
  card(virt, 'containers', 'How is a container different from a virtual machine?',
    'A container shares the host’s OS kernel and packages just an app and its dependencies; a VM includes a whole guest operating system.',
    'Containers start in seconds and use less memory, but they cannot run a different kernel than the host.',
    'One brings its own operating system; the other borrows the host’s.'),
  card(virt, 'cloud-iaas', 'In IaaS, what does the customer manage?',
    'The operating system, runtime, apps and data. The provider manages the physical hardware, virtualization and network.',
    'A cloud VM still needs patching and antivirus, and that is your job.',
    'You rent the raw computer and do everything above it.'),
  card(virt, 'cloud-paas-saas', 'How do PaaS and SaaS differ?',
    'PaaS gives developers a platform to run their own code without managing servers. SaaS is a finished application you just use, like web email.',
    'The further up the stack you go, the less you manage and the less you can customise.',
    'One is for building apps; the other is an app.'),
  card(virt, 'cloud-deployment', 'What are the public, private, hybrid and community cloud models?',
    'Public: shared provider infrastructure. Private: used by one organisation. Hybrid: a mix of the two, linked. Community: shared by organisations with common needs.',
    'The choice is mostly about control, compliance and cost.',
    'Who shares the hardware?'),
  card(virt, 'cloud-elasticity', 'What do rapid elasticity and measured service mean in cloud computing?',
    'Elasticity: resources grow and shrink automatically with demand. Measured service: you pay for what you actually use.',
    'Together they are why the cloud suits spiky workloads, and why a forgotten resource keeps costing money.',
    'Stretch when busy; the meter keeps running.'),
  card(virt, 'cloud-multitenancy', 'What is multitenancy?',
    'Many customers share the same physical infrastructure, kept separate by the provider’s software.',
    'It keeps costs low, and it is why providers put so much work into isolation.',
    'Lots of tenants in one building.'),
  card(virt, 'cloud-file-sync', 'What is cloud file synchronisation, such as OneDrive or Google Drive, and what is its main risk?',
    'Files are stored online and kept in sync across devices. Deleting or encrypting a file on one device can sync that change everywhere.',
    'Version history and the recycle bin are the first things to check after a mistake or a ransomware hit.',
    'A change in one place travels to every copy.'),
  card(virt, 'vdi', 'What is VDI?',
    'Virtual desktop infrastructure: users’ desktops run as VMs in a data centre or cloud and are shown on a thin client or any device.',
    'IT can patch one image for everyone, and data never leaves the data centre.',
    'The desktop you see runs somewhere else.'),
];

const ts = 'a1-d5';

/** 5.0 Hardware and network troubleshooting. */
export const TROUBLESHOOTING_CARDS: Card[] = [
  card(ts, 'method-steps', 'What are the steps of the CompTIA troubleshooting methodology, in order?',
    'Identify the problem; establish a theory of probable cause; test the theory; establish a plan of action and implement it; verify full system functionality (and add preventive measures); document findings, actions and outcomes.',
    'Following the order keeps you from "fixing" the wrong thing, and documenting last means the next tech benefits.',
    'Six steps; writing it all down comes last.'),
  card(ts, 'method-identify', 'What does "identify the problem" involve?',
    'Gather information from the user and logs, ask what changed recently, duplicate the problem if you can, and back up data before making changes.',
    '"What changed?" is the fastest question in IT. Updates, new hardware and moved furniture explain a lot.',
    'Before touching anything, ask and look.'),
  card(ts, 'method-escalate', 'What should you do if your theory is not confirmed?',
    'Establish a new theory, or escalate to someone with more access or experience.',
    'Escalating is part of the process, not a failure. Spending hours on a problem above your access helps nobody.',
    'Either think again or hand it up.'),
  card(ts, 'no-post-beeps', 'A PC powers on but shows nothing and beeps in a pattern. What are the beeps for?',
    'POST beep codes: the firmware reporting a hardware fault before video works. The pattern is in the board or BIOS vendor’s manual.',
    'The most common patterns point at RAM or the GPU. Reseat those first.',
    'The computer is trying to tell you something before the screen works.'),
  card(ts, 'no-power', 'A desktop shows no lights, no fans and no response. What do you check first?',
    'The outlet and power cable, the PSU switch, then the front-panel power switch wiring, then the PSU itself.',
    'Start simple and work outward. A tripped power strip is more common than a dead board.',
    'Follow the electricity from the wall inwards.'),
  card(ts, 'overheating-shutdown', 'A PC shuts off by itself under load, such as gaming. What is the likely cause?',
    'Overheating: dust, a failed fan, dried thermal paste or blocked airflow. An undersized or failing PSU is the other suspect.',
    'Check temperatures in firmware or a monitoring tool, clean the dust and look at the fans before replacing parts.',
    'It happens only when the machine works hardest.'),
  card(ts, 'bsod', 'What causes a Windows blue screen (stop error) that appears after new hardware is added?',
    'Most often a bad or incompatible driver, or faulty RAM.',
    'Note the stop code, roll back the new driver or remove the new part, and test memory.',
    'The newest thing is the first suspect.'),
  card(ts, 'ram-symptoms', 'Which symptoms point to failing RAM?',
    'Random crashes or blue screens, corrupted files, failed installs, and POST beep codes; a memory test (e.g. Windows Memory Diagnostic) confirms it.',
    'RAM faults look random, which is the clue. Test one stick at a time to find the bad one.',
    'Crashes with no pattern.'),
  card(ts, 'drive-failing', 'Which signs suggest a hard drive is failing?',
    'Clicking or grinding noises, slow file access, read/write errors, and S.M.A.R.T. warnings.',
    'Back up immediately. The drive may still be readable now and not tomorrow.',
    'Sounds a drive should not make, and warnings from its own self-monitoring.'),
  card(ts, 'boot-device', 'A PC says "no boot device found" but the drive is fine. What should you check?',
    'The boot order in UEFI/BIOS, a USB stick or disc left in, loose data cables, and whether the drive appears in firmware at all.',
    'A forgotten USB drive first in the boot order is a classic cause.',
    'Firmware may be looking in the wrong place.'),
  card(ts, 'raid-degraded', 'A RAID 5 array reports "degraded". What does that mean and what do you do?',
    'One drive has failed; the array still works but has no redundancy. Replace the drive and let it rebuild, after checking backups.',
    'A second failure during a degraded state loses the array, so act fast.',
    'It is working, but only just.'),
  card(ts, 'display-dim', 'A laptop screen is very dim but you can just see the image with a torch. What has failed?',
    'The backlight (or, on older CCFL displays, the inverter).',
    'The panel is making the picture; nothing is lighting it. That rules out the GPU.',
    'The picture is there, but nothing lights it.'),
  card(ts, 'display-artifacts', 'A monitor shows strange coloured blocks and lines, even in firmware menus. Where is the fault?',
    'Probably the GPU (overheating or failing) or the cable, rather than Windows or the driver.',
    'Artifacts before the OS loads rule out software. Try another cable and monitor, then the GPU.',
    'It happens before Windows is even running.'),
  card(ts, 'display-flicker', 'What usually causes a flickering external monitor?',
    'A loose or damaged cable, a refresh rate the monitor does not support, or a failing backlight.',
    'Reseat or swap the cable first. It is the cheapest test.',
    'Start with the thing connecting the two.'),
  card(ts, 'network-no-connectivity', 'A PC has no network connection at all. What is a good order to check things in?',
    'Link light and cable, the switch port, then the IP configuration (ipconfig), then ping the gateway, then DNS.',
    'Working up the layers (physical first) avoids chasing a DNS problem that is really an unplugged cable.',
    'Start at the physical layer and climb.'),
  card(ts, 'network-slow', 'Users report slow network speeds on one floor. What are common causes?',
    'A bad cable or port negotiating at a lower speed, Wi-Fi interference or too many clients per access point, or a saturated uplink.',
    'Check what speed the link negotiated. A port stuck at 100 Mbps instead of 1 Gbps is a quick find.',
    'Look at what the link agreed to, and who else is sharing it.'),
  card(ts, 'network-intermittent', 'A wired connection drops now and then. What should you suspect?',
    'A damaged cable or loose connector, EMI from nearby power lines or equipment, or a failing switch port.',
    'Intermittent faults are usually physical. Test and replace the cable before reconfiguring anything.',
    'Things that come and go are usually things you can touch.'),
  card(ts, 'ip-conflict', 'Windows warns about an IP address conflict. What happened?',
    'Two devices are using the same IP address, often because one was set statically inside the DHCP range.',
    'Keep static addresses outside the DHCP scope, or use DHCP reservations.',
    'Two devices are answering to the same number.'),
  card(ts, 'dns-failure', 'Websites fail by name but work by IP address. What is broken?',
    'DNS resolution: a wrong DNS server setting, the DNS server is down, or a stale cache (try ipconfig /flushdns).',
    'Checking `nslookup` against a known server separates a local setting problem from a server problem.',
    'The internet is reachable; the phone book is not.'),
  card(ts, 'printer-jams', 'A laser printer jams often. What are the common causes?',
    'Worn pickup or separation rollers, the wrong paper type or damp paper, overfilled trays, or debris in the paper path.',
    'Fanning and reloading dry paper fixes more jams than replacing parts.',
    'Start with the paper, then the parts that grab it.'),
  card(ts, 'printer-ghosting', 'Laser prints show faint repeated copies of the image further down the page. What is that called and what causes it?',
    'Ghosting, usually from a worn drum or cleaning problem, or a fuser issue.',
    'Measure the distance between repeats: it matches a roller’s circumference and tells you which part.',
    'The image repeats at a fixed distance.'),
  card(ts, 'printer-smudge', 'Laser toner rubs off the page with a finger. Which part has failed?',
    'The fuser, which should melt the toner onto the paper.',
    'Toner that sits on top was never fused. The fuser is also hot, so let it cool before touching.',
    'The step that uses heat and pressure did not happen.'),
  card(ts, 'printer-queue', 'Print jobs pile up in the queue and nothing prints. What is a common fix on Windows?',
    'Clear the queue and restart the Print Spooler service, then check the driver and connection.',
    'A single stuck job can block everything behind it.',
    'The service that holds jobs waiting to print.'),
  card(ts, 'mobile-battery-drain', 'A phone’s battery suddenly drains much faster than before. What should you check?',
    'Battery usage per app, screen brightness and timeout, background location or sync, and the battery’s health.',
    'A single misbehaving app after an update is the usual culprit.',
    'The phone’s own battery report shows who is using the power.'),
  card(ts, 'mobile-no-charge', 'A phone will not charge. What do you try before replacing the battery?',
    'Another cable and charger, clean lint out of the port, and check for liquid-damage warnings or a swollen battery.',
    'Pocket lint packed in the port is a very common and free fix.',
    'Start with what plugs in and where it plugs in.'),
  card(ts, 'method-plan', 'Before applying a fix, what should the plan of action take into account?',
    'Corporate policies and change procedures, the impact on the business and users, and a way to roll back if it goes wrong.',
    'A fix that takes down a shared server at noon, without approval, can cause a bigger problem than the one it solves.',
    'Think about who else is affected, and what the rules say.'),
  card(ts, 'clock-resets', 'A PC loses its date, time and firmware settings every time it is unplugged. What is the fix?',
    'Replace the CMOS battery on the motherboard.',
    'A wrong clock also breaks HTTPS certificates and domain logons, so the symptom may first show up as "websites are insecure".',
    'A small coin keeps settings alive while the power is off.'),
  card(ts, 'burning-smell', 'A PC gives off a burning smell. What should you do?',
    'Power it off and unplug it at once, then look for a failed PSU, swollen capacitors or scorched parts before powering it again.',
    'Smell and smoke are safety issues. Do not keep testing a machine that is burning.',
    'Safety first: remove the power before you investigate.'),
];

export const A1_CARDS: Card[] = [
  ...MOBILE_CARDS, ...NETWORKING_CARDS, ...HARDWARE_CARDS, ...VIRTUALIZATION_CARDS, ...TROUBLESHOOTING_CARDS,
];
