import type { Card } from './types';

/**
 * CS50 / intro CS, weeks 0–9. Every card is written from scratch: CS50's
 * materials are CC BY-NC-SA 4.0, so nothing here is copied from them. This is a
 * study aid for the same ideas, not a reproduction of the course; the course
 * itself is at https://cs50.harvard.edu/x/.
 */
const card = (domain: string, slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'original',
});

const w0 = 'cs50-w0';
const w1 = 'cs50-w1';
const w2 = 'cs50-w2';
const w3 = 'cs50-w3';
const w4 = 'cs50-w4';
const w5 = 'cs50-w5';
const w6 = 'cs50-w6';
const w7 = 'cs50-w7';
const w8 = 'cs50-w8';
const w9 = 'cs50-w9';

const WEEKS_0_5: Card[] = [
  // ---- Week 0: computational thinking and binary ----
  card(w0, 'bit', 'What is a bit?',
    'A single binary digit: 0 or 1. The smallest unit of information a computer stores.',
    'Physically it is a switch that is on or off — a voltage high or low, a charge present or not. Everything else, from text to video, is patterns of them.',
    'Think of the two positions of a light switch.'),
  card(w0, 'n-bits', 'How many different values can n bits represent?',
    '2ⁿ.',
    'Every extra bit doubles the count. Eight bits give 256 values (0–255), sixteen give 65,536.',
    'Each extra bit doubles how many patterns you can make.'),
  card(w0, 'binary-read', 'What is 1011 in binary, as a decimal number?',
    '11.',
    'Place values run 8, 4, 2, 1 from the left: 8 + 0 + 2 + 1 = 11. Each place is a power of two, just as decimal places are powers of ten.',
    'Place values from the right are 1, 2, 4, 8.'),
  card(w0, 'ascii', 'What is ASCII?',
    'A standard table that maps numbers to characters, so 65 is “A” and 97 is “a”.',
    'Text is numbers with an agreed meaning. ASCII covers 128 characters; Unicode extends the idea to every writing system, and UTF-8 encodes it so plain ASCII text is unchanged.',
    'A lookup table between numbers and letters; 65 is a capital letter.'),
  card(w0, 'algorithm', 'What is an algorithm?',
    'A precise, finite sequence of steps that solves a problem.',
    'Precise means a machine could follow it without judgement. The interesting question is never only “does it work” but “how does the work grow as the input does”.',
    'A recipe a machine could follow without any judgement.'),
  card(w0, 'abstraction', 'What does abstraction mean in programming?',
    'Hiding detail behind a name, so you can use something without knowing how it works.',
    'A function called sort lets you think “put these in order” rather than about comparisons and swaps. Good abstractions let one person hold a large program in their head.',
    'You call sort without thinking about swaps. What is being hidden?'),

  // ---- Week 1: C basics ----
  card(w1, 'stages', 'What are the four stages from C source code to a running program?',
    'Preprocessing, compiling, assembling, linking.',
    'Preprocessing handles lines starting with #. Compiling turns C into assembly, assembling turns that into machine code, and linking joins your code with library code such as printf.',
    'Four steps: the first handles lines starting with #, the last joins in library code.'),
  card(w1, 'include', 'What does #include <stdio.h> do?',
    'Tells the preprocessor to paste in the declarations for standard input and output, so the compiler knows what printf looks like.',
    'A declaration promises a function exists and says what it takes and returns. The definition itself arrives later, at the linking stage.',
    'Lines starting with # are handled before the compiler even starts.'),
  card(w1, 'int-division', 'What does 7 / 2 evaluate to in C when both are ints, and why?',
    '3. Integer division discards the fraction.',
    'The result has the type of the operands, and an int has no fractional part. Make one side a float (7 / 2.0) to get 3.5.',
    'Two ints in, an int out. Where does the .5 go?'),
  card(w1, 'assign-vs-equal', 'What is the difference between = and == in C?',
    '= assigns a value; == compares two values.',
    'Writing if (x = 5) assigns 5 to x and then tests it, which is always true. It compiles, which is why the mistake survives.',
    'One stores a value; the other asks a question.'),
  card(w1, 'float-precision', 'Why can a float not store 0.1 exactly?',
    'Floats store binary fractions, and 0.1 has no finite binary expansion, so it is rounded.',
    'It is the same reason 1/3 cannot be written exactly in decimal. Never compare floats with ==, and keep money in whole cents.',
    'Think of trying to write 1/3 exactly in decimal.'),
  card(w1, 'main-return', 'What does main returning 0 mean?',
    'By convention, success. Any other value tells the shell something went wrong.',
    'Scripts and other programs read that exit status (echo $? in a shell), which is how a chain of commands knows to stop.',
    'The shell reads it with echo $?. What would “no problems” be?'),
  card(w1, 'overflow', 'What is integer overflow?',
    'A result too large for its type. It wraps around for unsigned integers and is undefined behaviour for signed ones.',
    'A 32-bit signed int tops out at 2,147,483,647. Adding one more does not give a bigger number, and old bugs, including real disasters, came from assuming it would.',
    'Picture a car’s odometer rolling past 999999.'),

  // ---- Week 2: arrays and strings ----
  card(w2, 'array', 'What is an array in C?',
    'A block of memory holding elements of one type back to back, indexed from 0.',
    'Because the elements are contiguous, the address of element i is the start plus i times the element size. That is why indexing is instant.',
    'Boxes of one type side by side in memory. The first index is not 1.'),
  card(w2, 'string', 'What is a string in C?',
    'An array of chars ending with a zero byte, written \\0 and called NUL.',
    'There is no length stored; functions like strlen walk until they hit the NUL. Forgetting to leave room for it is the classic off-by-one.',
    'An array of chars, plus one special byte at the end.'),
  card(w2, 'argv', 'What do argc and argv[0] hold?',
    'argc is the number of command-line arguments including the program name; argv[0] is that program name as it was typed.',
    'Your first real argument is therefore argv[1], and argc is always at least 1.',
    'The program’s own name counts as an argument.'),
  card(w2, 'array-length', 'Why does a C function taking an array also need its length?',
    'The array decays to a pointer to its first element, and the length is not carried along.',
    'Inside the function, sizeof gives the size of a pointer, not of the array. So the caller must pass the length separately.',
    'What does an array turn into when you pass it to a function?'),
  card(w2, 'out-of-bounds', 'What happens if you write past the end of an array?',
    'Undefined behaviour: it may overwrite other data, crash, or appear to work.',
    'This is a buffer overflow, and it is the root of a huge class of security holes. C does not check bounds; you do.',
    'C never checks the index for you.'),
  card(w2, 'char-math', 'Why does \'a\' + 1 equal \'b\' in C?',
    'A char is a small integer (its ASCII code), so arithmetic on it works: 97 + 1 is 98, which is “b”.',
    'It is how a Caesar cipher works: shift the number, keep the alphabet in bounds with modulo.',
    'Under the hood, a char is just its ASCII number.'),

  // ---- Week 3: algorithms ----
  card(w3, 'linear-search', 'What is the worst-case running time of linear search?',
    'O(n): you may have to look at every element.',
    'It needs no ordering, which is its only virtue. Best case is Ω(1), when the first element matches.',
    'The unlucky case: the item is last, or not there at all.'),
  card(w3, 'binary-search', 'What does binary search require, and how fast is it?',
    'A sorted collection. It runs in O(log n).',
    'Each comparison discards half of what is left, so a billion items take about thirty steps. On unsorted data the halving is meaningless.',
    'Think of a phone book: open the middle, throw away half.'),
  card(w3, 'big-o', 'What do O, Ω and Θ describe?',
    'O is an upper bound, Ω a lower bound, and Θ a tight bound (both at once).',
    'People usually say O and mean “the worst case”. Saying an algorithm is O(n²) promises it is no worse than that, not that it is that bad.',
    'A ceiling, a floor, and both at once.'),
  card(w3, 'bubble-sort', 'What is bubble sort’s worst-case time, and when is its best case O(n)?',
    'O(n²) worst case. It is O(n) on already-sorted input, if it stops when a pass makes no swaps.',
    'It repeatedly swaps adjacent out-of-order pairs. The early exit is the difference between a lucky and an unlucky input.',
    'It swaps neighbours. What if a whole pass makes no swaps?'),
  card(w3, 'selection-sort', 'Why is selection sort Θ(n²) even on sorted input?',
    'It always scans the whole unsorted remainder to find the minimum, whatever the input looks like.',
    'It does no early exit, so best and worst case match. It does, however, do at most n swaps.',
    'It hunts for the smallest remaining item every time, whatever the input.'),
  card(w3, 'merge-sort', 'How fast is merge sort, and what does it cost?',
    'O(n log n) time, using O(n) extra memory.',
    'It splits the list, sorts each half recursively and merges them. The log n comes from the halving; the n from each merge touching every element.',
    'Halve, sort, merge. The merging needs somewhere to put things.'),
  card(w3, 'recursion', 'What two parts does every correct recursive function need?',
    'A base case that stops, and a recursive step that moves toward it.',
    'Without a base case the calls pile up on the stack until it overflows. Factorial: n! is 1 when n is 1 (base), otherwise n × (n−1)!.',
    'One part stops the calls; the other gets closer to stopping.'),

  // ---- Week 4: memory ----
  card(w4, 'pointer', 'What is a pointer?',
    'A variable that holds a memory address.',
    'It lets you refer to data without copying it, and to give a function access to the caller’s variable.',
    'Not the data itself, but where to find it.'),
  card(w4, 'address-deref', 'What do & and * do with a pointer?',
    '&x gives the address of x. *p follows the pointer p to the value it points at (dereferencing).',
    'In a declaration, * means “pointer to”; in an expression, it means “the thing at”. The same symbol, two jobs.',
    'One symbol asks “where is it?”, the other asks “what is there?”.'),
  card(w4, 'multi-declare', 'What does int *a, b; declare?',
    'a is a pointer to int; b is a plain int.',
    'The * binds to the name, not the type. To get two pointers you write int *a, *b;.',
    'Does the * belong to the type, or to the name?'),
  card(w4, 'malloc', 'What does malloc(n) return, and what must you do with it?',
    'A pointer to n bytes on the heap, or NULL if it failed. Check for NULL, and free the memory when done.',
    'Heap memory outlives the function that asked for it, which is the point and the danger: nothing frees it for you.',
    'Memory that outlives the function. It can fail, and it never cleans itself up.'),
  card(w4, 'leak', 'What is a memory leak?',
    'Heap memory that was allocated and never freed, and can no longer be reached.',
    'A short program hardly notices. A long-running one grows until the machine runs out. A tool like Valgrind finds them.',
    'Borrowed memory that is never given back.'),
  card(w4, 'stack-heap', 'What lives on the stack, and what lives on the heap?',
    'The stack holds function calls: locals, parameters and return addresses, freed automatically on return. The heap holds memory you allocate with malloc and free yourself.',
    'They grow toward each other. Too many nested calls exhaust the stack; too many allocations exhaust the heap.',
    'One is cleaned up automatically on return; the other is yours to manage.'),
  card(w4, 'segfault', 'What is a segmentation fault?',
    'The program touched memory it is not allowed to, such as dereferencing NULL or reading far past an array.',
    'The operating system stops the program. It is a kindness: the alternative is silently reading or corrupting someone else’s data.',
    'The operating system stops you for touching memory that isn’t yours.'),
  card(w4, 'dangling', 'Why is returning a pointer to a local variable a bug?',
    'The local lives on the stack and is gone when the function returns, so the pointer refers to memory that is no longer yours (a dangling pointer).',
    'It may seem to work for a while, which is worse than crashing. Return a value, or allocate on the heap.',
    'Where do local variables live, and what happens to them on return?'),
  card(w4, 'double-free', 'What is a double free, and a habit that prevents it?',
    'Calling free on the same allocation twice, which is undefined behaviour. Setting the pointer to NULL after freeing helps, since free(NULL) is harmless.',
    'It can corrupt the allocator’s bookkeeping, and attackers know how to use that.',
    'Giving back the same memory twice. What could you set the pointer to afterwards?'),

  // ---- Week 5: data structures ----
  card(w5, 'array-vs-list', 'Compare an array and a linked list.',
    'An array gives O(1) access by index but costly insertion in the middle. A linked list gives cheap insertion at a known position but O(n) access, and spends memory on pointers.',
    'The right choice depends on what you do most. If you mostly look things up by position, use an array.',
    'Boxes in a row versus a chain of nodes. Which is quick to index, which to insert into?'),
  card(w5, 'node', 'What does a singly linked list node contain?',
    'A value and a pointer to the next node. The last node’s pointer is NULL.',
    'You hold the list as a pointer to the first node, so losing that pointer loses the whole list.',
    'Two fields: the data, and the way to the next one.'),
  card(w5, 'stack-queue', 'What is the difference between a stack and a queue?',
    'A stack is last in, first out (LIFO); a queue is first in, first out (FIFO).',
    'Undo history is a stack; a print queue is a queue. Both can be built from an array or a linked list.',
    'A pile of plates versus a queue at a checkout.'),
  card(w5, 'hash-table', 'How does a hash table find a value quickly?',
    'A hash function turns the key into an array index, so lookup goes straight to the right bucket: O(1) on average.',
    'The trade is space and a good hash function. A poor one sends many keys to the same bucket and the speed disappears.',
    'A function turns the key straight into an array index.'),
  card(w5, 'collision', 'What is a hash collision, and two ways to handle it?',
    'Two keys mapping to the same index. Chaining keeps a list in each bucket; linear probing uses the next free slot.',
    'Collisions cannot be avoided in general (more keys than buckets, eventually), only managed.',
    'Two keys want the same slot: share it, or look for the next free one.'),
  card(w5, 'hash-worst', 'What is a hash table lookup’s worst case?',
    'O(n), when every key lands in the same bucket.',
    'This is why average and worst case are given separately, and why hash quality matters for anything an attacker can feed.',
    'What if the hash function sends every key to one bucket?'),
  card(w5, 'bst', 'What property defines a binary search tree, and why does balance matter?',
    'For every node, everything in the left subtree is smaller and everything in the right is larger. Balanced, search is O(log n); degenerate into a line, it is O(n).',
    'Inserting already-sorted data into a naive tree makes a line. Self-balancing trees exist to prevent it.',
    'Smaller goes one way, larger the other. What happens if you insert data that is already sorted?'),
  card(w5, 'trie', 'What is a trie, and what is its lookup cost?',
    'A tree in which each edge is a character, so a path from the root spells a key. Lookup takes time proportional to the key’s length, however many keys are stored.',
    'It is a good fit for dictionaries and autocomplete, at the cost of memory for all those pointers.',
    'Each step down the tree is one letter of the word.'),
];

const WEEKS_6_9: Card[] = [
  // ---- Week 6: Python ----
  card(w6, 'interpreted', 'How does running Python differ from running C?',
    'Python is interpreted: you run the source with the interpreter, with no separate compile step to manage. C is compiled to machine code first.',
    'Interpreted languages trade some speed for faster development and automatic memory management.',
    'One of them needs a compile step before you can run it.'),
  card(w6, 'dynamic-typing', 'What does it mean that Python is dynamically typed?',
    'Variables have no declared type. A value carries its type, and a name can be rebound to a value of another type.',
    'You write less code, but a type mistake shows up when that line runs, not when you compile.',
    'You never write int or string before a name.'),
  card(w6, 'list-tuple', 'What is the difference between a list and a tuple?',
    'A list is mutable, so you can change it. A tuple is immutable.',
    'Immutability makes tuples safe as dictionary keys and signals a fixed group of values, such as a coordinate.',
    'One of them can be changed after it is made.'),
  card(w6, 'dict', 'What is a dictionary, and how fast is a lookup?',
    'A collection of key-value pairs. Looking up a key is O(1) on average because it is built on a hash table.',
    'It is the hash table from week 5 with the bookkeeping done for you. Keys must be hashable, so a list cannot be a key.',
    'It is built on the data structure from the previous week that maps keys to buckets.'),
  card(w6, 'set', 'What does a Python set guarantee, and what is it good for?',
    'Each element appears only once, and membership tests are O(1) on average. It is good for removing duplicates and for asking whether something is present.',
    'Turning a list into a set and back is the quick way to drop repeats, though it loses the order.',
    'It rejects repeats.'),
  card(w6, 'slicing', 'What does items[1:3] return for a list?',
    'The elements at index 1 and 2. The start is included and the stop is excluded.',
    'Half-open ranges make lengths easy (stop minus start) and let slices join without overlap.',
    'It stops just before the second number.'),
  card(w6, 'comprehension', 'What is a list comprehension, and what does [x * x for x in range(4)] give?',
    'A compact way to build a list from a loop. It gives [0, 1, 4, 9].',
    'Read it as “x squared, for each x in range 4”. It replaces a loop that appends to an empty list.',
    'The loop is written inside the square brackets.'),
  card(w6, 'indentation', 'How does Python mark a block of code?',
    'By indentation rather than braces.',
    'Indentation is part of the syntax, so a misaligned line changes what the program does or stops it running.',
    'Whitespace carries meaning.'),
  card(w6, 'mutable-default', 'What goes wrong with a mutable default argument such as def add(x, items=[])?',
    'The default list is created once and shared by every call, so changes leak from one call to the next.',
    'Use None as the default and create a new list inside the function.',
    'Ask when the default value is created.'),
  card(w6, 'exceptions', 'How do you handle an error in Python without crashing the program?',
    'Put the risky code in a try block and handle the failure in an except block.',
    'Catch specific exceptions such as ValueError. Catching everything hides real bugs.',
    'One keyword attempts, the other reacts.'),
  card(w6, 'with-open', 'Why open files with a with statement?',
    'The file is closed automatically when the block ends, even if an error occurs.',
    'Forgetting to close a file can lose buffered writes or hold a lock. with makes the cleanup impossible to forget.',
    'Something tidies up for you at the end of the block.'),
  card(w6, 'venv', 'What is a virtual environment for?',
    'It gives a project its own set of installed packages, so different projects can use different versions without clashing.',
    'Without one, upgrading a library for one project can break another.',
    'A separate box of packages for each project.'),
  card(w6, 'class-self', 'What is a class, and what is self?',
    'A class is a blueprint for objects that bundle data and methods. self is the instance a method is called on, passed automatically as the first parameter.',
    'my_dog.bark() runs Dog.bark with self set to my_dog, which is how each object keeps its own data.',
    'It is the first parameter of every instance method.'),
  card(w6, 'in-list-set', 'Why is checking x in a list slower than checking x in a set?',
    'A list is scanned item by item, which is O(n). A set uses hashing, which is O(1) on average.',
    'For a big collection you check often, the container you choose matters more than micro-tuning the loop.',
    'One looks at every item, the other jumps straight to a slot.'),

  // ---- Week 7: SQL ----
  card(w7, 'what-sql', 'What is SQL used for?',
    'Querying and changing data in a relational database, which stores data in tables of rows and columns.',
    'It is declarative: you describe the result you want and the database decides how to get it.',
    'You describe what you want, not how to find it.'),
  card(w7, 'select-where', 'What does SELECT name FROM users WHERE age > 30; do?',
    'It returns the name column for every row in users whose age is above 30.',
    'SELECT picks columns, FROM picks the table and WHERE filters the rows.',
    'Three parts: which columns, which table, which rows.'),
  card(w7, 'primary-key', 'What is a primary key?',
    'A column (or set of columns) whose value uniquely identifies each row in a table.',
    'It cannot be NULL or repeat, so other tables can point at a row without ambiguity.',
    'The one value that no two rows share.'),
  card(w7, 'foreign-key', 'What is a foreign key?',
    'A column that stores another table’s primary key, linking a row to a row elsewhere.',
    'An orders table holds a customer_id that points at a row in customers instead of copying the customer’s details.',
    'It refers to a row in a different table.'),
  card(w7, 'inner-join', 'What does an INNER JOIN return?',
    'Only the rows where the join condition matches in both tables.',
    'A customer with no orders does not appear in an inner join of customers and orders.',
    'Rows with no partner are left out.'),
  card(w7, 'left-join', 'How does a LEFT JOIN differ from an INNER JOIN?',
    'It keeps every row from the left table and fills the right table’s columns with NULL where nothing matches.',
    'It answers questions like “every customer, and their orders if they have any”.',
    'Nothing from the first table is dropped.'),
  card(w7, 'group-by', 'What does GROUP BY do, and which functions go with it?',
    'It collects rows sharing a value into groups so aggregates such as COUNT, SUM, AVG, MIN and MAX work per group.',
    'SELECT city, COUNT(*) FROM users GROUP BY city; gives one row per city.',
    'One result row per shared value.'),
  card(w7, 'where-having', 'What is the difference between WHERE and HAVING?',
    'WHERE filters rows before grouping. HAVING filters the groups after aggregation.',
    'You cannot use COUNT(*) in WHERE because the groups do not exist yet at that stage.',
    'One acts before the groups exist, the other after.'),
  card(w7, 'order-limit', 'How do you fetch the five newest posts?',
    'SELECT * FROM posts ORDER BY created DESC LIMIT 5;',
    'ORDER BY ... DESC puts the newest first and LIMIT keeps only the top rows.',
    'Sort first, then cut the list short.'),
  card(w7, 'normalisation', 'Why split data across several tables (normalisation)?',
    'So each fact is stored once, and an update cannot leave copies that disagree.',
    'If a customer’s address is in one row, changing it once fixes it everywhere.',
    'Store each fact in exactly one place.'),
  card(w7, 'sql-injection', 'How do you prevent SQL injection?',
    'Use parameterised queries (placeholders), so user input is treated as data and never as SQL.',
    'Building a query by pasting strings together lets input change the query’s structure. Placeholders keep them separate.',
    'Never build the query by joining strings with user input.'),
  card(w7, 'index', 'What does a database index do, and what does it cost?',
    'It speeds up lookups on a column, like a book’s index, but takes extra space and slows writes.',
    'Index the columns you search or join on, not every column.',
    'Faster reads, slower writes.'),
  card(w7, 'transaction', 'What is a transaction?',
    'A group of statements that succeed or fail together (commit or roll back), keeping the data consistent.',
    'Moving money means subtracting from one account and adding to another. A transaction stops one half happening alone.',
    'All of the steps happen, or none do.'),
  card(w7, 'is-null', 'How do you test for a missing value in SQL?',
    'With IS NULL. Writing = NULL never matches.',
    'NULL means unknown, and unknown is not equal to anything, not even another NULL.',
    'The comparison is a keyword, not an equals sign.'),

  // ---- Week 8: HTML, CSS and JavaScript ----
  card(w8, 'html-css-roles', 'What does HTML describe, and what does CSS describe?',
    'HTML describes the structure and content of a page. CSS describes how it looks.',
    'Keeping them apart means you can restyle a site without touching its content.',
    'One is the skeleton, the other is the clothing.'),
  card(w8, 'semantic-html', 'Why use elements like nav and main instead of plain divs?',
    'They tell browsers, search engines and screen readers what each part is, which helps accessibility and search.',
    'A div has no meaning; a nav says “this is navigation”, and assistive technology can jump straight to it.',
    'Names that carry meaning.'),
  card(w8, 'get-post', 'What does a form’s method choose between GET and POST?',
    'GET sends the data in the URL, which suits searches. POST sends it in the request body, which suits changes and private data.',
    'GET requests can be bookmarked and repeated safely. Passwords never belong in a URL.',
    'One puts the data in the address, the other in the body.'),
  card(w8, 'status-codes', 'What do HTTP status codes 200, 301, 403, 404 and 500 mean?',
    '200 OK, 301 moved permanently, 403 forbidden, 404 not found, 500 server error.',
    'The first digit is the family: 2xx success, 3xx redirect, 4xx the client’s mistake, 5xx the server’s.',
    'The first digit tells you whose fault it is.'),
  card(w8, 'css-selectors', 'Which CSS selectors target class “note” and id “top”?',
    '.note for the class and #top for the id.',
    'Many elements can share a class, but an id should be unique on the page.',
    'A dot for one and a hash for the other.'),
  card(w8, 'box-model', 'What are the layers of the CSS box model, from the inside out?',
    'Content, padding, border, then margin.',
    'Padding is space inside the border, margin is space outside it. box-sizing: border-box makes width include padding and border.',
    'It is like a picture: the photo, a mat, the frame, the gap on the wall.'),
  card(w8, 'flex-grid', 'When would you choose flexbox, and when grid?',
    'Flexbox lays items out along one axis, a row or a column. Grid controls rows and columns together.',
    'Use flexbox for a navigation bar and grid for a page layout.',
    'One dimension versus two.'),
  card(w8, 'media-query', 'What does a CSS media query do?',
    'It applies styles only when a condition holds, such as a minimum viewport width, so the layout adapts to the screen.',
    'Mobile-first CSS starts with the small layout and adds media queries for wider screens.',
    'Styles that apply only in certain situations.'),
  card(w8, 'dom', 'What is the DOM?',
    'The browser’s tree of objects that represents the page, which JavaScript can read and change.',
    'Changing the DOM changes what the user sees without reloading the page.',
    'The page as a tree the script can edit.'),
  card(w8, 'event-listener', 'How do you run JavaScript when a button is clicked?',
    'Attach an event listener: button.addEventListener("click", handler).',
    'The browser calls handler each time the event happens, so the code reacts instead of running once at load.',
    'You tell the element to listen for something.'),
  card(w8, 'strict-equality', 'What is the difference between == and === in JavaScript?',
    '== converts types before comparing. === compares value and type with no conversion. Prefer ===.',
    'With ==, 0 == "0" is true and 0 == "" is true, which surprises people. === avoids that.',
    'One of them quietly converts.'),
  card(w8, 'let-const', 'When do you use const, and when let?',
    'const for a binding that is never reassigned, let for one that is. Avoid var.',
    'const does not make an object immutable, only the binding: you can still change what an object contains.',
    'Choose by whether the name will point somewhere else later.'),
  card(w8, 'fetch', 'What does fetch() return, and how do you read the data?',
    'A promise. Await it, then read the body, for example await response.json().',
    'Network calls take time, and promises let the page keep working while it waits. Check response.ok, because fetch does not throw on a 404.',
    'It hands you something to wait on.'),
  card(w8, 'same-origin', 'What does the same-origin policy do?',
    'It stops a page’s scripts reading responses from a different origin unless that server allows it through CORS.',
    'Without it, any site you visit could read your email in another tab.',
    'One site’s scripts cannot freely read another site’s data.'),
  card(w8, 'xss-output', 'How do you avoid XSS when showing user input on a page?',
    'Escape or encode it, and set textContent rather than innerHTML, so it is treated as text and not markup.',
    'If input is inserted as HTML, an attacker’s script runs with your page’s permissions.',
    'Show it as text, never as markup.'),

  // ---- Week 9: Flask ----
  card(w9, 'flask-what', 'What is Flask?',
    'A lightweight Python web framework where you map URLs to Python functions that return responses.',
    'It is small on purpose: routing and templates are built in, and you add extensions for things like databases.',
    'A small Python tool for turning functions into web pages.'),
  card(w9, 'route', 'What does @app.route("/hello") do?',
    'It registers the function beneath it to handle requests to /hello.',
    'The decorator is the map from a URL to code. A different route means a different function.',
    'A label above a function that says where it lives.'),
  card(w9, 'jinja', 'What are Jinja templates for?',
    'Producing HTML with placeholders and logic ({{ }} and {% %}) filled from Python data, so layout stays separate from code.',
    'Flask turns on Jinja’s autoescaping for HTML templates, so a value is shown as text and injected markup does not run.',
    'HTML with gaps that Python fills in.'),
  card(w9, 'request-form', 'How do you read submitted form fields in Flask?',
    'request.form for POST fields, and request.args for query-string parameters.',
    'Treat everything in them as untrusted input and validate it.',
    'A request object holds what the browser sent.'),
  card(w9, 'method-check', 'Why does a Flask route often check request.method?',
    'So one URL can show a form on GET and process it on POST.',
    'The route accepts both methods, and the code branches on which one arrived.',
    'The same address behaves differently by how it was reached.'),
  card(w9, 'session', 'What is a session in a web app?',
    'Data remembered between requests for one browser. Flask signs it into a cookie by default, and extensions can keep it on the server.',
    'HTTP forgets each request, so the session is how the app knows you are still logged in.',
    'How a stateless protocol remembers you.'),
  card(w9, 'cookie', 'What is a cookie?',
    'A small piece of data the server asks the browser to store and send back with later requests.',
    'Mark session cookies HttpOnly, Secure and SameSite so scripts cannot read them and other sites cannot ride on them.',
    'The browser hands it back on the next visit.'),
  card(w9, 'password-hashing', 'How should a web app store passwords?',
    'As a salted hash from a slow algorithm such as bcrypt, scrypt or Argon2, never in plain text.',
    'If the database leaks, hashes cannot be reversed easily, and salts stop one guess cracking many accounts.',
    'Store something you can check but not undo.'),
  card(w9, 'csrf', 'What is CSRF, and how do you prevent it?',
    'An attack that makes a logged-in user’s browser submit a request they did not intend. Prevent it with per-form tokens and SameSite cookies.',
    'The browser attaches your cookies to the forged request, so the server needs a secret the attacker cannot know.',
    'A forged request that rides on your login.'),
  card(w9, 'secrets', 'Why keep API keys out of your source code?',
    'Anyone who can read the repository can use them. Keep them in environment variables or a secrets store.',
    'Keys committed to git stay in its history even after you delete the line, so rotate any that leak.',
    'Code gets shared; secrets should not.'),
  card(w9, 'post-redirect-get', 'Why redirect after handling a POST?',
    'So refreshing the page does not submit the form again. It is called post/redirect/get.',
    'After a successful POST, redirect(url_for("index")) sends the browser to a normal GET page.',
    'A refresh repeats the last request the browser made.'),
  card(w9, 'debug-off', 'Why must debug mode be off in production?',
    'The debugger can expose source code and let an attacker run commands on the server.',
    'Debug mode is for your laptop. Show users a plain error page and log the details privately.',
    'A convenience that is dangerous in public.'),
  card(w9, 'prod-server', 'Why not run Flask’s built-in development server in production?',
    'It is not built for load or security. Use a production server such as gunicorn, usually behind a reverse proxy.',
    'The dev server handles a few requests at a time and is meant only for local work.',
    'The development server is for development.'),
];

export const CS50_CARDS: Card[] = [...WEEKS_0_5, ...WEEKS_6_9];
