import type { Card } from './types';

/**
 * CS50 / intro CS, weeks 0–5. Every card is written from scratch: CS50's
 * materials are CC BY-NC-SA 4.0, so nothing here is copied from them. This is a
 * study aid for the same ideas, not a reproduction of the course; the course
 * itself is at https://cs50.harvard.edu/x/.
 */
const card = (domain: string, slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'original',
});

const w0 = 'cs50-w0';
const w1 = 'cs50-w1';
const w2 = 'cs50-w2';
const w3 = 'cs50-w3';
const w4 = 'cs50-w4';
const w5 = 'cs50-w5';

export const CS50_CARDS: Card[] = [
  // ---- Week 0: computational thinking and binary ----
  card(w0, 'bit', 'What is a bit?',
    'A single binary digit: 0 or 1. The smallest unit of information a computer stores.',
    'Physically it is a switch that is on or off — a voltage high or low, a charge present or not. Everything else, from text to video, is patterns of them.',
    'Think of the two positions of a light switch.'),
  card(w0, 'n-bits', 'How many different values can n bits represent?',
    '2ⁿ.',
    'Every extra bit doubles the count. Eight bits give 256 values (0–255), sixteen give 65,536.',
    'Each extra bit doubles how many patterns you can make.'),
  card(w0, 'binary-read', 'What is 1011 in binary, as a decimal number?',
    '11.',
    'Place values run 8, 4, 2, 1 from the left: 8 + 0 + 2 + 1 = 11. Each place is a power of two, just as decimal places are powers of ten.',
    'Place values from the right are 1, 2, 4, 8.'),
  card(w0, 'ascii', 'What is ASCII?',
    'A standard table that maps numbers to characters, so 65 is “A” and 97 is “a”.',
    'Text is numbers with an agreed meaning. ASCII covers 128 characters; Unicode extends the idea to every writing system, and UTF-8 encodes it so plain ASCII text is unchanged.',
    'A lookup table between numbers and letters; 65 is a capital letter.'),
  card(w0, 'algorithm', 'What is an algorithm?',
    'A precise, finite sequence of steps that solves a problem.',
    'Precise means a machine could follow it without judgement. The interesting question is never only “does it work” but “how does the work grow as the input does”.',
    'A recipe a machine could follow without any judgement.'),
  card(w0, 'abstraction', 'What does abstraction mean in programming?',
    'Hiding detail behind a name, so you can use something without knowing how it works.',
    'A function called sort lets you think “put these in order” rather than about comparisons and swaps. Good abstractions let one person hold a large program in their head.',
    'You call sort without thinking about swaps. What is being hidden?'),

  // ---- Week 1: C basics ----
  card(w1, 'stages', 'What are the four stages from C source code to a running program?',
    'Preprocessing, compiling, assembling, linking.',
    'Preprocessing handles lines starting with #. Compiling turns C into assembly, assembling turns that into machine code, and linking joins your code with library code such as printf.',
    'Four steps: the first handles lines starting with #, the last joins in library code.'),
  card(w1, 'include', 'What does #include <stdio.h> do?',
    'Tells the preprocessor to paste in the declarations for standard input and output, so the compiler knows what printf looks like.',
    'A declaration promises a function exists and says what it takes and returns. The definition itself arrives later, at the linking stage.',
    'Lines starting with # are handled before the compiler even starts.'),
  card(w1, 'int-division', 'What does 7 / 2 evaluate to in C when both are ints, and why?',
    '3. Integer division discards the fraction.',
    'The result has the type of the operands, and an int has no fractional part. Make one side a float (7 / 2.0) to get 3.5.',
    'Two ints in, an int out. Where does the .5 go?'),
  card(w1, 'assign-vs-equal', 'What is the difference between = and == in C?',
    '= assigns a value; == compares two values.',
    'Writing if (x = 5) assigns 5 to x and then tests it, which is always true. It compiles, which is why the mistake survives.',
    'One stores a value; the other asks a question.'),
  card(w1, 'float-precision', 'Why can a float not store 0.1 exactly?',
    'Floats store binary fractions, and 0.1 has no finite binary expansion, so it is rounded.',
    'It is the same reason 1/3 cannot be written exactly in decimal. Never compare floats with ==, and keep money in whole cents.',
    'Think of trying to write 1/3 exactly in decimal.'),
  card(w1, 'main-return', 'What does main returning 0 mean?',
    'By convention, success. Any other value tells the shell something went wrong.',
    'Scripts and other programs read that exit status (echo $? in a shell), which is how a chain of commands knows to stop.',
    'The shell reads it with echo $?. What would “no problems” be?'),
  card(w1, 'overflow', 'What is integer overflow?',
    'A result too large for its type. It wraps around for unsigned integers and is undefined behaviour for signed ones.',
    'A 32-bit signed int tops out at 2,147,483,647. Adding one more does not give a bigger number, and old bugs, including real disasters, came from assuming it would.',
    'Picture a car’s odometer rolling past 999999.'),

  // ---- Week 2: arrays and strings ----
  card(w2, 'array', 'What is an array in C?',
    'A block of memory holding elements of one type back to back, indexed from 0.',
    'Because the elements are contiguous, the address of element i is the start plus i times the element size. That is why indexing is instant.',
    'Boxes of one type side by side in memory. The first index is not 1.'),
  card(w2, 'string', 'What is a string in C?',
    'An array of chars ending with a zero byte, written \\0 and called NUL.',
    'There is no length stored; functions like strlen walk until they hit the NUL. Forgetting to leave room for it is the classic off-by-one.',
    'An array of chars, plus one special byte at the end.'),
  card(w2, 'argv', 'What do argc and argv[0] hold?',
    'argc is the number of command-line arguments including the program name; argv[0] is that program name as it was typed.',
    'Your first real argument is therefore argv[1], and argc is always at least 1.',
    'The program’s own name counts as an argument.'),
  card(w2, 'array-length', 'Why does a C function taking an array also need its length?',
    'The array decays to a pointer to its first element, and the length is not carried along.',
    'Inside the function, sizeof gives the size of a pointer, not of the array. So the caller must pass the length separately.',
    'What does an array turn into when you pass it to a function?'),
  card(w2, 'out-of-bounds', 'What happens if you write past the end of an array?',
    'Undefined behaviour: it may overwrite other data, crash, or appear to work.',
    'This is a buffer overflow, and it is the root of a huge class of security holes. C does not check bounds; you do.',
    'C never checks the index for you.'),
  card(w2, 'char-math', 'Why does \'a\' + 1 equal \'b\' in C?',
    'A char is a small integer (its ASCII code), so arithmetic on it works: 97 + 1 is 98, which is “b”.',
    'It is how a Caesar cipher works: shift the number, keep the alphabet in bounds with modulo.',
    'Under the hood, a char is just its ASCII number.'),

  // ---- Week 3: algorithms ----
  card(w3, 'linear-search', 'What is the worst-case running time of linear search?',
    'O(n): you may have to look at every element.',
    'It needs no ordering, which is its only virtue. Best case is Ω(1), when the first element matches.',
    'The unlucky case: the item is last, or not there at all.'),
  card(w3, 'binary-search', 'What does binary search require, and how fast is it?',
    'A sorted collection. It runs in O(log n).',
    'Each comparison discards half of what is left, so a billion items take about thirty steps. On unsorted data the halving is meaningless.',
    'Think of a phone book: open the middle, throw away half.'),
  card(w3, 'big-o', 'What do O, Ω and Θ describe?',
    'O is an upper bound, Ω a lower bound, and Θ a tight bound (both at once).',
    'People usually say O and mean “the worst case”. Saying an algorithm is O(n²) promises it is no worse than that, not that it is that bad.',
    'A ceiling, a floor, and both at once.'),
  card(w3, 'bubble-sort', 'What is bubble sort’s worst-case time, and when is its best case O(n)?',
    'O(n²) worst case. It is O(n) on already-sorted input, if it stops when a pass makes no swaps.',
    'It repeatedly swaps adjacent out-of-order pairs. The early exit is the difference between a lucky and an unlucky input.',
    'It swaps neighbours. What if a whole pass makes no swaps?'),
  card(w3, 'selection-sort', 'Why is selection sort Θ(n²) even on sorted input?',
    'It always scans the whole unsorted remainder to find the minimum, whatever the input looks like.',
    'It does no early exit, so best and worst case match. It does, however, do at most n swaps.',
    'It hunts for the smallest remaining item every time, whatever the input.'),
  card(w3, 'merge-sort', 'How fast is merge sort, and what does it cost?',
    'O(n log n) time, using O(n) extra memory.',
    'It splits the list, sorts each half recursively and merges them. The log n comes from the halving; the n from each merge touching every element.',
    'Halve, sort, merge. The merging needs somewhere to put things.'),
  card(w3, 'recursion', 'What two parts does every correct recursive function need?',
    'A base case that stops, and a recursive step that moves toward it.',
    'Without a base case the calls pile up on the stack until it overflows. Factorial: n! is 1 when n is 1 (base), otherwise n × (n−1)!.',
    'One part stops the calls; the other gets closer to stopping.'),

  // ---- Week 4: memory ----
  card(w4, 'pointer', 'What is a pointer?',
    'A variable that holds a memory address.',
    'It lets you refer to data without copying it, and to give a function access to the caller’s variable.',
    'Not the data itself, but where to find it.'),
  card(w4, 'address-deref', 'What do & and * do with a pointer?',
    '&x gives the address of x. *p follows the pointer p to the value it points at (dereferencing).',
    'In a declaration, * means “pointer to”; in an expression, it means “the thing at”. The same symbol, two jobs.',
    'One symbol asks “where is it?”, the other asks “what is there?”.'),
  card(w4, 'multi-declare', 'What does int *a, b; declare?',
    'a is a pointer to int; b is a plain int.',
    'The * binds to the name, not the type. To get two pointers you write int *a, *b;.',
    'Does the * belong to the type, or to the name?'),
  card(w4, 'malloc', 'What does malloc(n) return, and what must you do with it?',
    'A pointer to n bytes on the heap, or NULL if it failed. Check for NULL, and free the memory when done.',
    'Heap memory outlives the function that asked for it, which is the point and the danger: nothing frees it for you.',
    'Memory that outlives the function. It can fail, and it never cleans itself up.'),
  card(w4, 'leak', 'What is a memory leak?',
    'Heap memory that was allocated and never freed, and can no longer be reached.',
    'A short program hardly notices. A long-running one grows until the machine runs out. A tool like Valgrind finds them.',
    'Borrowed memory that is never given back.'),
  card(w4, 'stack-heap', 'What lives on the stack, and what lives on the heap?',
    'The stack holds function calls: locals, parameters and return addresses, freed automatically on return. The heap holds memory you allocate with malloc and free yourself.',
    'They grow toward each other. Too many nested calls exhaust the stack; too many allocations exhaust the heap.',
    'One is cleaned up automatically on return; the other is yours to manage.'),
  card(w4, 'segfault', 'What is a segmentation fault?',
    'The program touched memory it is not allowed to, such as dereferencing NULL or reading far past an array.',
    'The operating system stops the program. It is a kindness: the alternative is silently reading or corrupting someone else’s data.',
    'The operating system stops you for touching memory that isn’t yours.'),
  card(w4, 'dangling', 'Why is returning a pointer to a local variable a bug?',
    'The local lives on the stack and is gone when the function returns, so the pointer refers to memory that is no longer yours (a dangling pointer).',
    'It may seem to work for a while, which is worse than crashing. Return a value, or allocate on the heap.',
    'Where do local variables live, and what happens to them on return?'),
  card(w4, 'double-free', 'What is a double free, and a habit that prevents it?',
    'Calling free on the same allocation twice, which is undefined behaviour. Setting the pointer to NULL after freeing helps, since free(NULL) is harmless.',
    'It can corrupt the allocator’s bookkeeping, and attackers know how to use that.',
    'Giving back the same memory twice. What could you set the pointer to afterwards?'),

  // ---- Week 5: data structures ----
  card(w5, 'array-vs-list', 'Compare an array and a linked list.',
    'An array gives O(1) access by index but costly insertion in the middle. A linked list gives cheap insertion at a known position but O(n) access, and spends memory on pointers.',
    'The right choice depends on what you do most. If you mostly look things up by position, use an array.',
    'Boxes in a row versus a chain of nodes. Which is quick to index, which to insert into?'),
  card(w5, 'node', 'What does a singly linked list node contain?',
    'A value and a pointer to the next node. The last node’s pointer is NULL.',
    'You hold the list as a pointer to the first node, so losing that pointer loses the whole list.',
    'Two fields: the data, and the way to the next one.'),
  card(w5, 'stack-queue', 'What is the difference between a stack and a queue?',
    'A stack is last in, first out (LIFO); a queue is first in, first out (FIFO).',
    'Undo history is a stack; a print queue is a queue. Both can be built from an array or a linked list.',
    'A pile of plates versus a queue at a checkout.'),
  card(w5, 'hash-table', 'How does a hash table find a value quickly?',
    'A hash function turns the key into an array index, so lookup goes straight to the right bucket: O(1) on average.',
    'The trade is space and a good hash function. A poor one sends many keys to the same bucket and the speed disappears.',
    'A function turns the key straight into an array index.'),
  card(w5, 'collision', 'What is a hash collision, and two ways to handle it?',
    'Two keys mapping to the same index. Chaining keeps a list in each bucket; linear probing uses the next free slot.',
    'Collisions cannot be avoided in general (more keys than buckets, eventually), only managed.',
    'Two keys want the same slot: share it, or look for the next free one.'),
  card(w5, 'hash-worst', 'What is a hash table lookup’s worst case?',
    'O(n), when every key lands in the same bucket.',
    'This is why average and worst case are given separately, and why hash quality matters for anything an attacker can feed.',
    'What if the hash function sends every key to one bucket?'),
  card(w5, 'bst', 'What property defines a binary search tree, and why does balance matter?',
    'For every node, everything in the left subtree is smaller and everything in the right is larger. Balanced, search is O(log n); degenerate into a line, it is O(n).',
    'Inserting already-sorted data into a naive tree makes a line. Self-balancing trees exist to prevent it.',
    'Smaller goes one way, larger the other. What happens if you insert data that is already sorted?'),
  card(w5, 'trie', 'What is a trie, and what is its lookup cost?',
    'A tree in which each edge is a character, so a path from the root spells a key. Lookup takes time proportional to the key’s length, however many keys are stored.',
    'It is a good fit for dictionaries and autocomplete, at the cost of memory for all those pointers.',
    'Each step down the tree is one letter of the word.'),
];
