import type { Card } from './types';

/**
 * One card for every part of every diagram beyond the motherboard, so each part
 * explains itself when tapped. Written from the 220-1201 objectives as an
 * outline; every word is original.
 */
const card = (domain: string, slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'objective-outline',
  tags: ['diagram'],
});

const hw = 'a1-d3';
const net = 'a1-d2';
const mob = 'a1-d1';

export const RAM_CARDS: Card[] = [
  card(hw, 'ram-dimm', 'What is a desktop DIMM, and how many pins does each DDR generation have?',
    'A full-size memory module. DDR3 has 240 pins, and DDR4 and DDR5 both have 288, so only the notch tells those two apart.',
    'Voltage falls each generation: DDR3 1.5 V, DDR4 1.2 V, DDR5 1.1 V. DDR5 also moves power management onto the module itself.',
    'The full-size stick that goes in the long slots beside the CPU.'),
  card(hw, 'ram-sodimm', 'What is a SO-DIMM, and how many pins does each DDR generation have?',
    'A small-outline module about half the length of a DIMM, used in laptops, mini PCs and all-in-ones. DDR3 has 204 pins, DDR4 260 and DDR5 262.',
    'The shorter size is the giveaway. It sits at an angle in its slot and is pressed flat until the clips hold it.',
    'The short stick from a laptop.'),
  card(hw, 'ram-notch', 'What is the notch on a memory module for?',
    'It is a key. Its position differs for each DDR generation and for DIMM versus SO-DIMM, so a module cannot be fitted into a slot it does not match.',
    'Never force a module. If it will not seat, it is the wrong type, and forcing it can break the slot or the board.',
    'A small gap along the bottom edge that does a job.'),
  card(hw, 'ram-contacts', 'What are the gold contacts along the bottom of a memory module, and how should you treat them?',
    'The edge connector that carries data and power. Hold the module by its edges and never touch the contacts.',
    'Skin oil and static can damage or corrode them, and a dull contact can be cleaned with a lint-free cloth and isopropyl alcohol.',
    'The strip that goes into the slot.'),
  card(hw, 'ram-chips', 'What are the black chips on a memory module?',
    'The DRAM chips that store the data. Modules can have chips on one side or both, and some have a heat spreader over them.',
    'More chips do not always mean more capacity: chip density matters too. An ECC module has one extra chip per side.',
    'Where the memory itself lives.'),
];

export const STORAGE_CARDS: Card[] = [
  card(hw, 'sto-hdd35', 'Where is a 3.5-inch hard drive normally used, and what limits its speed?',
    'In desktops and servers. It has spinning platters and moving heads, so it is slower and more shock-sensitive than an SSD, but cheaper per gigabyte.',
    'Speed is measured in RPM (5,400 or 7,200 for most, 10,000 or 15,000 in servers), and it has to wait for the platter to rotate under the head.',
    'It has moving parts inside.'),
  card(hw, 'sto-ssd25', 'What interface does a typical 2.5-inch SSD use, and what is its ceiling?',
    'SATA III, which tops out around 550 MB/s (6 Gbps).',
    'The interface, not the flash, is the bottleneck, which is why NVMe drives are so much faster. The 2.5-inch size lets it replace a laptop hard drive directly.',
    'It uses the same connectors as a hard drive.'),
  card(hw, 'sto-m2-sata', 'Which key does an M.2 SATA SSD use, and how fast is it?',
    'A B+M key (two notches), and it runs at SATA speed.',
    'Keys stop a module fitting a slot that cannot drive it. A two-notch module fits both key types of slot, but only works if the slot is wired for SATA.',
    'Two notches, so it fits two kinds of slot.'),
  card(hw, 'sto-m2-nvme', 'Which key does an M.2 NVMe SSD use, and what does it run over?',
    'An M key (a single notch), over PCIe, usually four lanes.',
    'NVMe was designed for flash and talks to the CPU over PCIe, so it reaches several gigabytes per second where SATA stops near half a gigabyte.',
    'One notch, on the side with the wider bus.'),
  card(hw, 'sto-sata-data', 'How many pins does a SATA data connector have, and how many drives does one cable serve?',
    'Seven pins, and one drive per cable.',
    'Unlike the old IDE ribbon that shared a cable between two drives, each SATA drive has its own point-to-point cable to a port.',
    'It is the narrower of the two SATA connectors.'),
  card(hw, 'sto-sata-power', 'How many pins does a SATA power connector have, and which voltages does it carry?',
    '15 pins, carrying +3.3 V, +5 V and +12 V.',
    'The extra pins provide the three voltages and grounds, and the wide L-shaped plug only fits one way.',
    'It is the wider of the two SATA connectors.'),
];

export const PSU_CARDS: Card[] = [
  card(hw, 'pc-body', 'What does a PC power supply do, and why should you never open one?',
    'It converts mains AC into the low-voltage DC the PC needs. Its capacitors can hold a dangerous charge even when unplugged, so it is replaced, not repaired.',
    'The wattage rating and an efficiency mark such as 80 PLUS tell you how much it can deliver and how much it wastes as heat.',
    'Alternating current goes in, something else comes out.'),
  card(hw, 'pc-atx24', 'Which connector brings main power to the motherboard, and how many pins does it have?',
    'The 24-pin ATX connector, a 20+4 arrangement on many supplies.',
    'It carries +3.3 V, +5 V and +12 V plus control signals such as power-good and power-on.',
    'It is the widest connector on the supply.'),
  card(hw, 'pc-eps8', 'What is the 8-pin (4+4) EPS connector on a power supply for?',
    'Power for the CPU, on +12 V.',
    'The split 4+4 lets it fit boards that have only a 4-pin CPU header as well.',
    'It goes to the top of the board, near the processor.'),
  card(hw, 'pc-pcie', 'What do PCIe power connectors supply, and how much do 6-pin and 8-pin plugs provide?',
    'Extra power for graphics cards: 75 W from a 6-pin and 150 W from an 8-pin (6+2), on top of the 75 W the slot gives.',
    'A card that draws more than the slot can supply needs these leads. The 6+2 plug splits so it fits either socket.',
    'Cards hungrier than the slot needs a lead of their own.'),
  card(hw, 'pc-sata', 'Which power connector feeds SATA drives?',
    'The flat, L-shaped 15-pin SATA power connector.',
    'The L shape only lets it plug in one way, and it carries three voltages for the drive’s motor and logic.',
    'The shape stops you plugging it in backwards.'),
  card(hw, 'pc-molex', 'What is a Molex connector, and what do its wire colours mean?',
    'A 4-pin peripheral connector for older drives, fans and accessories. Yellow is +12 V, red is +5 V, and the two black wires are ground.',
    'Colours are consistent across power supplies: yellow +12 V, red +5 V, orange +3.3 V, black ground. Use a native SATA lead for a SATA drive where you can.',
    'A chunky four-pin plug from before SATA.'),
];

export const PRINTER_CARDS: Card[] = [
  card(hw, 'lp-tray', 'What is the paper tray’s job in a laser printer?',
    'It holds the stack of paper, and the pickup roller takes one sheet at a time from it.',
    'Overfilling or mixing paper types in a tray is a common cause of jams and misfeeds.',
    'It is where the paper waits.'),
  card(hw, 'lp-pickup', 'What does the pickup roller do, and what happens when it wears?',
    'It grabs one sheet from the tray. A worn roller causes misfeeds, several sheets at once, and jams.',
    'Rollers are rubber, so they harden and slip with age. They are replaced with the maintenance kit.',
    'It is the first moving part the paper meets.'),
  card(hw, 'lp-toner', 'What does a laser printer’s toner cartridge contain?',
    'Toner powder, a fine mix of plastic and pigment, and in many models the drum and developing parts as well.',
    'When the cartridge includes the drum, replacing it also renews the parts that wear out, at the cost of a pricier cartridge.',
    'The consumable that runs out first.'),
  card(hw, 'lp-charge', 'What does the primary charge roller do?',
    'It gives the drum a uniform negative charge, ready to be written on.',
    'This is the charging step: an evenly charged drum is the blank canvas the laser draws on.',
    'It prepares the drum before the laser touches it.'),
  card(hw, 'lp-drum', 'What is the photosensitive drum?',
    'A light-sensitive cylinder where the laser draws the image as a pattern of charge and where toner clings before it is moved to paper.',
    'A scratched or worn drum leaves repeating marks or ghost images down the page.',
    'A cylinder that changes when light hits it.'),
  card(hw, 'lp-laser', 'What does the laser do in a laser printer?',
    'It sweeps across the charged drum through a spinning mirror, discharging the spots where toner should stick, which writes the image.',
    'This is the exposing step. Toner is attracted to the spots the laser touched.',
    'It writes the page onto the drum with light.'),
  card(hw, 'lp-transfer', 'What does the transfer roller do?',
    'It charges the paper so the toner is pulled off the drum onto it.',
    'This is the transferring step. At this point the toner is only sitting on the paper, so it smears until it is fused.',
    'It pulls the toner across to the paper.'),
  card(hw, 'lp-fuser', 'What does the fuser do, and what does it use?',
    'It melts toner into the paper using heat and pressure from a heated roller and a pressure roller.',
    'It is why pages come out warm, and why toner that rubs off points at a failed fuser.',
    'The last thing to touch the toner before the page comes out.'),
  card(hw, 'lp-clean', 'What clears the drum of leftover toner after each page?',
    'A cleaning blade scrapes the remaining toner off, so the drum is ready for the next page.',
    'This is the cleaning step. A worn blade leaves streaks or repeated marks.',
    'A scraper that resets the drum.'),
  card(hw, 'lp-output', 'What is the last stop for the page, and why is it often warm?',
    'The output tray. The page is warm because it has just passed through the fuser.',
    'A page that comes out cold or damp usually never went through the fuser properly.',
    'The end of the paper’s journey.'),
];

export const OSI_CARDS: Card[] = [
  card(net, 'osi-7', 'What does layer 7, the application layer, provide?',
    'The interface between network services and software. Protocols such as HTTP, FTP, SMTP and DNS work here.',
    'It is not the application itself, but the network services the application uses. Mnemonic from the top: All People Seem To Need Data Processing.',
    'Where a user’s programs meet the network.'),
  card(net, 'osi-6', 'What does layer 6, the presentation layer, do?',
    'It translates, encrypts and compresses data so both ends understand it, for example character encoding and encryption such as TLS.',
    'Think of it as a translator: data is put into a shape the receiving application can read.',
    'Formatting and encryption.'),
  card(net, 'osi-5', 'What does layer 5, the session layer, do?',
    'It opens, manages and closes conversations between two applications.',
    'It keeps track of who is talking to whom and can resume a conversation after an interruption.',
    'A dialogue with a beginning and an end.'),
  card(net, 'osi-4', 'What does layer 4, the transport layer, do?',
    'It delivers data end to end between hosts using ports. TCP is reliable and ordered, UDP is fast and unacknowledged. The unit is a segment.',
    'Ports live here, which is why a firewall rule that names a port is a layer 4 rule.',
    'Ports and end-to-end delivery.'),
  card(net, 'osi-3', 'What does layer 3, the network layer, do?',
    'It provides logical addressing and routing between networks using IP addresses. The unit is a packet, and routers work here.',
    'A router reads the destination IP address and decides the next hop.',
    'Where IP addresses and routers belong.'),
  card(net, 'osi-2', 'What does layer 2, the data link layer, do?',
    'It moves frames between devices on one network using MAC addresses. Switches and network cards work here.',
    'It also detects errors on the link. Bridges and switches forward by MAC address.',
    'Frames, MAC addresses and switches.'),
  card(net, 'osi-1', 'What does layer 1, the physical layer, do?',
    'It sends raw bits over the medium: cables, connectors, radio waves and voltages. Hubs, repeaters and cabling live here.',
    'A cable fault, a bent pin or a failed Wi-Fi radio is a layer 1 problem, so check it first. Mnemonic from the bottom: Please Do Not Throw Sausage Pizza Away.',
    'The cables and signals themselves.'),
];

export const TOPOLOGY_CARDS: Card[] = [
  card(net, 'topo-star', 'How does a star topology connect devices, and what is its weak point?',
    'Every device connects to a central switch. If the switch fails, everything attached to it goes down, but one broken cable affects only one device.',
    'It is the standard for modern wired LANs, because faults are easy to isolate and devices can be added without disturbing others.',
    'One central device, many spokes.'),
  card(net, 'topo-bus', 'What is a bus topology?',
    'Devices share one backbone cable with terminators at each end. A break or a missing terminator affects everyone. It is a legacy design.',
    'Every device hears every transmission, so collisions were common. Early coaxial Ethernet used it.',
    'A single shared cable with something on each end.'),
  card(net, 'topo-ring', 'What is a ring topology?',
    'Each device connects to two neighbours, forming a loop, and data circulates in one direction, often controlled by a token. A single break can stop it unless there is a second ring.',
    'Token Ring and FDDI used it. A dual ring lets traffic wrap around a break.',
    'A loop with no start or end.'),
  card(net, 'topo-mesh', 'What is the difference between a full mesh and a partial mesh?',
    'In a full mesh every node links to every other node, and in a partial mesh only some do. Both give redundancy at the cost of many links, and a full mesh of n nodes needs n(n−1)/2.',
    'The internet backbone is a partial mesh, because linking every router to every other one would be unaffordable.',
    'Every node, or only some of them, joined to many others.'),
  card(net, 'topo-hybrid', 'What is a hybrid topology?',
    'A combination of two or more topologies, such as several stars joined by a backbone. Most real networks are hybrid.',
    'A company network might be a star in each office with a partial mesh between sites.',
    'A mix of the basic shapes.'),
  card(net, 'topo-p2p', 'What is a point-to-point connection?',
    'A dedicated link between exactly two endpoints, such as a leased line or a wireless bridge between two buildings.',
    'With only two ends there is no sharing, so it is simple and predictable, but it does not scale to many sites on its own.',
    'A link with exactly two ends.'),
];

export const PORT_CARDS: Card[] = [
  card(hw, 'pt-usba', 'Which USB connector is the familiar flat rectangle, and is it reversible?',
    'USB Type-A. It only fits one way up.',
    'The Type-A plug goes into a host such as a PC or charger. Many devices use a different connector on their own end.',
    'The one you always try the wrong way first.'),
  card(hw, 'pt-usbc', 'What makes USB-C different?',
    'It is a small, oval, reversible connector that can carry USB 2, 3 or 4 data, video (DisplayPort Alt Mode), Thunderbolt and USB Power Delivery charging.',
    'The connector shape does not promise the features: one USB-C port may charge and drive a monitor while another only does slow data.',
    'A small oval plug with no wrong way up.'),
  card(hw, 'pt-hdmi', 'What does an HDMI port carry, and where is it common?',
    'Digital video and audio over one cable. It is common on TVs, monitors, consoles and laptops.',
    'Older DVI and VGA carried no sound, so HDMI simplified home theatre setups.',
    'One cable for picture and sound.'),
  card(hw, 'pt-dp', 'How can you spot a DisplayPort connector, and what can it do that HDMI cannot?',
    'One corner of the plug is cut off. It can drive several monitors from one port by daisy-chaining (Multi-Stream Transport) on displays that support it.',
    'It is the usual connector on PC monitors and graphics cards.',
    'Look for the odd corner.'),
  card(hw, 'pt-rj45', 'What is the connector on the end of an Ethernet cable?',
    'RJ45, technically 8P8C: eight pins with a clip.',
    'The clip can snap off, which is why a plug that will not stay in is a common cause of drops.',
    'The eight-pin plug with a latch.'),
  card(hw, 'pt-rj11', 'How does an RJ11 differ from an RJ45?',
    'An RJ11 is narrower, with fewer contacts, and is used for telephones and DSL. An RJ45 has eight.',
    'An RJ11 plug will fit into an RJ45 socket but does not make proper contact, so check the label.',
    'The smaller one from the telephone.'),
  card(hw, 'pt-vga', 'What kind of signal does a 15-pin blue VGA connector carry?',
    'Analog video only, with no audio.',
    'It is a legacy connector. The signal loses sharpness on long cables and at high resolutions.',
    'A blue, three-row connector held in by thumbscrews.'),
  card(hw, 'pt-dvi', 'What do DVI-D, DVI-A and DVI-I mean?',
    'DVI-D is digital only, DVI-A is analog only, and DVI-I carries both.',
    'Check the pins on the plug, because a DVI-D cable will not fit a DVI-A-only socket.',
    'The last letter says which kind of signal.'),
  card(hw, 'pt-audio', 'What do the colours on 3.5 mm audio jacks usually mean?',
    'Green is line-out (speakers), pink is microphone, and blue is line-in.',
    'The colours are a convention for PC sound cards, so a headset plugged into the pink jack records rather than plays.',
    'Three colours for output, microphone and input.'),
];

export const CABLE_CARDS: Card[] = [
  card(hw, 'cb-utp', 'What is UTP cable?',
    'Unshielded twisted pair: pairs of wires twisted together to cancel interference, with no metal shield. It is the common Ethernet cable.',
    'The twists cancel out interference from neighbouring pairs, and skipping the shield keeps the cable cheap and flexible.',
    'The everyday Ethernet cable without a metal wrap.'),
  card(hw, 'cb-stp', 'When would you choose shielded twisted pair (STP)?',
    'Where electrical interference is high, such as near motors or heavy power cables. The shield must be grounded correctly.',
    'A shield that is not grounded can act like an antenna and make things worse.',
    'A cable with a metal wrap for noisy places.'),
  card(hw, 'cb-coax', 'Where is coaxial cable used today, and which connector does it use?',
    'Cable TV and broadband modems, with an F-type connector.',
    'A centre conductor sits inside insulation and a metal shield, which protects the signal from interference.',
    'The screw-on cable from the wall to a cable modem.'),
  card(hw, 'cb-sm', 'What are the traits of single-mode fiber?',
    'A very thin core carrying a single light path, usually from a laser, for long distances of many kilometres.',
    'The narrow core keeps the light from spreading, which allows very long runs but needs more expensive optics.',
    'Thin core, long reach.'),
  card(hw, 'cb-mm', 'What are the traits of multimode fiber?',
    'A wider core carrying many light paths, usually from an LED, cheaper and used for shorter runs within a building or campus.',
    'The many paths spread out over distance, so range is limited compared with single-mode.',
    'Wider core, shorter runs.'),
  card(hw, 'cb-lc', 'What is an LC fiber connector?',
    'A small square connector with a latch, common on modern switches and SFP modules, often used in duplex pairs.',
    'LC stands for Lucent Connector. It is small enough to fit many ports in a switch.',
    'The small latching connector on modern network gear.'),
  card(hw, 'cb-sc', 'What is an SC fiber connector?',
    'A square, push-pull connector that snaps into place. It is common in older and telecom equipment.',
    'It is sometimes remembered as the square connector, and it clicks in without twisting.',
    'It pushes in and pulls out like a plug.'),
  card(hw, 'cb-st', 'What is an ST fiber connector?',
    'A round connector with a twist-lock bayonet fitting, common in older installations.',
    'You push it in and twist a quarter turn to lock it, which is why it feels different from the square types.',
    'Push and twist.'),
  card(hw, 'cb-t568', 'What is the T568B pin order for an RJ45 plug?',
    '1 white-orange, 2 orange, 3 white-green, 4 blue, 5 white-blue, 6 green, 7 white-brown, 8 brown.',
    'T568A swaps the green and orange pairs. A straight-through cable uses the same standard at both ends, and a crossover uses A at one end and B at the other.',
    'Orange comes first, then green splits the blue.'),
];

export const COOLING_CARDS: Card[] = [
  card(hw, 'cool-ihs', 'What is the integrated heat spreader (IHS) on a CPU?',
    'The metal lid over the CPU die that spreads heat out to the cooler.',
    'It also protects the fragile die. Thermal paste goes between the IHS and the cooler’s base.',
    'The metal lid on top of the processor.'),
  card(hw, 'cool-paste', 'Where does thermal paste go, and how much do you use?',
    'A thin layer on the centre of the heat spreader, about the size of a pea, which the cooler’s pressure spreads out.',
    'Too much can spill and insulate, and too little leaves gaps. Old dried paste is replaced whenever the cooler comes off.',
    'A small blob in the middle, spread by pressure.'),
  card(hw, 'cool-heatsink', 'What does a CPU heatsink do?',
    'It draws heat out of the CPU into metal fins with a large surface area, where moving air carries it away.',
    'More fin area means more heat can be shed, which is why coolers are tall.',
    'A block of metal with lots of fins.'),
  card(hw, 'cool-pipes', 'What are heat pipes on a cooler?',
    'Sealed copper tubes with a little liquid that evaporates at the hot end and condenses at the cool end, moving heat quickly to the fins.',
    'They move heat far better than solid copper of the same size.',
    'Sealed tubes that carry heat up to the fins.'),
  card(hw, 'cool-fan', 'How is a CPU cooler’s fan powered and controlled?',
    'From the 4-pin CPU_FAN header, where PWM lets the board vary its speed with temperature.',
    'Airflow should follow the case’s front-to-back path, so the fan is not fighting the case fans.',
    'It plugs into a specific header next to the socket.'),
  card(hw, 'cool-mount', 'What is the backplate or retention bracket on a CPU cooler for?',
    'It holds the cooler down on the CPU with even pressure. A loose or uneven mount causes overheating.',
    'Tighten opposite screws a little at a time, like the wheel nuts on a car.',
    'It clamps the cooler evenly to the board.'),
  card(hw, 'cool-pump', 'What does the pump block on an all-in-one liquid cooler do?',
    'It sits on the CPU, picks up heat and circulates the liquid around the loop.',
    'A pump that fails leaves the CPU with no cooling, so a rising temperature with a silent pump is a warning.',
    'The block on top of the CPU that moves the liquid.'),
  card(hw, 'cool-radiator', 'What is the radiator on a liquid cooler for?',
    'It passes the heat from the liquid to the air, with fans pushing air through its fins.',
    'It is usually mounted on the case’s front, top or rear so it can move air in the right direction.',
    'The finned part where the liquid gives up its heat.'),
];

export const LAPTOP_CARDS: Card[] = [
  card(mob, 'lt-battery', 'What is usually the largest component in a laptop’s base, and how is it fitted?',
    'The battery. Many are internal and screwed in, so disconnect it before other repairs, while removable ones use a latch.',
    'Working with the battery connected risks shorting something, so it comes out or is unplugged first.',
    'The biggest block in the base.'),
  card(mob, 'lt-board', 'What is special about a laptop motherboard?',
    'It is a single compact board with the CPU, chipset and ports, and in many models the CPU and RAM are soldered on.',
    'Soldered parts cannot be upgraded, so what you buy is what you keep.',
    'Everything is packed onto one small board.'),
  card(mob, 'lt-ram', 'What RAM do most laptops use, and how is it fitted?',
    'SO-DIMM, inserted at an angle and pressed down until the clips hold it.',
    'It is shorter than a desktop DIMM. Some thin models solder the memory to the board instead.',
    'It slides in at a slant and clicks flat.'),
  card(mob, 'lt-storage', 'What storage do modern laptops usually use?',
    'An M.2 SSD, or a 2.5-inch SATA SSD in older or larger models.',
    'M.2 drives screw flat to the board. An SSD is faster, quieter and more shock-resistant than a spinning drive.',
    'A small flat module screwed to the board.'),
  card(mob, 'lt-wifi', 'Where is a laptop’s Wi-Fi card, and what does it connect to?',
    'An M.2 card, usually keyed A/E, on the motherboard, with two thin antenna wires that run up into the lid.',
    'Reconnect the antenna wires when you reassemble the laptop, or the signal will be very weak.',
    'A small card with two thin wires going up the hinge.'),
  card(mob, 'lt-fan', 'What cools a laptop’s CPU?',
    'A small fan pushing air over a copper heatsink joined to the CPU by heat pipes. Dust in the vents makes it overheat.',
    'Cleaning the vents and replacing dried thermal paste are the usual fixes for a hot laptop.',
    'A tiny fan beside a copper heat spreader.'),
  card(mob, 'lt-keyboard', 'How does a laptop keyboard connect to the board?',
    'By a thin flat ribbon cable that latches into a ZIF connector.',
    'You flip up the small latch, slide the ribbon out, and reverse the steps to reconnect. Forcing it tears the ribbon.',
    'A flat ribbon that clips into a socket.'),
  card(mob, 'lt-display', 'How does a laptop’s display connect to the board?',
    'By a thin cable that runs through the hinge, usually eDP on newer models or LVDS on older ones.',
    'A flickering screen when you move the lid points at a worn cable in the hinge.',
    'It passes through the hinge.'),
  card(mob, 'lt-cmos', 'What is the CMOS battery in a laptop?',
    'A small coin cell on a short cable that keeps the clock and firmware settings when the main battery and power are gone.',
    'A laptop that loses its time and settings after being unplugged and left needs this replaced.',
    'A tiny cell that remembers the time.'),
];

export const DIAGRAM_CARDS: Card[] = [
  ...RAM_CARDS, ...STORAGE_CARDS, ...PSU_CARDS, ...PRINTER_CARDS, ...OSI_CARDS, ...TOPOLOGY_CARDS,
  ...PORT_CARDS, ...CABLE_CARDS, ...COOLING_CARDS, ...LAPTOP_CARDS,
];
