import type { Card } from './types';

/**
 * A+ Core 1 (220-1201), short-answer cards. One fact per card, so each is fair
 * game for flashcards, review and the typing stages. Topics follow the official
 * objectives as an outline; every word here is original. Verify against
 * CompTIA's objectives PDF before relying on coverage.
 */
const make = (domain: string) => (slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-t-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'objective-outline',
});

const mobile = make('a1-d1');
const net = make('a1-d2');
const hw = make('a1-d3');
const cloud = make('a1-d4');
const fix = make('a1-d5');

export const SHORT_A1_CARDS: Card[] = [
  // ---- 1.0 Mobile devices
  mobile('ips', 'Which LCD panel type is known for wide viewing angles and good colour?', 'IPS.',
    'In-plane switching panels keep their colour when viewed from the side, which is why they suit phones, tablets and photo work.',
    'Its name describes how the crystals switch, in the same plane.'),
  mobile('tn', 'Which LCD panel type is cheap and fast but has narrow viewing angles?', 'TN.',
    'Twisted nematic panels respond quickly, which gamers like, but colours shift when you look from above or below.',
    'The oldest and cheapest of the three common panel types.'),
  mobile('nfc', 'Which short-range wireless technology is used for tap-to-pay?', 'NFC.',
    'Near-field communication only works within a few centimetres, which is part of why it is considered safe for payments and pairing.',
    'Near-field communication.'),
  mobile('li-ion', 'Which battery chemistry do most phones and laptops use?', 'Lithium-ion.',
    'It holds a lot of energy for its weight and has no memory effect, but it swells with age and must never be punctured.',
    'It is named after the lightest metal.'),
  mobile('imei', 'What number uniquely identifies a phone’s hardware, whatever SIM is in it?', 'The IMEI.',
    'Carriers can use it to block a stolen handset. You can usually see it by dialling *#06#.',
    'International Mobile Equipment Identity.'),
  mobile('sim', 'What does a SIM card identify its owner to?', 'The carrier.',
    'It stores the subscriber’s identity so the network knows whose plan to use, and it can move to another phone.',
    'The company that provides your mobile service.'),
  mobile('esim', 'What is a SIM that is built into the device, with no physical card, called?', 'An eSIM.',
    'You activate a plan by scanning a code instead of swapping a card, and one device can hold several profiles.',
    'The e is for embedded.'),
  mobile('digitizer', 'Which touchscreen layer turns a touch into an electrical signal?', 'The digitizer.',
    'If the picture is fine but touch does not work, the digitizer is the first suspect, not the display.',
    'It converts touches into digital data.'),
  mobile('accelerometer', 'Which sensor detects a phone’s tilt and movement, so the screen can rotate?', 'The accelerometer.',
    'It measures acceleration along three axes, including gravity, which is how the phone knows which way is down.',
    'It measures how fast speed changes.'),
  mobile('gyroscope', 'Which sensor measures a phone’s rotation, helping with games and camera stabilisation?', 'The gyroscope.',
    'It tracks turning movement and works with the accelerometer to give smooth motion tracking.',
    'It spins, in spirit.'),
  mobile('gps', 'Which satellite system lets a phone work out where it is?', 'GPS.',
    'The phone listens to several satellites and calculates its position from the time each signal took to arrive.',
    'Global Positioning System.'),
  mobile('usb-c', 'Which reversible connector is now the common charging and data port?', 'USB-C.',
    'It plugs in either way up and can carry power, data and video, depending on the cable and the device.',
    'It has no wrong way round.'),
  mobile('lightning', 'Which proprietary connector did older iPhones use for charging?', 'Lightning.',
    'Apple’s 8-pin reversible connector was replaced by USB-C on newer models.',
    'Named after a weather event.'),
  mobile('airplane', 'Which mode switches off all of a phone’s radios at once?', 'Airplane mode.',
    'It disables cellular, Wi-Fi and Bluetooth in one tap, though you can turn Wi-Fi or Bluetooth back on afterwards.',
    'Used when flying.'),
  mobile('inverter', 'Which laptop part powers the backlight of an older LCD, and can leave the screen dim when it fails?', 'The inverter.',
    'Older CCFL backlights need high voltage from an inverter. Newer LED panels do not use one.',
    'It changes DC into AC for the lamp.'),
  mobile('fn-key', 'Which laptop key combines with the function keys to change brightness or toggle Wi-Fi?', 'Fn.',
    'Laptops have too few keys, so the Fn key switches the top row between its normal job and these extras.',
    'Short for function.'),

  // ---- 2.0 Networking: one port per card
  net('port-ssh', 'Which port does SSH use?', '22.',
    'Secure Shell gives an encrypted remote command line and replaces the plain-text Telnet.',
    'Telnet is the next number up.'),
  net('port-telnet', 'Which port does Telnet use?', '23.',
    'Telnet sends everything, passwords included, as plain text, so it is avoided on any real network.',
    'One more than SSH.'),
  net('port-smtp', 'Which port does SMTP use to send mail between servers?', '25.',
    'Simple Mail Transfer Protocol pushes mail along. Clients usually submit mail on 587 instead.',
    'Between 24 and 26.'),
  net('port-dns', 'Which port does DNS use?', '53.',
    'Name lookups use UDP on this port, and TCP for large answers and zone transfers.',
    'A little over fifty.'),
  net('port-dhcp-server', 'Which port does a DHCP server listen on?', '67.',
    'Clients use 68. The pair is UDP, and it works before the client has an address at all.',
    'The client uses the next number.'),
  net('port-http', 'Which port does HTTP use?', '80.',
    'Unencrypted web traffic. Anything sensitive should be on 443 instead.',
    'The default for a plain web address.'),
  net('port-pop3', 'Which port does POP3 use?', '110.',
    'Post Office Protocol downloads mail to one device and usually removes it from the server.',
    'Just over a hundred.'),
  net('port-ntp', 'Which port does NTP use?', '123.',
    'Network Time Protocol keeps clocks in step, which matters for logs and Kerberos.',
    'One, two, three.'),
  net('port-imap', 'Which port does IMAP use?', '143.',
    'IMAP keeps mail on the server so several devices see the same folders.',
    'POP3 is 110, this is a little higher.'),
  net('port-snmp', 'Which port does SNMP use?', '161.',
    'Simple Network Management Protocol lets a tool poll switches, routers and printers for status.',
    'The one-sixty-something.'),
  net('port-ldap', 'Which port does LDAP use?', '389.',
    'The Lightweight Directory Access Protocol looks things up in a directory such as Active Directory.',
    'A bit under four hundred.'),
  net('port-https', 'Which port does HTTPS use?', '443.',
    'Web traffic wrapped in TLS, which is what the padlock means.',
    'Four hundred and forty-something.'),
  net('port-smb', 'Which port does SMB file sharing use?', '445.',
    'Windows shares and printers travel over it, so it must never be exposed to the internet.',
    'Just above HTTPS.'),
  net('port-rdp', 'Which port does Remote Desktop use?', '3389.',
    'Exposing it to the internet invites brute-force attacks, so put it behind a VPN or gateway.',
    'Three thousand and then some.'),
  net('tcp', 'Which transport protocol guarantees delivery and order?', 'TCP.',
    'It sets up a connection, numbers every segment and re-sends anything lost. Web pages, email and file transfer use it.',
    'The reliable one.'),
  net('udp', 'Which transport protocol trades reliability for speed, as streaming and VoIP do?', 'UDP.',
    'There is no handshake and no re-sending, so late packets are simply skipped.',
    'The fast, no-promises one.'),
  net('dns-job', 'What does DNS translate names into?', 'IP addresses.',
    'People remember names such as example.com. Computers connect using the numbers, so DNS looks one up for the other.',
    'The numbers a network needs.'),
  net('dhcp-job', 'Which service hands out IP addresses automatically?', 'DHCP.',
    'It gives each client an address, mask, gateway and DNS server, so nobody types them in.',
    'Dynamic Host Configuration Protocol.'),
  net('nat', 'What lets many private addresses share one public address?', 'NAT.',
    'Network address translation rewrites addresses at the router and keeps a table of who asked for what.',
    'Network address ... what?'),
  net('vlan', 'What splits one physical switch into separate logical networks?', 'A VLAN.',
    'Ports are tagged into groups that cannot talk to each other without a router, which keeps traffic apart.',
    'A virtual LAN.'),
  net('slash24', 'How many usable host addresses does a /24 network have?', '254.',
    'There are 256 addresses, minus the network address and the broadcast address.',
    'Two fewer than a full byte’s worth.'),
  net('loopback', 'What is the IPv4 loopback address?', '127.0.0.1.',
    'Traffic sent to it never leaves the machine, so it is the quickest check that the network stack works.',
    'Starts with a hundred and twenty-seven.'),
  net('mac-bits', 'How many bits long is a MAC address?', '48 bits.',
    'It is written as six pairs of hex digits and identifies a network card on the local network.',
    'Six bytes.'),
  net('ipv4-bits', 'How many bits long is an IPv4 address?', '32 bits.',
    'Four bytes, which allows only about four billion addresses and is why IPv6 exists.',
    'Four bytes.'),
  net('ipv6-bits', 'How many bits long is an IPv6 address?', '128 bits.',
    'Sixteen bytes, written as eight groups of hex digits, so addresses are effectively unlimited.',
    'Four times as long as IPv4.'),
  net('access-point', 'Which device connects wireless clients to a wired network?', 'An access point.',
    'It is a bridge between Wi-Fi and Ethernet. Home routers contain one, and offices add several.',
    'The point you reach for wireless access.'),
  net('modem', 'Which device converts the ISP’s signal into something your router can use?', 'A modem.',
    'It modulates and demodulates the line signal, whether cable, DSL or fibre.',
    'Short for modulator-demodulator.'),
  net('ssid', 'What is the name a Wi-Fi network broadcasts called?', 'The SSID.',
    'It is the label you pick in the list of networks. Hiding it is not real security.',
    'Service set identifier.'),
  net('ethernet-length', 'What is the maximum length of one twisted-pair Ethernet cable run?', '100 m.',
    'Beyond it the signal weakens, so longer runs need a switch or repeater in between.',
    'About the length of a football pitch.'),
  net('ping', 'Which utility sends echo requests to test whether a host is reachable?', 'ping.',
    'It uses ICMP and reports how long each reply takes, so it also shows latency and packet loss.',
    'It is named after a sonar sound.'),

  // ---- 3.0 Hardware
  hw('sata3', 'What is SATA III’s maximum speed?', '6 Gbps.',
    'That is about 600 MB/s in practice, which is why SATA SSDs all feel about the same and NVMe is faster.',
    'Six of something per second.'),
  hw('nvme-bus', 'Which bus do NVMe drives use to talk to the CPU?', 'PCIe.',
    'Skipping the SATA controller is what lets NVMe SSDs reach several gigabytes a second.',
    'The same bus as graphics cards.'),
  hw('raid0', 'Which RAID level stripes data across drives with no redundancy?', 'RAID 0.',
    'It is fast, but if any one drive fails the whole array is lost.',
    'The number is also how much redundancy it has.'),
  hw('raid1', 'Which RAID level mirrors data across two drives?', 'RAID 1.',
    'Each drive holds an identical copy, so one can fail with no loss, at the cost of half the capacity.',
    'One copy of everything, twice.'),
  hw('raid5', 'Which RAID level stripes with parity and needs at least three drives?', 'RAID 5.',
    'Parity is spread across the drives, so any one can fail and be rebuilt, and one drive’s worth of space is used for it.',
    'It is the one with distributed parity.'),
  hw('raid10', 'Which RAID level combines mirroring and striping?', 'RAID 10.',
    'It is fast and tolerates a failure in each mirror, but it needs at least four drives and gives half the capacity.',
    'A mirror of stripes, or a stripe of mirrors.'),
  hw('ssd-name', 'What does SSD stand for?', 'Solid state drive.',
    'It stores data in flash chips with no moving parts, so it is silent, fast and shock-resistant.',
    'No spinning platters.'),
  hw('psu-name', 'What does PSU stand for?', 'Power supply unit.',
    'It turns mains AC into the low DC voltages a PC runs on, and every part draws from it.',
    'It feeds the whole machine.'),
  hw('ram-name', 'What does RAM stand for?', 'Random access memory.',
    'Any location can be read as quickly as any other, and the contents vanish when the power goes.',
    'The computer’s short-term working space.'),
  hw('gpu-name', 'What does GPU stand for?', 'Graphics processing unit.',
    'It is built for doing many simple calculations in parallel, first for drawing pictures and now for AI too.',
    'It draws the picture.'),
  hw('uefi', 'Which firmware has largely replaced the legacy BIOS?', 'UEFI.',
    'It boots from GPT disks, supports Secure Boot and has a graphical menu.',
    'Unified Extensible Firmware Interface.'),
  hw('pata', 'Which old ribbon-cable drive interface did SATA replace?', 'PATA.',
    'Parallel ATA, also called IDE, used a wide 40-pin ribbon and jumpers to set master and slave.',
    'The parallel one.'),
  hw('multimeter', 'Which tool measures the voltages coming out of a PSU?', 'A multimeter.',
    'You probe each pin of the connector and compare the reading with the expected rail, such as 3.3, 5 or 12 volts.',
    'It measures many things.'),
  hw('psu-tester', 'Which small tool quickly shows whether a PSU is giving the right voltages?', 'A PSU tester.',
    'You plug the 24-pin connector in and read lights or a screen, with no probing needed.',
    'It is named after what it tests.'),
  hw('compressed-air', 'What is used to blow dust out of a PC safely?', 'Compressed air.',
    'Hold fans still so they do not overspin, and keep the can upright so it does not spray liquid.',
    'A can of it.'),
  hw('dot-matrix', 'Which printer strikes a ribbon with pins and is good for multipart forms?', 'A dot matrix printer.',
    'It is an impact printer, so the carbon copies underneath are printed too, which laser and inkjet cannot do.',
    'It makes the characters out of tiny dots.'),
  hw('cpu-clock', 'Which unit measures how fast a CPU’s clock ticks?', 'Hertz.',
    'Modern CPUs run at billions of cycles a second, so you see gigahertz on the box.',
    'Named after a German physicist.'),

  // ---- 4.0 Virtualization and cloud computing
  cloud('hypervisor', 'What software creates and runs virtual machines?', 'A hypervisor.',
    'It shares the host’s CPU, memory and disk among the guests and keeps them isolated from each other.',
    'It supervises the guests.'),
  cloud('type1', 'Which hypervisor type runs directly on the hardware?', 'Type 1.',
    'A bare-metal hypervisor is what servers use, because there is no general-purpose OS between it and the machine.',
    'The one without a host operating system.'),
  cloud('type2', 'Which hypervisor type runs as an application on top of an ordinary operating system?', 'Type 2.',
    'VirtualBox and VMware Workstation are examples, handy on a laptop for testing.',
    'The hosted one.'),
  cloud('iaas', 'Which cloud model rents out virtual servers, storage and networks?', 'IaaS.',
    'Infrastructure as a service leaves you to manage the OS and everything above it.',
    'The model closest to the hardware.'),
  cloud('paas', 'Which cloud model gives developers a platform to run code without managing servers?', 'PaaS.',
    'Platform as a service takes care of the OS and runtime so you only deploy your app.',
    'The middle one of the three.'),
  cloud('saas', 'Which cloud model delivers finished applications over the internet?', 'SaaS.',
    'Software as a service, such as webmail or an online office suite, is used through a browser and needs no installing.',
    'You just use the app.'),
  cloud('public-cloud', 'Which cloud model is shared by many customers and run by a provider?', 'Public cloud.',
    'You rent capacity from a large provider and share the underlying hardware with other tenants.',
    'Open to anyone who pays.'),
  cloud('private-cloud', 'Which cloud model is built for one organisation alone?', 'Private cloud.',
    'It gives more control and isolation, but the organisation bears the cost of running it.',
    'Reserved for a single owner.'),
  cloud('hybrid-cloud', 'Which cloud model mixes private and public clouds?', 'Hybrid cloud.',
    'Sensitive workloads can stay in the private part while the public part absorbs peaks in demand.',
    'A blend of two.'),
  cloud('elasticity', 'What lets cloud resources grow and shrink automatically with demand?', 'Elasticity.',
    'It avoids paying for idle servers and keeps a busy service from falling over.',
    'Like a rubber band.'),
  cloud('measured', 'Which cloud trait means you pay for what you actually use?', 'Measured service.',
    'Usage is metered, so a bill follows consumption, much like electricity.',
    'It is metered.'),
  cloud('vdi', 'What does VDI stand for?', 'Virtual desktop infrastructure.',
    'Users see a desktop that actually runs on a server, so any device can be a thin window onto it.',
    'The desktop is virtual.'),
  cloud('container', 'What packages an app with its libraries and shares the host’s kernel?', 'A container.',
    'It starts in seconds and uses far less than a full VM, because it does not carry its own operating system.',
    'Like a shipping box for software.'),
  cloud('docker', 'Which tool made containers popular with developers?', 'Docker.',
    'It builds and runs container images, so an app behaves the same on a laptop and on a server.',
    'Its logo is a whale carrying boxes.'),
  cloud('sandbox', 'What is an isolated environment for testing risky software called?', 'A sandbox.',
    'Whatever happens inside cannot reach the real system, so malware analysis and updates can be tried safely.',
    'Where children play without breaking anything.'),
  cloud('virt-bios', 'What must be switched on in firmware for virtual machines to run well?', 'Hardware virtualization.',
    'It is called VT-x on Intel and AMD-V on AMD. If it is off, a hypervisor may refuse to start or run slowly.',
    'A CPU feature, often off by default.'),
  cloud('on-prem', 'What do you call IT that runs in your own building instead of in the cloud?', 'On-premises.',
    'You buy, host and maintain the hardware yourself, with full control and full responsibility.',
    'At your own premises.'),

  // ---- 5.0 Hardware and network troubleshooting
  fix('step-1', 'What is the first step of the CompTIA troubleshooting methodology?', 'Identify the problem.',
    'Question the user, find out what changed, and gather information before touching anything.',
    'Understand what is going on.'),
  fix('step-2', 'Which step follows identifying the problem?', 'Establish a theory of probable cause.',
    'Start with the obvious and question it. A cable that is out of its socket is likelier than a failed CPU.',
    'Make a guess, an educated one.'),
  fix('step-3', 'Which step follows establishing a theory?', 'Test the theory.',
    'If it holds up, you can move on. If not, you go back and form another one, or escalate.',
    'Prove or disprove it.'),
  fix('step-4', 'Which step follows a confirmed theory?', 'Establish a plan of action.',
    'You decide how to fix it, and what else the fix could affect, before you do it.',
    'Decide how you will fix it.'),
  fix('step-5', 'Which step follows implementing the solution?', 'Verify full system functionality.',
    'Check that the original problem is gone and that nothing else broke. Add preventive measures where you can.',
    'Make sure everything still works.'),
  fix('step-6', 'What is the last step of the troubleshooting methodology?', 'Document the findings.',
    'Record the symptoms, the cause and the fix, so the next person solves it faster.',
    'Write it down.'),
  fix('one-beep', 'What does a single short beep at start-up usually mean?', 'The self-test passed.',
    'Many PCs give one short beep after the power-on self-test succeeds. Repeated patterns mean a fault, and the board’s manual decodes them.',
    'It is the good news beep.'),
  fix('cable-tester', 'Which tool checks an Ethernet cable end to end for faults?', 'A cable tester.',
    'It sends a signal down each wire and shows breaks, shorts and crossed pairs.',
    'It tests cables.'),
  fix('toner-probe', 'Which tool finds the far end of a cable by following its tone?', 'A toner probe.',
    'A tone generator on one end and a probe at the other lets you trace a cable through walls and bundles.',
    'You listen for a sound.'),
  fix('loopback-plug', 'Which plug tests a network port by sending its signal straight back?', 'A loopback plug.',
    'If the port passes the test with the plug in, the fault is in the cabling or beyond, not the card.',
    'It loops the signal back.'),
  fix('apipa', 'What does APIPA stand for?', 'Automatic Private IP Addressing.',
    'Windows gives itself an address in 169.254.0.0/16 when no DHCP server answers, a sign that DHCP is unreachable.',
    'It starts with Automatic.'),
  fix('renew-ip', 'Which two ipconfig switches release and renew a DHCP address?', '/release and /renew.',
    'Run them in an elevated prompt to request a fresh lease, a quick fix for an address conflict.',
    'Give it up, then ask again.'),
  fix('overheat', 'A PC shuts down under load and is full of dust. What do you do first?', 'Clean the dust out.',
    'Clogged heatsinks and fans stop heat leaving the CPU, which then shuts the PC off to protect itself.',
    'Remove what is clogging the air flow.'),
  fix('no-power', 'A PC shows no sign of life at all. What is the first thing to check?', 'The power cable.',
    'Check the cable, the outlet and the PSU switch before you replace anything.',
    'The cheapest, simplest part.'),
];
