import type { Card } from './types';

/**
 * A+ Core 2 (220-1202), short-answer cards. One fact per card, so each is fair
 * game for flashcards, review and the typing stages. Topics follow the official
 * objectives as an outline; every word here is original. Verify against
 * CompTIA's objectives PDF before relying on coverage.
 */
const make = (domain: string) => (slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-t-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'objective-outline',
});

const os = make('a2-d1');
const sec = make('a2-d2');
const soft = make('a2-d3');
const ops = make('a2-d4');

export const SHORT_A2_CARDS: Card[] = [
  // ---- 1.0 Operating systems
  os('flushdns', 'Which command clears the DNS resolver cache in Windows?', 'ipconfig /flushdns.',
    'A stale cached answer can send you to an old address. Flushing makes the PC ask the DNS server afresh.',
    'It is an ipconfig switch.'),
  os('dir', 'Which command lists the files in a folder at the Windows command prompt?', 'dir.',
    'Add /a to include hidden files, or /s to include subfolders.',
    'It shows what the folder holds.'),
  os('cd', 'Which command changes the current folder at a command prompt?', 'cd.',
    'cd .. goes up one level, and cd \\ goes to the root of the drive.',
    'Change something that starts with a d.'),
  os('cls', 'Which command clears the Windows command prompt screen?', 'cls.',
    'It only tidies the display. Nothing is deleted.',
    'Clear the screen, abbreviated.'),
  os('shutdown', 'Which command shuts down or restarts a Windows PC from the command line?', 'shutdown.',
    'shutdown /r restarts, /s shuts down and /t sets a delay in seconds.',
    'The command is simply what you want done.'),
  os('regedit', 'Which command opens the Registry Editor?', 'regedit.',
    'Back up the registry or make a restore point first, because a wrong edit can stop Windows booting.',
    'Registry, then edit, squashed together.'),
  os('devmgmt', 'Which command opens Device Manager?', 'devmgmt.msc.',
    'Use it to update, roll back, disable or uninstall a driver, and to spot devices with a warning icon.',
    'It ends in the extension that all management consoles share.'),
  os('diskmgmt', 'Which command opens Disk Management?', 'diskmgmt.msc.',
    'You can initialise, partition, format and assign letters to drives there.',
    'Disk, then management, then the console extension.'),
  os('services-msc', 'Which command opens the Services console?', 'services.msc.',
    'You can start, stop and set the startup type of background services, such as Windows Update.',
    'The console is named after what it controls.'),
  os('eventvwr', 'Which command opens Event Viewer?', 'eventvwr.msc.',
    'It shows the Application, Security and System logs, where you find the real cause of a crash.',
    'Event, then viewer, with the vowels removed.'),
  os('msinfo32', 'Which command opens System Information, with a summary of hardware and drivers?', 'msinfo32.',
    'It lists the BIOS version, installed memory and loaded drivers in one place.',
    'Info about the system, with a number.'),
  os('taskmgr-keys', 'Which keyboard shortcut opens Task Manager directly?', 'Ctrl+Shift+Esc.',
    'It skips the security screen that Ctrl+Alt+Del shows first.',
    'Three keys, ending with the escape key.'),
  os('ls', 'Which Linux command lists the files in a folder?', 'ls.',
    'ls -l gives a long listing with permissions and ownership, and -a includes hidden files.',
    'Two letters, the first is for listing.'),
  os('cat', 'Which Linux command prints a file’s contents to the screen?', 'cat.',
    'The name comes from concatenate, because it can join several files together.',
    'An animal with a short name.'),
  os('cp', 'Which Linux command copies a file?', 'cp.',
    'cp source destination makes a duplicate and leaves the original where it is.',
    'Two letters for copy.'),
  os('mv', 'Which Linux command moves or renames a file?', 'mv.',
    'Moving and renaming are the same thing to Linux: the file simply gets a new path.',
    'Two letters for move.'),
  os('rm', 'Which Linux command deletes a file?', 'rm.',
    'There is no recycle bin, so double-check before using it, and be very careful with -r.',
    'Two letters for remove.'),
  os('mkdir', 'Which Linux command makes a new folder?', 'mkdir.',
    'Add -p to create the missing parent folders as well.',
    'Make and directory, joined up.'),
  os('whoami', 'Which command shows which user you are logged in as?', 'whoami.',
    'It works on Linux and Windows, and is handy to check whether you are running as an administrator.',
    'A question, written as one word.'),
  os('sudo', 'Which Linux command runs another command with administrator rights?', 'sudo.',
    'It asks for your password and logs what you run, which is safer than staying logged in as root.',
    'Superuser do.'),
  os('top', 'Which Linux command shows running processes and their resource use live?', 'top.',
    'Press q to leave it. htop is a friendlier version if it is installed.',
    'It lists the biggest users first.'),
  os('time-machine', 'Which macOS feature backs up the whole Mac to an external drive?', 'Time Machine.',
    'It keeps hourly, daily and weekly copies, so you can go back and find an older version of a file.',
    'It lets you go back in time.'),
  os('spotlight', 'Which macOS feature searches files, apps and the web from one box?', 'Spotlight.',
    'You open it with Command and Space.',
    'It shines a light on whatever you type.'),
  os('mission-control', 'Which macOS feature shows all open windows and virtual desktops?', 'Mission Control.',
    'It is the way to manage Spaces, which are macOS’s virtual desktops.',
    'It sounds like a space programme.'),
  os('keychain', 'Which macOS feature stores passwords and syncs them between Apple devices?', 'Keychain.',
    'It holds passwords, certificates and secure notes under your login.',
    'A ring for keys.'),
  os('filevault', 'Which macOS feature encrypts the startup disk?', 'FileVault.',
    'Without the password or recovery key the contents are unreadable if the Mac is lost.',
    'A vault for files.'),

  // ---- 2.0 Security
  sec('authn', 'What is verifying who someone is called?', 'Authentication.',
    'A password, a code or a fingerprint answers "are you who you say you are?". Authorization comes after.',
    'It starts with authen.'),
  sec('authz', 'What is deciding what an identified person may do called?', 'Authorization.',
    'After you are authenticated, permissions say which files and actions are yours.',
    'It follows authentication.'),
  sec('accounting', 'What is keeping a record of what users did called, in AAA?', 'Accounting.',
    'Logs of who logged in, what they ran and for how long are used for audits and billing.',
    'The third A.'),
  sec('factor-know', 'What kind of authentication factor is a password?', 'Something you know.',
    'It lives in your head, which is also why it can be guessed or stolen.',
    'Knowledge.'),
  sec('factor-have', 'What kind of authentication factor is a smart card or phone?', 'Something you have.',
    'A thief needs the physical item, not just a leaked secret.',
    'Possession.'),
  sec('factor-are', 'What kind of authentication factor is a fingerprint?', 'Something you are.',
    'Biometrics use your body, so they cannot be forgotten, but they also cannot be changed if copied.',
    'Inherence.'),
  sec('mfa', 'What does MFA stand for?', 'Multifactor authentication.',
    'Using two or more different kinds of factor means a stolen password alone is not enough.',
    'More than one proof.'),
  sec('wpa3', 'Which Wi-Fi security protocol is the current standard?', 'WPA3.',
    'It replaces the weaker pre-shared key handshake and gives stronger protection against password guessing.',
    'The newest of the WPA family.'),
  sec('wep', 'Which old Wi-Fi security protocol is broken and should never be used?', 'WEP.',
    'It can be cracked in minutes, so anything still using it must be upgraded.',
    'Wired Equivalent Privacy, which it wasn’t.'),
  sec('aes', 'Which strong encryption algorithm does WPA2 use?', 'AES.',
    'The Advanced Encryption Standard is also used for disk encryption and many VPNs.',
    'Advanced Encryption Standard.'),
  sec('ransomware', 'Which malware locks your files and demands payment?', 'Ransomware.',
    'Offline backups are the real defence, because paying does not guarantee the files come back.',
    'It holds your files for a ransom.'),
  sec('worm', 'Which malware spreads by itself across a network with no user action?', 'A worm.',
    'It exploits a weakness to copy itself from machine to machine, so it can saturate a network quickly.',
    'It crawls from host to host.'),
  sec('trojan', 'Which malware pretends to be a legitimate program?', 'A Trojan.',
    'It relies on you running it, then does something else behind your back. It does not replicate by itself.',
    'Named after a wooden horse.'),
  sec('keylogger', 'Which malware records everything you type?', 'A keylogger.',
    'It can capture passwords and card numbers. An on-screen keyboard or a password manager helps against it.',
    'It logs keys.'),
  sec('phishing', 'What is it called when an email tricks you into giving up credentials?', 'Phishing.',
    'It often impersonates a bank or boss. Check the sender, hover over links and report it.',
    'It sounds like fishing, but with a ph.'),
  sec('tailgating', 'What is it called when someone follows you through a secure door without badging in?', 'Tailgating.',
    'Access control vestibules and a polite challenge help stop it.',
    'Driving too close behind.'),
  sec('shoulder-surf', 'What is watching someone enter a password over their shoulder called?', 'Shoulder surfing.',
    'Privacy screens and awareness in public places help prevent it.',
    'It happens from just behind the person.'),
  sec('evil-twin', 'What is a rogue Wi-Fi access point that imitates a real one called?', 'An evil twin.',
    'Victims join it thinking it is the real network, and the attacker watches their traffic.',
    'It looks identical but is not.'),
  sec('vpn', 'What does a VPN create between your device and a network?', 'An encrypted tunnel.',
    'Traffic inside it cannot be read on the way, which is what makes public Wi-Fi safer.',
    'A private passage.'),
  sec('least-privilege', 'Which principle gives each user only the access they need?', 'Least privilege.',
    'Limiting rights reduces what a stolen account or a mistake can do.',
    'As little as will do.'),
  sec('bitlocker', 'Which Windows feature encrypts a whole drive?', 'BitLocker.',
    'It usually keeps its key in the TPM and asks for a recovery key if the hardware changes.',
    'It locks the bits.'),
  sec('uac', 'Which Windows feature asks permission before an action that needs administrator rights?', 'User Account Control.',
    'The dim prompt stops software quietly changing the system without you knowing.',
    'It controls what accounts may do.'),
  sec('tpm', 'Which chip on the motherboard stores encryption keys securely?', 'The TPM.',
    'Trusted Platform Module. BitLocker and Windows Hello use it so keys never sit in ordinary memory.',
    'Trusted Platform Module.'),
  sec('gdpr', 'Which European regulation protects personal data?', 'GDPR.',
    'It gives people rights over their data and sets rules, with large fines, on how organisations handle it.',
    'General Data Protection Regulation.'),
  sec('hipaa', 'Which US law protects health information?', 'HIPAA.',
    'Anyone handling patient records must keep them secure and private.',
    'It protects patients, in America.'),
  sec('pci-dss', 'Which standard protects payment card data?', 'PCI DSS.',
    'It sets security rules for anyone who stores, processes or sends card numbers.',
    'Payment Card Industry Data Security Standard.'),
  sec('encryption', 'What is scrambling data so only the holder of a key can read it called?', 'Encryption.',
    'It protects data at rest on a disk and data in transit over a network.',
    'The opposite of decryption.'),

  // ---- 3.0 Software troubleshooting
  soft('safe-mode', 'Which Windows mode starts with only the essential drivers and services?', 'Safe Mode.',
    'If a problem goes away there, the cause is a driver, a service or a start-up program, not Windows itself.',
    'The cautious way to start.'),
  soft('stop-error', 'What is a Windows blue screen officially called?', 'A stop error.',
    'It halts Windows to avoid damage, and the stop code tells you what to search for.',
    'Windows stops everything.'),
  soft('sfc', 'Which command scans and repairs protected Windows system files?', 'sfc /scannow.',
    'Run it from an elevated prompt. If it cannot fix everything, DISM comes next.',
    'System File Checker, plus a switch.'),
  soft('chkdsk', 'Which command checks a disk for errors?', 'chkdsk.',
    'With /f it fixes errors and with /r it also looks for bad sectors and recovers what it can.',
    'Check, then disk.'),
  soft('bootrec', 'Which recovery tool repairs the Windows boot configuration?', 'bootrec.',
    'It is run from the recovery environment, with switches such as /fixmbr, /fixboot and /rebuildbcd.',
    'Boot, then record, squashed.'),
  soft('winre', 'What do you boot into to repair Windows when it will not start?', 'The recovery environment.',
    'It offers startup repair, system restore, a command prompt and a way to reset the PC.',
    'The place where Windows repairs itself.'),
  soft('system-restore', 'Which Windows tool rolls system files and settings back to an earlier point?', 'System Restore.',
    'It does not touch your own documents, but it can undo a bad driver or program install.',
    'A restore point is its raw material.'),
  soft('rollback-driver', 'Which Device Manager option reverts a faulty driver update?', 'Roll Back Driver.',
    'It is on the driver tab of the device’s properties and is greyed out if there is no earlier version.',
    'Go back to the previous one.'),
  soft('padlock', 'What does the padlock beside a web address indicate?', 'An encrypted connection.',
    'It does not prove a site is trustworthy, only that traffic to it cannot be read on the way.',
    'It shows the link is protected.'),
  soft('factory-reset', 'What is returning a phone to its original settings, with all data erased, called?', 'A factory reset.',
    'It is the last step for a phone that is badly infected or unresponsive, so back up first.',
    'As it came out of the box.'),
  soft('backup-first', 'What should you do before a factory reset?', 'Back up the data.',
    'A reset erases everything, so you need a copy of photos, contacts and files first.',
    'Make a copy before you wipe.'),
  soft('event-viewer', 'Which Windows tool shows a timeline of crashes, warnings and errors?', 'Event Viewer.',
    'Look at the System and Application logs around the time of the problem for an error code to search for.',
    'It views events.'),

  // ---- 4.0 Operational procedures
  ops('sop', 'What does SOP stand for?', 'Standard operating procedure.',
    'A written set of steps so that a task is done the same way every time, whoever does it.',
    'Documented steps for routine work.'),
  ops('sla', 'What does SLA stand for?', 'Service level agreement.',
    'It sets what a provider promises, such as a response time of four hours, and what happens if they miss it.',
    'A promise about levels of service.'),
  ops('aup', 'What does AUP stand for?', 'Acceptable use policy.',
    'It tells staff what they may and may not do on company systems, and is usually signed on joining.',
    'The rules of what is okay.'),
  ops('cab', 'What does CAB stand for in change management?', 'Change advisory board.',
    'A group that reviews and approves significant changes before they go ahead.',
    'A board that gives advice on changes.'),
  ops('rfc', 'What is a formal proposal to change a system called?', 'A request for change.',
    'It states what will change, why, the risk and how to undo it, so reviewers can decide.',
    'You are asking for permission.'),
  ops('sds', 'What does SDS stand for on a chemical’s paperwork?', 'Safety data sheet.',
    'It explains how to handle, store and dispose of a chemical, such as toner, and what to do if it spills.',
    'Data about safety.'),
  ops('ppe', 'What does PPE stand for?', 'Personal protective equipment.',
    'Gloves, goggles and a mask protect you from toner, dust and broken glass.',
    'What you wear to stay safe.'),
  ops('esd', 'What does ESD stand for?', 'Electrostatic discharge.',
    'A static shock you cannot even feel can destroy a chip, so ground yourself before touching components.',
    'A spark of static.'),
  ops('wrist-strap', 'What do you wear to stop static damaging components?', 'An antistatic wrist strap.',
    'It connects you to the case or another ground, so no charge can build up.',
    'It goes round your wrist.'),
  ops('ups', 'Which device keeps equipment running on battery during a power cut?', 'A UPS.',
    'An uninterruptible power supply gives you minutes to save work and shut down cleanly.',
    'Uninterruptible.'),
  ops('surge', 'Which device protects equipment from voltage spikes?', 'A surge protector.',
    'It diverts the extra voltage but has no battery, so it will not keep a PC running in a power cut.',
    'It protects against surges.'),
  ops('drp', 'What is the plan for restoring IT after a major disaster called?', 'A disaster recovery plan.',
    'It lists which systems come back first, who does what and how data is restored from backups.',
    'The plan for after the worst happens.'),
  ops('byod', 'What does BYOD stand for?', 'Bring your own device.',
    'Staff use personal phones and laptops for work, which needs a policy and usually device management.',
    'Staff bring their own.'),
  ops('mdm', 'What does MDM stand for?', 'Mobile device management.',
    'It lets IT enforce a passcode, push apps and wipe a lost phone remotely.',
    'It manages phones and tablets.'),
  ops('drm', 'What does DRM stand for?', 'Digital rights management.',
    'It limits how purchased media can be copied or used, to protect the owner’s rights.',
    'It manages rights over digital content.'),
  ops('eula', 'What does EULA stand for?', 'End user license agreement.',
    'The contract you accept when installing software. It sets what you may and may not do with it.',
    'The long text you click Accept on.'),
  ops('pii', 'What does PII stand for?', 'Personally identifiable information.',
    'Names, addresses, ID numbers and anything else that could point to one person must be handled with care.',
    'Information that identifies a person.'),
  ops('ext-ps1', 'Which file extension marks a PowerShell script?', '.ps1.',
    'PowerShell scripts run commands and manage Windows, but execution policy can stop them running.',
    'It begins with the shell’s initials.'),
  ops('ext-bat', 'Which file extension marks a Windows batch file?', '.bat.',
    'It runs a list of command-prompt commands in order, such as one that maps drives at sign-in.',
    'A batch, abbreviated.'),
  ops('ext-sh', 'Which file extension marks a shell script on Linux?', '.sh.',
    'You may need to make it executable with chmod before you can run it.',
    'The first two letters of shell.'),
  ops('ext-py', 'Which file extension marks a Python script?', '.py.',
    'It runs with the Python interpreter and is popular for automating admin tasks.',
    'The first two letters of the language.'),
  ops('ext-js', 'Which file extension marks a JavaScript file?', '.js.',
    'It runs in the browser or in a runtime such as Node.',
    'Two letters for the language.'),
  ops('asset-inventory', 'What is a list of all the hardware and software an organisation owns called?', 'An asset inventory.',
    'It shows what you have, where it is, who uses it and when warranties and licences expire.',
    'A list of assets.'),
  ops('network-diagram', 'What document shows how devices on a network are connected?', 'A network diagram.',
    'It helps you find where a fault can be and plan a change without breaking something.',
    'A picture of the network.'),
];
