import type { Card } from './types';

/**
 * CS50 / intro CS, short-answer cards. Every answer is a name, a keyword or a
 * short phrase, so each one is fair game for the typing stages as well as for
 * flashcards and review. Written from scratch: CS50's own materials are
 * CC BY-NC-SA 4.0 and none of it is copied here.
 */
const make = (domain: string) => (slug: string, front: string, back: string, why: string, hint: string): Card => ({
  id: `${domain}-t-${slug}`,
  domainId: domain,
  front,
  back,
  why,
  hint,
  provenance: 'original',
});

const w0 = make('cs50-w0');
const w1 = make('cs50-w1');
const w2 = make('cs50-w2');
const w3 = make('cs50-w3');
const w4 = make('cs50-w4');
const w5 = make('cs50-w5');
const w6 = make('cs50-w6');
const w7 = make('cs50-w7');
const w8 = make('cs50-w8');
const w9 = make('cs50-w9');

export const SHORT_CS50_CARDS: Card[] = [
  // ---- Week 0: computational thinking and binary
  w0('bin-1111', 'What is 1111 in binary, as a decimal number?', '15.',
    'The place values from the right are 1, 2, 4 and 8, so a 1 in every place is 8 + 4 + 2 + 1. Four bits cannot hold more than that.',
    'Add up the place value of every 1.'),
  w0('dec-10', 'How do you write the decimal number 10 in binary?', '1010.',
    'Ten is eight plus two, so the eights place and the twos place hold a 1 and the fours and ones hold a 0.',
    'One eight and one two, nothing else.'),
  w0('byte', 'How many bits make up one byte?', 'Eight.',
    'A byte is the unit memory is counted in. Eight bits give 256 patterns, enough for one ASCII character.',
    'The prefix in "octet" tells you.'),
  w0('hex', 'Which number system uses the digits 0 to 9 and then the letters A to F?', 'Hexadecimal.',
    'It is base 16: sixteen symbols, with A to F standing for 10 to 15. Programmers like it because it packs bits tidily.',
    'Base sixteen.'),
  w0('hex-bits', 'How many bits does one hexadecimal digit stand for?', 'Four.',
    'Sixteen is two to the fourth power, so each hex digit maps to a group of exactly four bits. That is why colour codes and addresses are written in hex.',
    'Sixteen values is two to the power of this.'),
  w0('ascii-a', 'What decimal number is the ASCII code for a capital A?', '65.',
    'Capitals run from 65 (A) to 90 (Z) and lowercase from 97 (a) to 122 (z), so a letter and its capital differ by 32.',
    'Capital letters start in the sixties.'),
  w0('unicode', 'Which standard gives the characters of every writing system, and emoji, their own code?', 'Unicode.',
    'ASCII only had room for English letters. Unicode assigns a number to symbols from all writing systems, and UTF-8 is the usual way to store them.',
    'It extends ASCII far beyond English.'),
  w0('rgb', 'What do the three numbers in an RGB colour stand for?', 'Amounts of red, green and blue.',
    'A screen pixel mixes three lights. Each number, usually 0 to 255, says how strong one of them is, so 0, 0, 0 is black.',
    'One number for each primary light.'),
  w0('pseudocode', 'What is it called when you write a solution as plain-language steps before coding it?', 'Pseudocode.',
    'Planning in words lets you check the logic without fighting syntax. It also makes the translation into any language easier.',
    'Not real code, just the plan.'),
  w0('boolean', 'What kind of value can only ever be true or false?', 'A Boolean.',
    'Conditions such as x > 5 evaluate to one. The word comes from the logician George Boole.',
    'Named after a logician.'),
  w0('loop', 'What do you call a set of steps that repeats until a condition changes?', 'A loop.',
    'Loops save you from writing the same line a hundred times and let a program react to how much data it is given.',
    'It goes round and round.'),
  w0('debug', 'What is the word for finding and fixing mistakes in a program?', 'Debugging.',
    'Printing values, stepping through code and explaining it aloud to a rubber duck are all ways to find where reality parts from your plan.',
    'Hunting the bugs down.'),

  // ---- Week 1: C basics
  w1('printf', 'Which C function prints formatted text to the screen?', 'printf.',
    'The f is for formatted: placeholders in the first argument are filled by the values after it.',
    'Print, with a formatting f on the end.'),
  w1('fmt-string', 'Which printf placeholder prints a string?', '%s.',
    'Each placeholder expects a matching type: %s a string, %c a character, %i an int, %f a float.',
    'The letter is the first one of the type.'),
  w1('fmt-int', 'Which printf placeholder prints an int?', '%i.',
    '%d does the same job. Using the wrong placeholder for a type prints nonsense or crashes.',
    'Think of the first letter of the word.'),
  w1('fmt-char', 'Which printf placeholder prints a single character?', '%c.',
    'A char is stored as a small number, so the placeholder decides whether you see the letter or the code.',
    'The first letter of the word character.'),
  w1('semicolon', 'What punctuation ends most statements in C?', 'A semicolon.',
    'It tells the compiler where one instruction stops. A missing one is the most common first error message.',
    'A comma with a dot above it.'),
  w1('main-type', 'What return type does main have in the programs you write?', 'int.',
    'main returns an integer status to the operating system, with 0 meaning success.',
    'The same type as a whole number.'),
  w1('strlen-header', 'Which header declares strlen?', 'string.h.',
    'Most functions live in a header you must include first, or the compiler does not know their names.',
    'The header about text handling.'),
  w1('char-size', 'How many bytes is a char in C?', 'One byte.',
    'A char holds a single ASCII character, so eight bits are enough.',
    'It is the smallest type there is.'),
  w1('int-size', 'On a typical computer, how many bytes is an int?', 'Four bytes.',
    'Four bytes are 32 bits, which gives roughly plus or minus two billion.',
    'Thirty-two bits divided by eight.'),
  w1('stdbool', 'Which header gives you the bool type in C?', 'stdbool.h.',
    'Plain C had no Boolean type for decades. This header adds bool, true and false.',
    'Standard plus the type name.'),
  w1('make', 'Which command builds hello.c into a program called hello?', 'make hello.',
    'make works out the compiler command for you and leaves a runnable file with no extension.',
    'The build tool, then the file name without .c.'),
  w1('run-dot-slash', 'How do you run a program named hello that sits in the current folder?', './hello.',
    'The dot means this folder. Without it the shell only searches the folders on your PATH.',
    'Dot, slash, then the name.'),
  w1('modulo', 'Which operator gives the remainder after a division?', 'Modulo.',
    'It is written %. 17 % 5 is 2, and it is how you test for even numbers or wrap a counter around.',
    'It is not division, it is what is left over.'),
  w1('comment', 'Which symbols start a one-line comment in C?', 'Two forward slashes.',
    'The compiler ignores everything after them on that line. Comments explain why, not what.',
    'Two of the same stroke, leaning one way.'),

  // ---- Week 2: arrays and strings
  w2('null-char', 'Which character marks the end of a C string?', 'The null character.',
    'Strings are arrays of chars with a hidden zero byte at the end. Functions such as printf read until they meet it.',
    'Its value is zero.'),
  w2('null-escape', 'How do you write the null character in C source code?', 'Backslash zero.',
    'The escape \\0 is a char whose value is 0. It is what strlen stops at.',
    'An escape character followed by a digit.'),
  w2('first-index', 'What index does the first element of a C array have?', 'Zero.',
    'The index is the distance from the start of the array, and the first element is zero steps away.',
    'It is the distance from the start.'),
  w2('last-index', 'If an array has n elements, what is the index of the last one?', 'n minus 1.',
    'Indexes run from 0 to n - 1. Reading index n steps past the end into memory you do not own.',
    'One less than the length.'),
  w2('hi-bytes', 'How many bytes does the string "hi" take up, counting its end marker?', '3 bytes.',
    'Two letters plus the null character. Forgetting the extra byte is how strings overflow their arrays.',
    'Two letters plus something hidden.'),
  w2('strcmp', 'Which function compares two C strings?', 'strcmp.',
    'Using == on strings compares addresses, not text. strcmp returns 0 when the two are equal.',
    'String, then compare, in short.'),
  w2('strcpy', 'Which function copies one C string into another?', 'strcpy.',
    'The destination must be big enough for the text and its null character, or the copy overruns it.',
    'String, then copy, in short.'),
  w2('toupper', 'Which function converts a char to uppercase?', 'toupper.',
    'It returns the capital version of a letter and leaves anything else alone.',
    'The opposite of tolower.'),
  w2('isalpha', 'Which function tells you whether a char is a letter?', 'isalpha.',
    'The is... family answers yes or no: isdigit, isupper, isspace and friends.',
    'It starts with is and ends with what a letter belongs to.'),
  w2('ctype', 'Which header declares toupper and isalpha?', 'ctype.h.',
    'It is the header for character types, so every function about one character lives there.',
    'Short for character type.'),
  w2('double-quotes', 'Which kind of quotes wrap a string in C?', 'Double quotes.',
    '"a" is a string of two bytes, the letter and the null. Mixing the two kinds of quote is a classic early mistake.',
    'The longer pair.'),
  w2('single-quotes', 'Which kind of quotes wrap a single character in C?', 'Single quotes.',
    '\'a\' is one char with a numeric value, which is why \'a\' + 1 gives \'b\'.',
    'The pair for just one.'),
  w2('first-char', 'What does s[0] give for the string "cat"?', 'The letter c.',
    'Square brackets pick one char out of the array, counting from zero.',
    'The first letter.'),

  // ---- Week 3: algorithms
  w3('binary-time', 'In plain words, how fast is binary search?', 'Logarithmic time.',
    'Each step throws away half of what is left, so a million sorted items need only about twenty looks.',
    'Halving, again and again.'),
  w3('linear-time', 'What running time does linear search have in the worst case?', 'Linear time.',
    'If the item is last, or missing, you look at every element once.',
    'It grows in step with the number of items.'),
  w3('quadratic', 'Which running time do bubble sort and selection sort have in the worst case?', 'Quadratic time.',
    'Two nested loops over n items means about n times n steps, so doubling the data quadruples the work.',
    'The input size squared.'),
  w3('merge-time', 'What is the running time of merge sort?', 'n log n.',
    'It splits log n times and does n work merging at each level. That is far faster than n squared on big lists.',
    'Between linear and quadratic.'),
  w3('selection', 'Which sort repeatedly picks the smallest remaining item and puts it next?', 'Selection sort.',
    'It scans the unsorted part for the minimum every time, which is why it is slow even on sorted input.',
    'It selects the minimum.'),
  w3('bubble', 'Which sort swaps neighbouring items that are out of order, again and again?', 'Bubble sort.',
    'The largest values bubble towards the end on each pass.',
    'Big values rise like bubbles.'),
  w3('merge', 'Which sort splits the list in half, sorts each half, then combines them?', 'Merge sort.',
    'It is a divide-and-conquer recursion that does its real work while merging two sorted halves.',
    'The combining step is the clever part.'),
  w3('insertion', 'Which sort grows a sorted section by inserting each next item into place?', 'Insertion sort.',
    'It is how many people sort a hand of cards. It is quick on nearly sorted data.',
    'Like sorting playing cards in your hand.'),
  w3('base-case', 'What stops a recursive function from calling itself forever?', 'A base case.',
    'It is the input simple enough to answer directly. Every recursive call has to move towards it.',
    'The simplest case with a direct answer.'),
  w3('big-o', 'Which notation describes an upper bound on running time?', 'Big O.',
    'It says the algorithm takes no more than this, up to a constant. It is the one people quote most.',
    'The letter that looks like a circle.'),
  w3('omega', 'Which notation describes a lower bound on running time?', 'Big Omega.',
    'It says the algorithm needs at least this much. It is the best-case partner of Big O.',
    'A Greek capital letter that closes the gap at the bottom.'),
  w3('theta', 'Which notation says an upper and a lower bound are the same?', 'Big Theta.',
    'When O and Omega agree, the running time is pinned down tightly.',
    'A Greek letter with a bar through it.'),
  w3('sorted-first', 'What must be true of a list before binary search can work on it?', 'It must be sorted.',
    'Throwing away half only works if you know which half cannot hold the answer.',
    'Order matters.'),
  w3('constant', 'What do you call a running time that does not grow with the size of the input?', 'Constant time.',
    'Looking up an array element by index takes the same time whether the array holds ten items or ten million.',
    'It never changes, whatever the size.'),

  // ---- Week 4: memory
  w4('address-of', 'Which operator gives you the address of a variable?', 'The ampersand.',
    'Putting & in front of a variable yields where it lives in memory, which is what a pointer stores.',
    'The symbol that also stands for and.'),
  w4('dereference', 'Which operator follows a pointer to the value it points at?', 'The asterisk.',
    'It is called dereferencing. In a declaration the same star just says "this is a pointer".',
    'A star.'),
  w4('stdlib', 'Which header declares malloc and free?', 'stdlib.h.',
    'It is the general-purpose standard library header, home to memory allocation and conversion functions.',
    'Standard library.'),
  w4('free', 'Which function gives memory from malloc back?', 'free.',
    'Every successful malloc needs exactly one free, or the program leaks memory.',
    'The opposite of allocating.'),
  w4('null', 'Which value means a pointer points at nothing?', 'NULL.',
    'malloc returns it when it cannot find room, so always check before using the pointer.',
    'It is also what ends a linked list.'),
  w4('valgrind', 'Which tool finds memory leaks and invalid memory use?', 'Valgrind.',
    'It runs your program under a microscope and reports lost blocks and reads or writes past an allocation.',
    'A memory checker with a Norse-sounding name.'),
  w4('heap', 'Where does malloc get its memory from?', 'The heap.',
    'The heap holds memory you ask for explicitly and keep until you free it, unlike the stack, which cleans up by itself.',
    'The big region you manage yourself.'),
  w4('stack', 'Where do a function’s local variables live?', 'On the stack.',
    'Each call gets a frame that is thrown away when the function returns, so never return a pointer to a local.',
    'It grows with every call and shrinks on return.'),
  w4('sizeof', 'Which operator returns how many bytes a type takes?', 'sizeof.',
    'You use it with malloc so you ask for the right amount of memory, for example n * sizeof(int).',
    'The size of something.'),
  w4('ptr-size', 'How many bytes is a pointer on a 64-bit system?', '8 bytes.',
    'An address has to be as wide as the machine’s memory addresses, which is 64 bits there.',
    'Sixty-four bits.'),
  w4('hex-prefix', 'What prefix marks a hexadecimal number in C?', '0x.',
    'It is how addresses are printed and how you write them in code, such as 0xFF.',
    'A zero and a letter.'),
  w4('string-pointer', 'In C, what is a string really a pointer to?', 'Its first character.',
    'A string is the address of the first char, and the characters after it follow until the null.',
    'The very start of the text.'),
  w4('memcpy', 'Which function copies raw bytes from one place in memory to another?', 'memcpy.',
    'Unlike strcpy it does not look for a null, so you tell it how many bytes to copy.',
    'Memory plus copy.'),
  w4('stack-overflow', 'What happens when recursion uses up all the stack space?', 'A stack overflow.',
    'Each call needs a frame. Forgetting the base case makes the calls pile up until the program crashes.',
    'It is also the name of a famous Q and A site.'),

  // ---- Week 5: data structures
  w5('lifo', 'In which order does a stack hand items back?', 'Last in, first out.',
    'Think of a pile of plates: you take from the top, so the newest item leaves first.',
    'LIFO is the short form.'),
  w5('fifo', 'In which order does a queue hand items back?', 'First in, first out.',
    'Like a line at a shop, the item that waited longest goes next.',
    'FIFO is the short form.'),
  w5('stack-ops', 'What are the two basic operations of a stack?', 'Push and pop.',
    'Push adds to the top and pop removes the top item.',
    'One adds, one takes away.'),
  w5('queue-ops', 'What are the two basic operations of a queue?', 'Enqueue and dequeue.',
    'You join at the back and leave from the front.',
    'Join the line, leave the line.'),
  w5('struct', 'Which C keyword groups several variables into one new type?', 'struct.',
    'It is how a node holding a value and a pointer, or a person with a name and an age, is defined.',
    'A bundle of fields under one name.'),
  w5('arrow', 'Which operator reaches a field through a pointer to a struct?', 'The arrow operator.',
    'p->x is shorthand for (*p).x. It saves you the awkward brackets.',
    'Written as a dash and a greater-than sign.'),
  w5('head', 'What does a linked list need to keep so you can find its start?', 'A pointer to the head.',
    'Lose the head and you lose the whole list, because every node is reached from the one before it.',
    'The first node.'),
  w5('list-end', 'What does the last node of a singly linked list point to?', 'NULL.',
    'A null next pointer is how you know you have walked off the end.',
    'Nothing at all.'),
  w5('hash-function', 'What turns a key into an array index in a hash table?', 'A hash function.',
    'Good ones spread keys evenly so buckets stay short, and always give the same index for the same key.',
    'It scrambles a key into a number.'),
  w5('chaining', 'Which collision strategy hangs a linked list off each bucket?', 'Chaining.',
    'Keys that land in the same bucket simply join the chain, so nothing is overwritten.',
    'Links in a chain.'),
  w5('probing', 'Which collision strategy steps along to the next free slot?', 'Linear probing.',
    'If the bucket is taken you try the next one, and the next, until you find an empty place.',
    'It keeps feeling along the array.'),
  w5('bst-time', 'How fast is a lookup in a balanced binary search tree?', 'Logarithmic time.',
    'Each comparison throws away half of the remaining tree.',
    'Halving at every step.'),
  w5('root', 'What is the top node of a tree called?', 'The root.',
    'Every other node is reached by walking down from it.',
    'Like the base of a plant, but drawn at the top.'),
  w5('leaf', 'What is a tree node with no children called?', 'A leaf.',
    'It sits at the bottom of a branch, with nothing hanging off it.',
    'The end of a branch.'),
  w5('dynamic-array', 'What data structure resizes itself as you add items, like a Python list?', 'A dynamic array.',
    'When it fills up it allocates a bigger block and copies everything across, so adding is cheap on average.',
    'An array that can grow.'),

  // ---- Week 6: Python
  w6('print', 'Which function prints text to the screen in Python?', 'print.',
    'It adds a newline for you, unlike C’s printf.',
    'The same word as in the question.'),
  w6('input', 'Which function reads a line typed by the user in Python?', 'input.',
    'It always returns a string, so wrap it in int() if you want a number.',
    'The opposite of output.'),
  w6('len', 'Which function returns how many items a list or string holds?', 'len.',
    'It works on lists, strings, dictionaries and tuples alike.',
    'It answers: how many are in here?'),
  w6('range', 'Which function produces a run of integers to loop over?', 'range.',
    'for i in range(5) gives 0, 1, 2, 3, 4. It never includes the end value.',
    'It covers a span of numbers.'),
  w6('def', 'Which keyword defines a function in Python?', 'def.',
    'It is followed by the name, the parameters in brackets and a colon.',
    'You are declaring what a function is.'),
  w6('fstring', 'What do you call a Python string with an f before its opening quote?', 'An f-string.',
    'It lets you write expressions in curly braces, such as f"hello, {name}", and fills them in.',
    'F for format.'),
  w6('floor-div', 'Which operator does floor division in Python?', 'Two slashes.',
    '7 // 2 is 3. A single slash gives a float, 3.5.',
    'The division sign, doubled.'),
  w6('power', 'Which operator raises a number to a power in Python?', 'Two asterisks.',
    '2 ** 10 is 1024. The caret means something else (XOR).',
    'The times sign, doubled.'),
  w6('none', 'What value means no value at all in Python?', 'None.',
    'A function with no return statement gives it back. Compare it with the is operator.',
    'Written with a capital N.'),
  w6('pip', 'Which tool installs Python packages?', 'pip.',
    'pip install requests downloads a package from PyPI into your environment.',
    'Three letters, a package installer.'),
  w6('import', 'Which keyword brings a module into your program?', 'import.',
    'It makes everything in the module available, like import random or from sys import argv.',
    'The opposite of export.'),
  w6('append', 'Which list method adds an item to the end?', 'append.',
    'Lists grow in place: names.append("Ada") changes names and returns nothing.',
    'Add on to the end.'),
  w6('sort', 'Which list method sorts it in place?', 'sort.',
    'The built-in sorted() returns a new list instead and leaves the original alone.',
    'Put them in order.'),
  w6('keys', 'Which dictionary method gives you all its keys?', 'keys.',
    'You can loop over it, or loop over the dictionary itself, which does the same thing.',
    'The things you look values up by.'),
  w6('argv', 'Which list holds the command-line arguments in Python?', 'sys.argv.',
    'You import sys first. Item 0 is the script’s own name, as in C.',
    'It lives in the sys module.'),
  w6('pylist-index', 'What does the index -1 give for a Python list?', 'The last item.',
    'Negative indexes count from the end, which saves you from writing len(items) - 1.',
    'Counting from the other side.'),

  // ---- Week 7: SQL
  w7('select', 'Which SQL keyword chooses the columns to return?', 'SELECT.',
    'Every query that reads data starts with it, followed by the column names or a star for all of them.',
    'Pick what to show.'),
  w7('from', 'Which clause names the table a query reads from?', 'FROM.',
    'SELECT says which columns, FROM says which table.',
    'Which table it comes out of.'),
  w7('where', 'Which clause filters rows before they are grouped?', 'WHERE.',
    'It keeps only the rows for which the condition is true.',
    'The condition goes here.'),
  w7('order-by', 'Which clause sorts the rows a query returns?', 'ORDER BY.',
    'Add DESC after the column to put the biggest values first.',
    'Two words, the second is BY.'),
  w7('limit', 'Which clause caps how many rows come back?', 'LIMIT.',
    'Combine it with ORDER BY to get the top five or the newest ten.',
    'A ceiling on the count.'),
  w7('insert', 'Which statement adds a new row to a table?', 'INSERT INTO.',
    'You name the table, then the columns, then the VALUES to put in them.',
    'Put something in.'),
  w7('update', 'Which statement changes values in rows that already exist?', 'UPDATE.',
    'Always add a WHERE, or every row in the table is changed.',
    'Make existing rows current.'),
  w7('delete', 'Which statement removes rows from a table?', 'DELETE.',
    'Without a WHERE it removes every row. Try the same condition in a SELECT first.',
    'Take rows away.'),
  w7('create-table', 'Which statement makes a new table?', 'CREATE TABLE.',
    'You list each column with its type, and mark the primary key.',
    'Build a new one.'),
  w7('drop-table', 'Which statement removes an entire table and its rows?', 'DROP TABLE.',
    'It cannot be undone, so it is the command to double-check.',
    'Let it fall away.'),
  w7('count', 'Which function counts rows?', 'COUNT.',
    'COUNT(*) counts all rows, and COUNT(column) skips the NULLs.',
    'How many?'),
  w7('avg', 'Which function averages a column of numbers?', 'AVG.',
    'It ignores NULLs, which can make the answer differ from what you expect.',
    'The mean, abbreviated.'),
  w7('distinct', 'Which keyword removes duplicate rows from a result?', 'DISTINCT.',
    'SELECT DISTINCT city returns each city once, however many rows mention it.',
    'Only one of each.'),
  w7('like', 'Which operator matches text against a pattern with wildcards?', 'LIKE.',
    'WHERE name LIKE "A%" finds everything starting with A.',
    'Similar to.'),
  w7('percent', 'Which character matches any run of characters in a LIKE pattern?', 'The percent sign.',
    'The underscore matches exactly one character.',
    'A symbol you also see on a discount tag.'),
  w7('sqlite', 'Which lightweight database engine keeps a whole database in a single file?', 'SQLite.',
    'There is no server to run, which is why it is on phones and in so many apps.',
    'The light one.'),

  // ---- Week 8: HTML, CSS and JavaScript
  w8('a-tag', 'Which HTML element makes a link?', 'The a tag.',
    'The href attribute holds the address. The text between the tags is what the reader clicks.',
    'Short for anchor.'),
  w8('alt', 'Which img attribute describes a picture for screen readers?', 'alt.',
    'It is also what shows when the image fails to load, so write what the image means, not "image".',
    'The words that stand in for the picture.'),
  w8('h1', 'Which element is the main heading of a page?', 'h1.',
    'Headings give a page its outline, and h1 to h6 go from most to least important.',
    'The first level.'),
  w8('ul', 'Which element makes a bulleted list?', 'ul.',
    'Each item goes in an li element. ol is the numbered version.',
    'An unordered list.'),
  w8('css-color', 'Which CSS property sets the colour of text?', 'color.',
    'It is spelled the American way, which trips up everyone who types colour.',
    'Spelled without the u.'),
  w8('bg-color', 'Which CSS property sets the background colour?', 'background-color.',
    'It can take a name, a hex code or an rgb value.',
    'Two words joined with a hyphen.'),
  w8('margin', 'Which box-model layer sits outside the border?', 'The margin.',
    'It is the clear space between this element and its neighbours.',
    'It pushes other elements away.'),
  w8('padding', 'Which box-model layer sits between the content and the border?', 'The padding.',
    'It is breathing room inside the element and takes on its background.',
    'Think of cushioning inside the box.'),
  w8('display-flex', 'Which display value turns on flexbox?', 'flex.',
    'The children then line up in a row or column and can share the space between them.',
    'The layout that bends to fit.'),
  w8('class-selector', 'Which character starts a class selector in CSS?', 'A dot.',
    '.note targets class="note". An id selector starts with a hash instead.',
    'A full stop.'),
  w8('id-selector', 'Which character starts an id selector in CSS?', 'A hash sign.',
    '#top targets the one element with id="top". Ids are meant to be unique on a page.',
    'The number sign.'),
  w8('console-log', 'Which method writes to the browser’s console?', 'console.log.',
    'It is the quickest way to see what a variable holds while you debug.',
    'The console object, then log.'),
  w8('query-selector', 'Which method finds an element using a CSS selector?', 'querySelector.',
    'It returns the first match. querySelectorAll returns all of them.',
    'It asks the document a question.'),
  w8('add-listener', 'Which method attaches an event handler to an element?', 'addEventListener.',
    'You give it the event name, such as click, and a function to run when it happens.',
    'Add something that listens.'),
  w8('array-map', 'Which array method makes a new array by transforming every item?', 'map.',
    'It leaves the original alone. filter keeps some items and reduce combines them into one value.',
    'Transform each one.'),
  w8('json', 'What does JSON stand for?', 'JavaScript Object Notation.',
    'It is a plain-text format for data that almost every language can read and write.',
    'Three words, the first is a language.'),
  w8('viewport', 'Which meta tag name makes a page scale properly on a phone?', 'viewport.',
    'Without it a phone pretends to be a wide desktop screen and shrinks everything.',
    'The visible part of the screen.'),

  // ---- Week 9: Flask and web applications
  w9('flask-run', 'Which command starts a Flask app in development?', 'flask run.',
    'It starts the built-in development server, which reloads when you save.',
    'The framework’s name, then a verb.'),
  w9('render-template', 'Which Flask function fills in a template and returns HTML?', 'render_template.',
    'You pass the template’s file name and the values it should show.',
    'It renders a template, with an underscore.'),
  w9('request', 'Which Flask object holds the data of the incoming request?', 'request.',
    'request.form, request.args and request.method are all read from it.',
    'What the browser sent.'),
  w9('jinja-var', 'Which delimiters print a value in a Jinja template?', 'Double curly braces.',
    '{{ name }} is replaced with the value, and Jinja escapes any HTML in it.',
    'A pair of the squiggly brackets, doubled.'),
  w9('static-folder', 'In which folder does Flask look for CSS, images and scripts?', 'static.',
    'Files there are served as they are, with no Python involved.',
    'Files that do not change.'),
  w9('templates-folder', 'In which folder does Flask look for its HTML templates?', 'templates.',
    'render_template looks here automatically, so you only give the file name.',
    'The folder named after the files it holds.'),
  w9('http-get', 'Which HTTP method should only be used to read data?', 'GET.',
    'It must not change anything, so it is safe to repeat or bookmark.',
    'Fetch it.'),
  w9('http-post', 'Which HTTP method sends form data to change something?', 'POST.',
    'The data travels in the body of the request, not in the address, so it stays out of the URL.',
    'Send it.'),
  w9('status-404', 'Which HTTP status code means not found?', '404.',
    'The server is fine, but nothing exists at that address.',
    'The most famous error number.'),
  w9('status-200', 'Which HTTP status code means everything went fine?', '200.',
    'It is the code you hope to get back for every request.',
    'Two hundred and nothing else.'),
  w9('status-500', 'Which HTTP status code means the server hit an error?', '500.',
    'It is the server’s fault, not the visitor’s, and usually means an exception in your code.',
    'The first of the five hundreds.'),
  w9('salted-hash', 'What should a password be turned into before it is stored?', 'A salted hash.',
    'A hash cannot be reversed, and a unique random salt stops two equal passwords looking the same.',
    'One-way and seasoned.'),
  w9('https', 'Which protocol encrypts traffic between a browser and a website?', 'HTTPS.',
    'The S is for secure. It stops anyone on the way reading or changing what is sent.',
    'The web, with a padlock.'),
  w9('view', 'In the MVC pattern, which part shows data to the user?', 'The view.',
    'The model holds the data, the controller decides what to do, and the view is what you see.',
    'It is what the user looks at.'),
];
